// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"153":3,"155":5,"161":8,"162":8,"165":9,"167":10,"171":12,"173":13,"182":15,"183":15,"186":16,"188":17,"191":19,"194":21,"196":22,"198":23,"200":24,"201":24,"202":25,"211":27,"212":27,"215":28,"217":29,"220":31,"223":33,"225":34,"227":35,"228":35,"229":36} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Counters: value (line 5)
//
// ENDPOINTS:
//   GET /api/count (line 8)
//   POST /api/increment (line 15)
//   POST /api/reset (line 27)
//
// DATAFLOW: Client ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});

// Built-in utilities
function _clear_len(val) { if (val == null) return 0; if (typeof val === "string" || Array.isArray(val)) return val.length; if (typeof val === "object") return Object.keys(val).length; return 0; }
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    counters: { line: 5, file: "main.clear", fields: { value: { type: "number" } } },
  },
  endpoints: {
    "GET /api/count": { line: 8, file: "main.clear", auth: false },
    "POST /api/increment": { line: 15, file: "main.clear", auth: false },
    "POST /api/reset": { line: 27, file: "main.clear", auth: false },
  }
} : null;

// clear:3
// Database: local memory (JSON file backup)
// clear:5
// Data shape: Counters
const CountersSchema = {
  value: { type: "number", default: 0 }
};
db.createTable('counters', CountersSchema);
// clear:8
// clear:8 — GET /api/count
app.get('/api/count', async (req, res) => {
  try {
    // clear:9
    const rows = (await db.findAll('counters', {}, { limit: 50 })).map(_revive);
    // clear:10
    if (_clear_len(rows) == 0) {
      return res.json({ count: 0 });
    }
    // clear:12
    let first_row = rows[0];
    // clear:13
    return res.json({ count: first_row?.value });
  } catch (err) {
    console.error('[GET /api/count] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/count', line: 8, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:15
// clear:15 — POST /api/increment
app.post('/api/increment', async (req, res) => {
  try {
    // clear:16
    const rows = (await db.findAll('counters', {}, { limit: 50 })).map(_revive);
    // clear:17
    if (_clear_len(rows) == 0) {
      let new_entry = { value: 1 };
      const saved = await _clearTry(() => db.insert('counters', _pick(new_entry, CountersSchema)), { op: 'insert', table: 'counters', line: 19, file: 'main.clear', source: "" }); // clear:19
      return res.json({ count: 1 });
    }
    // clear:21
    let first_row = rows[0];
    // clear:22
    let new_value = (first_row?.value + 1);
    // clear:23
    let updated = { value: new_value, id: first_row?.id };
    // clear:24
    await _clearTry(() => db.update('counters', _pick(updated, CountersSchema)), { op: 'update', table: 'counters', line: 24, file: 'main.clear', source: "" }); // clear:24
    // clear:25
    return res.json({ count: new_value });
  } catch (err) {
    console.error('[POST /api/increment] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/increment', line: 15, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:27
// clear:27 — POST /api/reset
app.post('/api/reset', async (req, res) => {
  try {
    // clear:28
    const rows = (await db.findAll('counters', {}, { limit: 50 })).map(_revive);
    // clear:29
    if (_clear_len(rows) == 0) {
      let zero_entry = { value: 0 };
      const new_counter = await _clearTry(() => db.insert('counters', _pick(zero_entry, CountersSchema)), { op: 'insert', table: 'counters', line: 31, file: 'main.clear', source: "" }); // clear:31
      return res.json({ count: 0 });
    }
    // clear:33
    let first_row = rows[0];
    // clear:34
    let reset_counter = { value: 0, id: first_row?.id };
    // clear:35
    await _clearTry(() => db.update('counters', _pick(reset_counter, CountersSchema)), { op: 'update', table: 'counters', line: 35, file: 'main.clear', source: "" }); // clear:35
    // clear:36
    return res.json({ count: 0 });
  } catch (err) {
    console.error('[POST /api/reset] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/reset', line: 27, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});