#!/usr/bin/env node
// E2E tests -- auto-generated by Clear compiler
// Run: node test.js
// Requires: server running on localhost:3000

const BASE = process.env.TEST_URL || "http://localhost:3000";
let passed = 0, failed = 0;
let _emailCounter = 0;
let _uniqueCounter = 0;
function _uniqueEmail() { return "test" + (++_emailCounter) + "@example.com"; }
function _uniqueText(base) { return base + "_" + (++_uniqueCounter); }

// Note: for clean re-runs, delete clear-data.json before starting the server
// unique constraints may cause 500s if stale data exists from a previous run

// Generate a test auth token using the same runtime as the server
const auth = require("./clear-runtime/auth");
const TEST_TOKEN = auth.createToken({ id: 1, role: "admin", email: "test@test.com" });
const AUTH_HEADERS = { "Authorization": "Bearer " + TEST_TOKEN, "Content-Type": "application/json" };

async function test(name, fn) {
  try {
    await fn();
    passed++;
    console.log("PASS:", name);
  } catch (err) {
    failed++;
    console.log("FAIL:", name, "-", err.message);
  }
}

function assert(condition, msg) { if (!condition) throw new Error(msg); }

async function run() {
  await test("GET /api/health returns 200", async () => {
    const r = await fetch(BASE + "/api/health");
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("GET /api/models returns 200", async () => {
    const r = await fetch(BASE + "/api/models", { headers: AUTH_HEADERS });
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("GET /api/models/:id returns 200 or 404", async () => {
    const r = await fetch(BASE + "/api/models/1", { headers: AUTH_HEADERS });
    assert(r.status === 200 || r.status === 404, "Expected 200 or 404, got " + r.status);
  });

  await test("GET /api/chat/:session_id returns 200 or 404", async () => {
    const r = await fetch(BASE + "/api/chat/1", { headers: AUTH_HEADERS });
    assert(r.status === 200 || r.status === 404, "Expected 200 or 404, got " + r.status);
  });

  await test("GET /api/share/:sheet_id returns 200 or 404", async () => {
    const r = await fetch(BASE + "/api/share/1");
    assert(r.status === 200 || r.status === 404, "Expected 200 or 404, got " + r.status);
  });

  await test("POST /api/models with valid data returns 201", async () => {
    const payload = {"name":"Test value","type":"Test value"};
    payload["name"] = _uniqueText("name");
    payload["type"] = _uniqueText("type");
    const r = await fetch(BASE + "/api/models", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.id, "Response should have an id");
  });

  await test("POST /api/models with no body returns 400", async () => {
    const r = await fetch(BASE + "/api/models", { method: "POST" });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/models with empty required field returns 400", async () => {
    const r = await fetch(BASE + "/api/models", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify({ name: "" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/predict with valid data returns 201", async () => {
    const payload = {"model_id":"Test value","input_data":"Test value"};
    payload["model_id"] = _uniqueText("model_id");
    payload["input_data"] = _uniqueText("input_data");
    const r = await fetch(BASE + "/api/predict", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.id, "Response should have an id");
  });

  await test("POST /api/predict with no body returns 400", async () => {
    const r = await fetch(BASE + "/api/predict", { method: "POST" });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/predict with empty required field returns 400", async () => {
    const r = await fetch(BASE + "/api/predict", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify({ model_id: "" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/chat with valid data returns 201", async () => {
    const payload = {"role":"Test value","content":"Test value","session_id":"Test value"};
    payload["role"] = _uniqueText("role");
    payload["content"] = _uniqueText("content");
    payload["session_id"] = _uniqueText("session_id");
    const r = await fetch(BASE + "/api/chat", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.id, "Response should have an id");
  });

  await test("POST /api/chat with no body returns 400", async () => {
    const r = await fetch(BASE + "/api/chat", { method: "POST" });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/chat with empty required field returns 400", async () => {
    const r = await fetch(BASE + "/api/chat", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify({ role: "" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/share with valid data returns 201", async () => {
    const payload = {"sheet_id":"Test value","code":"Test value"};
    payload["sheet_id"] = _uniqueText("sheet_id");
    payload["code"] = _uniqueText("code");
    const r = await fetch(BASE + "/api/share", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.id, "Response should have an id");
  });

  await test("POST /api/share with no body returns 400", async () => {
    const r = await fetch(BASE + "/api/share", { method: "POST" });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/share with empty required field returns 400", async () => {
    const r = await fetch(BASE + "/api/share", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify({ sheet_id: "" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/export with valid data returns 200", async () => {
    const payload = {"format":"Test value"};
    payload["format"] = _uniqueText("format");
    const r = await fetch(BASE + "/api/export", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify(payload)
    });
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("POST /api/export with no body returns 400", async () => {
    const r = await fetch(BASE + "/api/export", { method: "POST" });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/export with empty required field returns 400", async () => {
    const r = await fetch(BASE + "/api/export", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify({ format: "" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/models strips unknown fields (mass assignment protection)", async () => {
    const payload = { ...{"name":"Test value","type":"Test value"}, admin: true, role: "superuser" };
    payload["name"] = _uniqueText("name");
    payload["type"] = _uniqueText("type");
    const r = await fetch(BASE + "/api/models", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.admin === undefined, "admin field should have been stripped");
    assert(data.role === undefined, "role field should have been stripped");
  });

  await test("GET /api/models returns created records after POST", async () => {
    const r = await fetch(BASE + "/api/models", { headers: AUTH_HEADERS });
    const data = await r.json();
    assert(Array.isArray(data), "Expected array");
    assert(data.length > 0, "Expected at least one record (from earlier POST test)");
  });

  console.log("");
  console.log("Results:", passed, "passed,", failed, "failed");
  process.exit(failed > 0 ? 1 : 0);
}

run();