// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"152":3,"154":5,"164":12,"165":12,"170":13,"174":15,"178":17,"182":19,"183":19,"184":20,"194":22,"195":22,"198":23,"200":24,"209":26,"210":26,"213":27,"215":28} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Leads: company*, email*, size*, assigned_to, created_at_date (line 5)
//
// ENDPOINTS:
//   POST /api/leads (line 12)
//   GET /api/leads (line 22)
//   GET /api/leads/by/:rep (line 26)
//
// DATAFLOW: Client ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    leads: { line: 5, file: "main.clear", fields: { company: { required: true, type: "text" }, email: { required: true, type: "text" }, size: { required: true, type: "text" }, assigned_to: { type: "text" }, created_at_date: { type: "timestamp" } } },
  },
  endpoints: {
    "POST /api/leads": { line: 12, file: "main.clear", auth: false },
    "GET /api/leads": { line: 22, file: "main.clear", auth: false },
    "GET /api/leads/by/:rep": { line: 26, file: "main.clear", auth: false },
  }
} : null;

// clear:3
// Database: local memory (JSON file backup)
// clear:5
// Data shape: Leads
const LeadsSchema = {
  company: { type: "text", required: true },
  email: { type: "text", required: true },
  size: { type: "text", required: true },
  assigned_to: { type: "text" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('leads', LeadsSchema);
// clear:12
// clear:12 — POST /api/leads
app.post('/api/leads', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const lead = req.body;
    // clear:13
    if (lead?.size == "Enterprise") {
      lead.assigned_to = "alice";
    }
    // clear:15
    if (lead?.size == "Mid-Market") {
      lead.assigned_to = "bob";
    }
    // clear:17
    if (lead?.size == "SMB") {
      lead.assigned_to = "charlie";
    }
    // clear:19
    const saved = await _clearTry(() => db.insert('leads', _pick(lead, LeadsSchema)), { op: 'insert', table: 'leads', line: 19, file: 'main.clear', source: "" }); // clear:19
    // clear:20
    return res.status(201).json(saved);
  } catch (err) {
    console.error('[POST /api/leads] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/leads', line: 12, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:22
// clear:22 — GET /api/leads
app.get('/api/leads', async (req, res) => {
  try {
    // clear:23
    const leads = (await db.findAll('leads', {}, { limit: 50 })).map(_revive);
    // clear:24
    return res.json(leads);
  } catch (err) {
    console.error('[GET /api/leads] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/leads', line: 22, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:26
// clear:26 — GET /api/leads/by/:rep
app.get('/api/leads/by/:rep', async (req, res) => {
  try {
    // clear:27
    const results = (await db.findAll('leads', {}, { limit: 50 })).map(_revive);
    // clear:28
    return res.json(results);
  } catch (err) {
    console.error('[GET /api/leads/by/:rep] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/leads/by/:rep', line: 26, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});