// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"160":14,"162":18,"171":25,"172":25,"180":26,"182":29,"183":29,"184":30,"186":33,"187":33,"188":34,"190":37,"191":37,"192":38,"202":40,"203":40,"206":41,"208":42,"210":43,"212":44} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Sales: amount*, region, sold_at_date (line 18)
//
// ENDPOINTS:
//   POST /api/seed (line 25)
//   GET /api/kpis (line 40)
//
// PAGES:
//   'KPIs' at / (line 48)
//
// DATAFLOW: Frontend ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    sales: { line: 18, file: "main.clear", fields: { amount: { required: true, type: "number" }, region: { type: "text" }, sold_at_date: { type: "timestamp" } } },
  },
  endpoints: {
    "POST /api/seed": { line: 25, file: "main.clear", auth: false },
    "GET /api/kpis": { line: 40, file: "main.clear", auth: false },
  }
} : null;

// DATAFLOW:
// ┌──────────┐   POST /api/seed    ┌──────────┐   save   ┌─────────┐
// │ Browser  │ ─────────────────→  │  Server  │ ────────→ │  Sales  │
// │          │   GET /api/kpis     │          │          │   DB    │
// │  KPIs    │ ←── aggregates ──── │          │ ←─ query │         │
// └──────────┘                     └──────────┘          └─────────┘
// 
// PAGE '/' — 3 big KPI numbers: Total Revenue, Order Count, Avg Order Size
// clear:14
// Database: local memory (JSON file backup)
// clear:18
// Data shape: Sales
const SalesSchema = {
  amount: { type: "number", required: true },
  region: { type: "text" },
  sold_at_date: { type: "timestamp", auto: true }
};
db.createTable('sales', SalesSchema);
// Backend
// clear:25
// clear:25 — POST /api/seed
app.post('/api/seed', async (req, res) => {
  try {
    if (process.env.NODE_ENV === 'production') return res.status(403).json({ error: 'Seed endpoint is disabled in production' });
    const _existing = await db.findAll('sales');
    if (_existing.length > 0) return res.json({ message: 'already seeded' });
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const seed = req.body;
    // clear:26
    let sale_1 = { amount: 120, region: "West" };
    // clear:29
    await _clearTry(() => db.insert('sales', _pick(sale_1, SalesSchema)), { op: 'insert', table: 'sales', line: 29, file: 'main.clear', source: "" }); // clear:29
    // clear:30
    let sale_2 = { amount: 340, region: "East" };
    // clear:33
    await _clearTry(() => db.insert('sales', _pick(sale_2, SalesSchema)), { op: 'insert', table: 'sales', line: 33, file: 'main.clear', source: "" }); // clear:33
    // clear:34
    let sale_3 = { amount: 210, region: "North" };
    // clear:37
    await _clearTry(() => db.insert('sales', _pick(sale_3, SalesSchema)), { op: 'insert', table: 'sales', line: 37, file: 'main.clear', source: "" }); // clear:37
    // clear:38
    return res.json({ message: "seeded" });
  } catch (err) {
    console.error('[POST /api/seed] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/seed', line: 25, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:40
// clear:40 — GET /api/kpis
app.get('/api/kpis', async (req, res) => {
  try {
    // clear:41
    let total_revenue = await db.aggregate('sales', 'SUM', 'amount', {});
    // clear:42
    let order_count = await db.aggregate('sales', 'COUNT', 'id', {});
    // clear:43
    let avg_order_size = await db.aggregate('sales', 'AVG', 'amount', {});
    // clear:44
    return res.json({ total_revenue: total_revenue, order_count: order_count, avg_order_size: avg_order_size });
  } catch (err) {
    console.error('[GET /api/kpis] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/kpis', line: 40, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// Frontend

const path = require('path');
app.use(express.static(__dirname));
app.get("/", (req, res) => res.sendFile('index.html', { root: __dirname }));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});