// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"192":18,"202":26,"203":26,"208":27,"209":27,"210":28,"220":30,"221":30,"224":31,"226":31,"235":33,"236":33,"240":34,"242":34,"251":36,"252":36,"257":37,"260":37,"262":38,"272":40,"273":40,"277":41,"278":41,"279":42} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Contacts: name*, email*!, phone, notes (line 18)
//
// ENDPOINTS:
//   POST /api/contacts (line 26)
//   GET /api/contacts (line 30)
//   GET /api/contacts/:id (line 33)
//   PUT /api/contacts/:id (line 36)
//   DELETE /api/contacts/:id (line 40)
//
// DATAFLOW: Client ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// CF-1: runtime instrumentation — fire-and-forget beacons to the Compiler Flywheel.
const _CLEAR_FLYWHEEL_URL = process.env.CLEAR_FLYWHEEL_URL;
const _CLEAR_COMPILE_ROW_ID = process.env.CLEAR_COMPILE_ROW_ID;
function _clearBeacon(event) {
  if (!_CLEAR_FLYWHEEL_URL || !_CLEAR_COMPILE_ROW_ID) return;
  try {
    fetch(_CLEAR_FLYWHEEL_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(Object.assign({ compile_row_id: _CLEAR_COMPILE_ROW_ID, ts: Date.now() }, event)),
      signal: AbortSignal.timeout(500),
    }).catch(() => {});
  } catch {}
}
app.use((req, res, next) => {
  const _t0 = Date.now();
  res.on('finish', () => {
    _clearBeacon({ event_type: 'endpoint_latency', method: req.method, path: req.route ? req.route.path : req.path, status: res.statusCode, duration_ms: Date.now() - _t0 });
  });
  next();
});
app.use((err, req, res, next) => {
  _clearBeacon({ event_type: 'endpoint_error', method: req.method, path: req.path, error_sig: (err && err.message ? String(err.message).substring(0, 200) : 'unknown') });
  next(err);
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    contacts: { line: 18, file: "main.clear", fields: { name: { required: true, type: "text" }, email: { required: true, unique: true, type: "text" }, phone: { type: "text" }, notes: { type: "text" } } },
  },
  endpoints: {
    "POST /api/contacts": { line: 26, file: "main.clear", auth: false },
    "GET /api/contacts": { line: 30, file: "main.clear", auth: false },
    "GET /api/contacts/:id": { line: 33, file: "main.clear", auth: false },
    "PUT /api/contacts/:id": { line: 36, file: "main.clear", auth: false },
    "DELETE /api/contacts/:id": { line: 40, file: "main.clear", auth: false },
  }
} : null;

//   Contact Book — backend-only CRUD
//   ─────────────────────────────────
//   TABLE       Contacts (name, email, phone, notes)
//   ENDPOINTS   POST   /api/contacts          create one
//               GET    /api/contacts          list all
//               GET    /api/contacts/:id      look up one
//               PUT    /api/contacts/:id      update one
//               DELETE /api/contacts/:id      remove one
//   RULES       email column must be a real email and unique
//               (validates and de-dupes automatically)
// Data
// clear:18
// Data shape: Contacts
const ContactsSchema = {
  name: { type: "text", required: true },
  email: { type: "text", required: true, unique: true },
  phone: { type: "text" },
  notes: { type: "text" }
};
db.createTable('contacts', ContactsSchema);
// Backend
// clear:26
// clear:26 — POST /api/contacts
app.post('/api/contacts', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const contact = req.body;
    // clear:27
    await _clearTry(() => db.update('contacts', _pick(contact, ContactsSchema)), { op: 'update', table: 'contacts', line: 27, file: 'main.clear', source: "" }); // clear:27
    // clear:28
    return res.status(201).json(contact);
  } catch (err) {
    console.error('[POST /api/contacts] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/contacts', line: 26, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:30
// clear:30 — GET /api/contacts
app.get('/api/contacts', async (req, res) => {
  try {
    // clear:31
    const _resp_31 = (await db.findAll('contacts', {}, { limit: 50 })).map(_revive);
    // clear:31
    return res.json(_resp_31);
  } catch (err) {
    console.error('[GET /api/contacts] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/contacts', line: 30, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:33
// clear:33 — GET /api/contacts/:id
app.get('/api/contacts/:id', async (req, res) => {
  try {
    const incoming = req.params;
    // clear:34
    const _resp_34 = _revive(await db.findOne('contacts', { id: incoming?.id }));
    // clear:34
    return res.json(_resp_34);
  } catch (err) {
    console.error('[GET /api/contacts/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/contacts/:id', line: 33, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:36
// clear:36 — PUT /api/contacts/:id
app.put('/api/contacts/:id', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const changes = req.body;
    // clear:37
    const _picked_changes = _pick(changes, ContactsSchema);
    _picked_changes.id = req.params.id;
    await _clearTry(() => db.update('contacts', _picked_changes), { op: 'update', table: 'contacts', line: 37, file: 'main.clear', source: "" }); // clear:37
    Object.assign(changes, await db.findOne('contacts', { id: _picked_changes.id }) || {});
    // clear:38
    return res.json(changes);
  } catch (err) {
    console.error('[PUT /api/contacts/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'PUT /api/contacts/:id', line: 36, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:40
// clear:40 — DELETE /api/contacts/:id
app.delete('/api/contacts/:id', async (req, res) => {
  try {
    const incoming = req.params;
    // clear:41
    await _clearTry(() => db.remove('contacts', { id: incoming?.id }), { op: 'remove', table: 'contacts', line: 41, file: 'main.clear', source: "" }); // clear:41
    // clear:42
    return res.status(204).json({ message: "ok" });
  } catch (err) {
    console.error('[DELETE /api/contacts/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'DELETE /api/contacts/:id', line: 40, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});
process.on('SIGINT', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});