// =============================================================================
// CLEAR LANGUAGE — VALIDATOR
// =============================================================================
//
// PURPOSE: Standalone validation passes for Clear ASTs. Checks forward
// references, type mixing, and config usage. Separated from the compiler
// so validation is opt-in — compile() just generates code.
//
// !! MAINTENANCE RULE: Update this diagram whenever you add a new validation
// !! pass. Add the function name to both the diagram AND the validate() call
// !! list below. Every validation function follows the same pattern:
// !! function validateX(body, errors_or_warnings) — walks AST, pushes issues.
//
// ARCHITECTURE:
//
//   AST (from parser.js)
//       │
//       ▼
//   ┌──────────────────────────────────────────────────────┐
//   │  validate(ast) → { errors[], warnings[] }             │
//   │                                                       │
//   │  Runs these passes in order:                          │
//   │                                                       │
//   │  ERRORS (block compilation):                          │
//   │    ├─ validateForwardReferences ... undeclared vars    │
//   │    ├─ validateTypes .............. type mismatches     │
//   │    └─ validateSecurity .......... missing auth guards  │
//   │                                                       │
//   │  WARNINGS (quality + safety):                         │
//   │    ├─ validateConfig ............ env var usage        │
//   │    ├─ validateFieldNames ........ misspelled fields    │
//   │    ├─ validateEndpointURLs ...... orphan endpoints     │
//   │    ├─ validateDuplicateEndpoints  same route twice     │
//   │    ├─ validateDisplayActions .... edit/delete on table │
//   │    ├─ validateEndpointResponses . missing send back    │
//   │    ├─ validateFetchURLsMatch .... frontend→backend URL │
//   │    ├─ validateArithmetic ........ balance subtraction  │
//   │    ├─ validateCapacity .......... overflow risk        │
//   │    ├─ validateFieldMismatch ..... form↔schema names    │
//   │    ├─ validateOWASP ............ SQLi, XSS, CSRF etc  │
//   │    ├─ validateCallTargets ...... undefined agents etc  │
//   │    ├─ validateMemberAccessTypes  field on primitive    │
//   │    ├─ validateTypedCallArgs .... literal vs annotation │
//   │    └─ validateInferredTypes ... (error) text in arith  │
//   │                                                       │
//   │  Errors block compilation. Warnings are advisory.     │
//   └──────────────────────────────────────────────────────┘
//       │
//       ▼
//   If errors: compilation stops, errors shown to user
//   If clean: AST proceeds to compiler.js
//
// ADDING A NEW VALIDATION PASS:
//   1. Write function validateX(body, warnings) — same pattern as others
//   2. Add call to validate() function (line ~48)
//   3. Update this diagram
//   4. Add test to clear.test.js
//
// DEPENDENCIES: parser.js (NodeType enum)
// DEPENDENTS:   index.js (called in compileProgram pipeline)
//
// =============================================================================

import { NodeType } from './parser.js';

// Built-in names that don't need to be declared
const BUILTINS = new Set([
  'sum', 'total', 'average', 'avg', 'mean', 'minimum', 'min', 'maximum', 'max',
  'round', 'floor', 'ceil', 'absolute', 'abs', 'square_root', 'sqrt',
  'length', 'size', 'count', 'uppercase', 'lowercase', 'trim', 'contains',
  'starts_with', 'ends_with', 'replace', 'split', 'join', 'character',
  'fetch_data', 'env', 'show', 'print', 'log',
  'substring', 'index_of', 'is_letter', 'is_digit', 'char_code',
  'get',
  'true', 'false', 'nothing', 'null', 'none', 'response',
  // Internal compiler functions (generated by collection ops, not user-facing)
  '_first', '_last', '_rest', '_map_prop', '_combine',
  '_sum_field', '_avg_field', '_max_field', '_min_field',
  // Auth context
  '_current_user',
]);

/**
 * Validate a Clear AST: check forward references, types, and config.
 *
 * @param {object} ast - The AST from parse()
 * @returns {{ errors: Array<{line, message}>, warnings: Array<string> }}
 */
export function validate(ast) {
  const errors = [];
  const warnings = [];
  validateForwardReferences(ast.body, errors);
  validateTypes(ast.body, errors);
  validateConfig(ast.body, warnings);
  validateFieldNames(ast.body, warnings);
  validateEndpointURLs(ast.body, errors, warnings);
  validateSecurity(ast.body, errors, warnings);
  validateDuplicateEndpoints(ast.body, warnings);
  validateDisplayActions(ast.body, warnings);
  validateEndpointResponses(ast.body, warnings);
  validateFetchURLsMatchEndpoints(ast.body, warnings);
  validateArithmetic(ast.body, warnings);
  validateCapacity(ast.body, warnings);
  validateFieldMismatch(ast.body, warnings);
  validateOWASP(ast.body, errors, warnings);
  validateAgentTools(ast.body, errors);
  validateCallTargets(ast.body, errors);
  validateMemberAccessTypes(ast.body, warnings);
  validateTypedCallArgs(ast.body, warnings);
  validateInferredTypes(ast.body, errors);
  validateChainDepth(ast.body, warnings);
  validateExprComplexity(ast.body, warnings);
  return { errors, warnings };
}

/**
 * NO FORWARD REFERENCES: Variables must be defined before use.
 * Functions are declarations (hoisted, like Python def).
 * Params are in scope inside function bodies.
 */
function validateForwardReferences(body, errors) {
  // First pass: collect all function names (they're hoisted)
  const functionNames = new Set();
  function collectFunctions(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.FUNCTION_DEF) functionNames.add(node.name);
      if (node.type === NodeType.COMPONENT_DEF) functionNames.add(node.name);
      if (node.type === NodeType.AGENT) functionNames.add('agent_' + node.name.toLowerCase().replace(/\s+/g, '_'));
      if (node.type === NodeType.PIPELINE) functionNames.add('pipeline_' + node.name.toLowerCase().replace(/\s+/g, '_'));
      if (node.type === NodeType.WORKFLOW) functionNames.add('workflow_' + node.name.toLowerCase().replace(/\s+/g, '_'));
      if (node.type === NodeType.SKILL) functionNames.add('skill_' + node.name.toLowerCase().replace(/\s+/g, '_'));
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) {
        collectFunctions(node.body);
      }
    }
  }
  collectFunctions(body);

  // Pre-scan: API call target variables are state (always available)
  function collectApiTargets(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.API_CALL && node.targetVar) functionNames.add(node.targetVar);
      if (node.type === NodeType.API_CALL && !node.targetVar) functionNames.add('response');
      if (node.body) collectApiTargets(node.body);
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) collectApiTargets(node.body);
    }
  }
  collectApiTargets(body);

  // Second pass: check references
  const defined = new Set(functionNames);

  function checkNode(nodes, scopeVars, newScope) {
    // newScope=true creates an isolated scope (functions, endpoints)
    // newScope=false (default) shares the parent's mutable set
    const localDefined = newScope ? new Set(scopeVars || defined) : (scopeVars || defined);

    for (const node of nodes) {
      switch (node.type) {
        case NodeType.ASSIGN:
          // Check the expression BEFORE defining the variable
          checkExpr(node.expression, localDefined, node.line);
          localDefined.add(node.name);
          break;
        case NodeType.PARALLEL_AGENTS:
          // Each assignment's expression is checked, then all names are defined
          for (const assign of node.assignments) {
            checkExpr(assign.expression, localDefined, assign.line);
          }
          for (const assign of node.assignments) {
            localDefined.add(assign.name);
          }
          break;
        case NodeType.FUNCTION_DEF: {
          // Function body gets its own scope with params
          const fnScope = new Set(localDefined);
          for (const p of node.params) fnScope.add(p.name);
          checkNode(node.body, fnScope, true);
          break;
        }
        case NodeType.FOR_EACH:
          localDefined.add(node.variable);
          checkExpr(node.iterable, localDefined, node.line);
          checkNode(node.body, localDefined);
          break;
        case NodeType.REPEAT:
          checkExpr(node.count, localDefined, node.line);
          checkNode(node.body, localDefined);
          break;
        case NodeType.WHILE:
          checkExpr(node.condition, localDefined, node.line);
          checkNode(node.body, localDefined);
          break;
        case NodeType.IF_THEN:
          checkExpr(node.condition, localDefined, node.line);
          if (node.thenBranch) checkNodeSingle(node.thenBranch, localDefined);
          if (node.otherwiseBranch) checkNodeSingle(node.otherwiseBranch, localDefined);
          break;
        case NodeType.SHOW:
          checkExpr(node.expression, localDefined, node.line);
          break;
        case NodeType.RETURN:
          checkExpr(node.expression, localDefined, node.line);
          break;
        case NodeType.DISPLAY:
          checkExpr(node.expression, localDefined, node.line);
          break;
        case NodeType.RESPOND:
          checkExpr(node.expression, localDefined, node.line);
          break;
        case NodeType.PAGE:
        case NodeType.SECTION:
          checkNode(node.body, localDefined);
          break;
        case NodeType.TRY_HANDLE:
          checkNode(node.tryBody, localDefined);
          if (node.handlers) {
            // `error` is always bound in handler bodies
            const handlerScope = new Set(localDefined);
            handlerScope.add('error');
            node.handlers.forEach(h => checkNode(h.body, handlerScope));
          } else {
            if (node.errorVar) localDefined.add(node.errorVar);
            checkNode(node.handleBody, localDefined);
          }
          break;
        case NodeType.ENDPOINT: {
          // Endpoint body gets its own scope
          const epScope = new Set(localDefined);
          epScope.add('incoming');
          if (node.receivingVar) epScope.add(node.receivingVar);
          epScope.add('request');
          epScope.add('req');
          checkNode(node.body, epScope, true);
          break;
        }
        case NodeType.TEST_DEF:
          checkNode(node.body, new Set(localDefined), true);
          break;
        case NodeType.EXPECT:
          checkExpr(node.expression, localDefined, node.line);
          break;
        case NodeType.LIST_PUSH:
          checkExpr(node.value, localDefined, node.line);
          break;
        case NodeType.CRUD:
          if (node.operation === 'lookup') {
            // lookup defines a variable, doesn't reference one
            if (node.variable) localDefined.add(node.variable);
            // where conditions reference column names -- don't validate as variables
          } else if (node.operation === 'save') {
            // save references the source variable
            if (node.variable && !localDefined.has(node.variable) && !BUILTINS.has(node.variable)
                && node.variable !== 'incoming') {
              errors.push({ line: node.line, message: `You used '${node.variable}' but it hasn't been created yet. Define it on an earlier line.` });
            }
            // save with resultVar defines the result
            if (node.resultVar) localDefined.add(node.resultVar);
            if (node.condition) checkExpr(node.condition, localDefined, node.line);
          } else if (node.operation === 'remove') {
            // where conditions reference column names -- don't validate as variables
          }
          break;
        case NodeType.ASK_FOR:
          // Input creates a variable
          localDefined.add(node.variable);
          break;
        case NodeType.USE:
          // npm package imports define the alias as a variable
          if (node.isNpm && node.npmAlias) localDefined.add(node.npmAlias);
          // Namespaced module imports define the namespace variable
          if (node._namespace) localDefined.add(node._namespace);
          // Selective imports define the imported names directly
          if (node._selectiveNodes) {
            for (const mNode of node._selectiveNodes) {
              localDefined.add(mNode.name);
            }
          }
          break;
        // Phase 20: Advanced Features
        case NodeType.STREAM:
          checkNode(node.body, localDefined);
          break;
        case NodeType.BACKGROUND:
          checkNode(node.body, new Set(localDefined), true);
          break;
        case NodeType.SUBSCRIBE: {
          const subScope = new Set(localDefined);
          subScope.add('message');
          checkNode(node.body, subScope, true);
          break;
        }
        case NodeType.BROADCAST:
          break;
        case NodeType.MIGRATION:
        case NodeType.WAIT:
          break;
        // Phase 19: File Uploads & External APIs
        case NodeType.ACCEPT_FILE:
          break;
        case NodeType.EXTERNAL_FETCH:
          if (node.config && node.config.errorFallback)
            checkExpr(node.config.errorFallback, localDefined, node.line);
          break;
        // Phase 18: Billing & Payments
        case NodeType.CHECKOUT:
        case NodeType.USAGE_LIMIT:
          break;
        // Phase 17: Webhooks & OAuth
        case NodeType.WEBHOOK: {
          const whScope = new Set(localDefined);
          whScope.add('incoming');
          whScope.add('request');
          checkNode(node.body, whScope, true);
          break;
        }
        case NodeType.OAUTH_CONFIG:
          break;
        // Phase 16: Input validation
        case NodeType.VALIDATE:
          for (const rule of node.rules) localDefined.add(rule.name);
          break;
        case NodeType.RESPONDS_WITH:
        case NodeType.RATE_LIMIT:
          break;
        // Phases 85-90: Workflows
        case NodeType.WORKFLOW: {
          // Workflow defines state fields in its scope
          const wfScope = new Set(localDefined);
          if (node.stateVar) wfScope.add(node.stateVar);
          for (const f of (node.stateFields || [])) wfScope.add(f.name);
          break;
        }
        case NodeType.POLICY:
          break;
        default:
          break;
      }
    }
  }

  function checkNodeSingle(node, scope) {
    checkNode([node], scope);
  }

  // Keywords that could be typos when appearing as unknown variable references
  const KEYWORDS = [
    'repeat', 'while', 'for', 'each', 'define', 'function', 'return',
    'if', 'otherwise', 'match', 'when', 'show', 'display', 'button',
    'section', 'page', 'heading', 'subheading', 'text', 'divider',
    'create', 'build', 'send', 'requires', 'validate', 'guard',
    'database', 'style', 'increase', 'decrease', 'add', 'remove',
    'sort', 'filter', 'save', 'delete', 'get', 'try', 'test', 'expect',
    'webhook', 'background', 'checkout', 'limit', 'stream', 'subscribe',
    'configure', 'connect', 'query', 'fetch', 'scrape', 'predict', 'train',
  ];

  function suggestKeyword(name, scope) {
    const lower = name.toLowerCase();
    let best = null, bestDist = 3; // max distance 2
    // Check keywords
    for (const kw of KEYWORDS) {
      if (lower === kw) return null;
      const d = editDistance(lower, kw);
      if (d < bestDist) { bestDist = d; best = kw; }
    }
    // Check user-defined variables (catches typos like 'emial' -> 'email')
    if (scope) {
      for (const v of scope) {
        if (lower === v.toLowerCase()) return null;
        const d = editDistance(lower, v.toLowerCase());
        if (d < bestDist) { bestDist = d; best = v; }
      }
    }
    return best;
  }

  // Levenshtein distance (compact, only compute up to max 2)
  function editDistance(a, b) {
    if (Math.abs(a.length - b.length) > 2) return 3;
    const m = a.length, n = b.length;
    const dp = Array.from({ length: m + 1 }, (_, i) => [i]);
    for (let j = 0; j <= n; j++) dp[0][j] = j;
    for (let i = 1; i <= m; i++) {
      for (let j = 1; j <= n; j++) {
        dp[i][j] = Math.min(
          dp[i - 1][j] + 1,
          dp[i][j - 1] + 1,
          dp[i - 1][j - 1] + (a[i - 1] !== b[j - 1] ? 1 : 0)
        );
      }
    }
    return dp[m][n];
  }

  function checkExpr(expr, scope, line) {
    if (!expr) return;
    switch (expr.type) {
      case NodeType.VARIABLE_REF:
        if (!scope.has(expr.name) && !BUILTINS.has(expr.name.toLowerCase())) {
          const suggestion = suggestKeyword(expr.name, scope);
          if (suggestion) {
            errors.push({
              line: line,
              message: `Did you mean '${suggestion}'? '${expr.name}' on line ${line} looks like a typo. Clear keywords are lowercase -- check the spelling.`
            });
          } else {
            errors.push({
              line: line,
              message: `You used '${expr.name}' on line ${line} but it hasn't been created yet. Define it on an earlier line. Example: ${expr.name} = 0 or ${expr.name} is 'value'`
            });
          }
        }
        break;
      case NodeType.BINARY_OP:
        checkExpr(expr.left, scope, line);
        checkExpr(expr.right, scope, line);
        break;
      case NodeType.UNARY_OP:
        checkExpr(expr.operand, scope, line);
        break;
      case NodeType.CALL:
        if (expr.callee) {
          // Method call: helpers's double(5) — validate the callee expression
          checkExpr(expr.callee, scope, line);
        } else if (!scope.has(expr.name) && !BUILTINS.has(expr.name.toLowerCase())) {
          errors.push({
            line: line,
            message: `You used '${expr.name}()' on line ${line} but this function hasn't been defined yet. Add it above line ${line}. Example: ${expr.name}(x) = x * 2`
          });
        }
        for (const arg of expr.args) checkExpr(arg, scope, line);
        break;
      case NodeType.MEMBER_ACCESS:
        checkExpr(expr.object, scope, line);
        break;
      case NodeType.LITERAL_LIST:
        for (const el of expr.elements) checkExpr(el, scope, line);
        break;
      case NodeType.LITERAL_RECORD:
        for (const entry of expr.entries) checkExpr(entry.value, scope, line);
        break;
      default:
        // Literals — no references to check
        break;
    }
  }

  checkNode(body);
}

/**
 * TYPE CHECKING: Catch string + number at compile time.
 * Track which variables are known strings vs known numbers.
 */
function validateTypes(body, errors) {
  // Track variable types: 'string', 'number', 'boolean', 'list', 'unknown'
  const types = new Map();

  function inferType(expr) {
    if (!expr) return 'unknown';
    switch (expr.type) {
      case NodeType.LITERAL_STRING: return 'string';
      case NodeType.LITERAL_NUMBER: return 'number';
      case NodeType.LITERAL_BOOLEAN: return 'boolean';
      case NodeType.LITERAL_LIST: return 'list';
      case NodeType.LITERAL_NOTHING: return 'unknown';
      case NodeType.VARIABLE_REF: return types.get(expr.name) || 'unknown';
      case NodeType.BINARY_OP: {
        const lt = inferType(expr.left);
        const rt = inferType(expr.right);
        // String + number = type error
        if (expr.operator === '+') {
          if ((lt === 'string' && rt === 'number') || (lt === 'number' && rt === 'string')) {
            errors.push({
              line: expr.line || expr.left.line || 0,
              message: `You're adding text to a number on line ${expr.line || expr.left.line || '?'} — convert one to match the other. Use text_of(number) or number_of(text).`
            });
            return 'unknown';
          }
          if (lt === 'string' || rt === 'string') return 'string';
          if (lt === 'number' && rt === 'number') return 'number';
        }
        if (['-', '*', '/', '%', '**'].includes(expr.operator)) return 'number';
        if (['==', '!=', '>', '<', '>=', '<=', '&&', '||'].includes(expr.operator)) return 'boolean';
        return 'unknown';
      }
      case NodeType.CALL: return 'unknown'; // Can't know function return types yet
      case NodeType.MEMBER_ACCESS: return 'unknown';
      default: return 'unknown';
    }
  }

  function walkTypes(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.ASSIGN) {
        const t = inferType(node.expression);
        types.set(node.name, t);
      } else if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) {
        walkTypes(node.body);
      } else if (node.type === NodeType.FUNCTION_DEF) {
        // Don't type-check inside function bodies (params are unknown)
      } else if (node.type === NodeType.ASK_FOR) {
        const inputTypes = { text: 'string', number: 'number', 'long text': 'string', 'yes/no': 'boolean', choice: 'string' };
        types.set(node.variable, inputTypes[node.inputType] || 'unknown');
      }
    }
  }

  walkTypes(body);
}

/**
 * CONFIG VALIDATION: Warn when env() is used but no config reference exists.
 */
function validateConfig(body, warnings) {
  const envCalls = [];

  function findEnvCalls(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.ASSIGN && node.expression) {
        walkExprForEnv(node.expression);
      }
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) {
        findEnvCalls(node.body);
      }
      if (node.type === NodeType.ENDPOINT) {
        findEnvCalls(node.body);
      }
    }
  }

  function walkExprForEnv(expr) {
    if (!expr) return;
    if (expr.type === NodeType.CALL && expr.name && expr.name.toLowerCase() === 'env') {
      if (expr.args.length > 0 && expr.args[0].type === NodeType.LITERAL_STRING) {
        envCalls.push(expr.args[0].value);
      }
    }
    if (expr.type === NodeType.BINARY_OP) {
      walkExprForEnv(expr.left);
      walkExprForEnv(expr.right);
    }
    if (expr.type === NodeType.CALL) {
      for (const arg of expr.args) walkExprForEnv(arg);
    }
  }

  findEnvCalls(body);

  if (envCalls.length > 0) {
    for (const envVar of envCalls) {
      warnings.push(`'${envVar}' is used with env() but there's no clear.config to verify it exists. Add a clear.config file with: ${envVar} is env('${envVar}')`);
    }
  }
}

/**
 * FIELD NAME CROSS-CHECK: Warn when validate rules reference fields
 * that don't exist in the corresponding data shape schema.
 */
function validateFieldNames(body, warnings) {
  // Collect all schema field names from DATA_SHAPE nodes
  const schemaFields = new Map(); // tableName -> Set of field names
  function collectSchemas(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.DATA_SHAPE) {
        const fields = new Set(node.fields.map(f => f.name));
        schemaFields.set(node.name.toLowerCase(), fields);
        // Also store plural form
        const plural = node.name.toLowerCase() + (node.name.toLowerCase().endsWith('s') ? '' : 's');
        schemaFields.set(plural, fields);
      }
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) {
        collectSchemas(node.body);
      }
    }
  }
  collectSchemas(body);

  if (schemaFields.size === 0) return;

  // Check validate rules against schemas
  function checkValidation(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.VALIDATE && node.rules) {
        // Find which schema this endpoint is likely using (look for CRUD nodes in same endpoint)
        const allFields = new Set();
        for (const [, fields] of schemaFields) {
          for (const f of fields) allFields.add(f);
        }
        for (const rule of node.rules) {
          if (!allFields.has(rule.name)) {
            // Find closest match for helpful error message
            const closest = [...allFields].find(f =>
              f.startsWith(rule.name.substring(0, 3)) || rule.name.startsWith(f.substring(0, 3))
            );
            const hint = closest ? ` Did you mean '${closest}'?` : '';
            warnings.push(`Line ${rule.line || node.line || '?'}: validation field '${rule.name}' doesn't match any field in your data tables (${[...allFields].join(', ')}).${hint}`);
          }
        }
      }
      // Check reverse: schema required fields missing from validation
      if (node.type === NodeType.ENDPOINT && node.body) {
        checkValidation(node.body);

        // Find the VALIDATE and CRUD (save) in this endpoint to match schema
        const validate = node.body.find(n => n.type === NodeType.VALIDATE);
        const crud = node.body.find(n => n.type === NodeType.CRUD && n.operation === 'save');
        if (validate && crud && crud.target) {
          const targetLower = crud.target.toLowerCase();
          const targetPlural = targetLower + (targetLower.endsWith('s') ? '' : 's');
          const schema = schemaFields.get(targetLower) || schemaFields.get(targetPlural);
          if (schema) {
            // Find schema fields that are required but not in the validate rules
            // (skip auto fields like created_at, id)
            const validatedFields = new Set(validate.rules.map(r => r.name));
            const autoFields = new Set();
            // Collect auto and default fields from the actual data shape
            function findShape(nodes) {
              for (const n of nodes) {
                if (n.type === NodeType.DATA_SHAPE && (n.name.toLowerCase() === targetLower || n.name.toLowerCase() === targetPlural)) {
                  for (const f of n.fields) {
                    if (f.auto || f.defaultValue !== null && f.defaultValue !== undefined) autoFields.add(f.name);
                  }
                }
                if (n.body) findShape(n.body);
              }
            }
            findShape(body);

            for (const field of schema) {
              if (!validatedFields.has(field) && !autoFields.has(field) && !['id'].includes(field)) {
                // Check if the field is required in the schema
                // We need to check the actual DATA_SHAPE node
                let isRequired = false;
                function checkRequired(nodes) {
                  for (const n of nodes) {
                    if (n.type === NodeType.DATA_SHAPE && (n.name.toLowerCase() === targetLower || n.name.toLowerCase() === targetPlural)) {
                      const f = n.fields.find(f => f.name === field);
                      if (f && f.required) isRequired = true;
                    }
                    if (n.body) checkRequired(n.body);
                  }
                }
                checkRequired(body);
                if (isRequired) {
                  warnings.push(
                    `Line ${validate.line || node.line}: validation for ${node.method} ${node.path} is missing required field '${field}' from the ${crud.target} schema. ` +
                    `The database will reject records without it. Add: ${field} is text, required`
                  );
                }
              }
            }
          }
        }
      }
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) checkValidation(node.body);
    }
  }
  checkValidation(body);
}

/**
 * ENDPOINT URL CROSS-CHECK: Warn when frontend fetches a URL
 * that no backend endpoint serves.
 */
function validateEndpointURLs(body, errors, warnings) {
  // Collect all backend endpoint method+URL pairs
  const endpoints = []; // { method, path, pattern }
  function collectEndpoints(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.ENDPOINT) {
        const pattern = new RegExp('^' + node.path.replace(/:(\w+)/g, '[^/]+') + '$');
        endpoints.push({ method: node.method.toUpperCase(), path: node.path, pattern });
      }
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) {
        collectEndpoints(node.body);
      }
    }
  }
  collectEndpoints(body);

  if (endpoints.length === 0) return;

  // Collect all frontend fetch URLs and check method+URL match
  function checkFetchURLs(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.API_CALL && node.url) {
        const method = (node.method || 'GET').toUpperCase();
        const url = node.url;
        // Check if this method+URL matches any endpoint
        const matches = endpoints.some(ep => ep.method === method && ep.pattern.test(url));
        if (!matches) {
          // Check if URL matches on a different method (helpful suggestion)
          const urlMatches = endpoints.filter(ep => ep.pattern.test(url));
          const methodMatches = endpoints.filter(ep => ep.method === method);
          let hint = '';
          if (urlMatches.length > 0) {
            hint = ` That URL exists for ${urlMatches.map(ep => ep.method).join('/')} but not ${method}.`;
          } else {
            const closest = endpoints.find(ep => {
              const base = ep.path.replace(/:(\w+)/g, '');
              return url.startsWith(base.substring(0, Math.max(1, base.length - 2)));
            });
            if (closest) hint = ` Did you mean '${closest.path}'?`;
          }
          errors.push({ line: node.line || 0, message: `frontend ${method}s '${url}' but no backend endpoint handles ${method} ${url}.${hint}` });
        }
      }
      if (node.type === NodeType.BUTTON && node.body) checkFetchURLs(node.body);
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) checkFetchURLs(node.body);
      if (node.type === NodeType.ON_PAGE_LOAD && node.body) checkFetchURLs(node.body);
      if (node.type === NodeType.IF_THEN) {
        if (node.thenBranch) {
          if (Array.isArray(node.thenBranch)) checkFetchURLs(node.thenBranch);
          else checkFetchURLs([node.thenBranch]);
        }
        if (node.otherwiseBranch) {
          if (Array.isArray(node.otherwiseBranch)) checkFetchURLs(node.otherwiseBranch);
          else checkFetchURLs([node.otherwiseBranch]);
        }
      }
    }
  }
  checkFetchURLs(body);
}

/**
 * SECURITY ANALYSIS: Detect common security anti-patterns.
 *
 * Checks:
 * 1. Destructive endpoints (DELETE, PUT) without auth guards
 * 2. Schema has user_id but endpoints don't filter by user (IDOR risk)
 * 3. Schema has user_id but POST endpoint accepts it from client (impersonation risk)
 */
function validateSecurity(body, errors, warnings) {
  // Collect schemas that have user_id or owner-type fields
  const schemasWithOwner = new Set();
  const allSchemaFields = new Map(); // tableName -> Set of fields
  function collectSchemas(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.DATA_SHAPE) {
        const fields = new Set(node.fields.map(f => f.name));
        const name = node.name.toLowerCase();
        allSchemaFields.set(name, fields);
        allSchemaFields.set(name + (name.endsWith('s') ? '' : 's'), fields);
        if (fields.has('user_id') || fields.has('owner_id')) {
          schemasWithOwner.add(name);
          schemasWithOwner.add(name + (name.endsWith('s') ? '' : 's'));
        }
      }
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) collectSchemas(node.body);
    }
  }
  collectSchemas(body);

  // Check endpoints for security issues
  function checkEndpoints(nodes) {
    for (const node of nodes) {
      if (node.type !== NodeType.ENDPOINT) continue;
      const method = node.method.toUpperCase();
      const hasAuth = node.body.some(n =>
        n.type === NodeType.REQUIRES_AUTH || n.type === NodeType.REQUIRES_ROLE
      );

      // Check 1: Destructive endpoints without auth -- this is an error, not a warning
      if ((method === 'DELETE' || method === 'PUT') && !hasAuth) {
        const fixLine = `  requires auth`;
        errors.push({
          line: node.line,
          patchable: true,
          fix: [fixLine],
          insertAfter: node.line,
          message: `${method} ${node.path} has no auth guard -- anyone can ${method === 'DELETE' ? 'delete' : 'modify'} data without logging in. Fix:\n${fixLine}`
        });
      }

      // Check 2: GET endpoint returns all records from a user-owned table without filtering
      if (method === 'GET' && schemasWithOwner.size > 0) {
        const hasCrud = node.body.some(n => n.type === NodeType.CRUD);
        const hasWhereClause = node.body.some(n =>
          n.type === NodeType.CRUD && n.condition
        );
        // If it queries a table with user_id but no where clause and no auth
        if (hasCrud && !hasWhereClause && !hasAuth) {
          const crudNode = node.body.find(n => n.type === NodeType.CRUD);
          if (crudNode) {
            const tableName = crudNode.target ?
              crudNode.target.toLowerCase() + (crudNode.target.toLowerCase().endsWith('s') ? '' : 's') :
              '';
            if (schemasWithOwner.has(tableName)) {
              const ownerField = allSchemaFields.get(tableName)?.has('user_id') ? 'user_id' : 'owner_id';
              const fixLines = [
                `  this endpoint requires auth`,
                `  all_${tableName} = get all ${crudNode.target || 'Records'}`,
              ];
              errors.push({
                line: node.line,
                patchable: true,
                fix: fixLines,
                insertAfter: node.line,
                message: `GET ${node.path} returns ALL records from a table with ${ownerField}, but doesn't filter by user. ` +
                  `Every user will see everyone else's data. Fix:\n` + fixLines.join('\n')
              });
            }
          }
        }
      }

      // Check 3: POST accepts user_id from client on a user-owned table
      if (method === 'POST' && node.receivingVar) {
        const crudSave = node.body.find(n => n.type === NodeType.CRUD && n.operation === 'save');
        if (crudSave && crudSave.target) {
          const tableName = crudSave.target.toLowerCase() + (crudSave.target.toLowerCase().endsWith('s') ? '' : 's');
          const fields = allSchemaFields.get(tableName);
          if (fields && (fields.has('user_id') || fields.has('owner_id'))) {
            const ownerField = fields.has('user_id') ? 'user_id' : 'owner_id';
            warnings.push(
              `Line ${node.line}: POST ${node.path} inserts into a table with '${ownerField}' but accepts that field from the client. ` +
              `A user could set ${ownerField} to someone else's ID. Consider setting ${ownerField} server-side from current user's id.`
            );
          }
        }
      }
    }
  }
  checkEndpoints(body);

  // Check 4: POST endpoints that handle login/signup without rate limiting
  function checkBruteForce(nodes) {
    for (const node of nodes) {
      if (node.type !== NodeType.ENDPOINT) continue;
      const method = node.method.toUpperCase();
      const path = node.path.toLowerCase();
      const isAuthEndpoint = path.includes('login') || path.includes('signin') ||
        path.includes('signup') || path.includes('register') || path.includes('auth');
      if (method === 'POST' && isAuthEndpoint) {
        const hasRateLimit = node.body.some(n => n.type === NodeType.RATE_LIMIT);
        if (!hasRateLimit) {
          warnings.push(
            `Line ${node.line}: ${method} ${node.path} looks like a login/signup endpoint but has no rate limit. ` +
            `Without rate limiting, attackers can try thousands of passwords per second. Add: rate limit 10 per minute`
          );
        }
      }
    }
  }
  checkBruteForce(body);

  // Check 5: Sensitive field names in GET responses (password, secret, token in schema)
  function checkSensitiveFields(nodes) {
    const sensitiveNames = ['password', 'password_hash', 'secret', 'api_key', 'token', 'private_key'];
    for (const node of nodes) {
      if (node.type !== NodeType.DATA_SHAPE) continue;
      const tableName = node.name;
      const sensitive = node.fields.filter(f => sensitiveNames.includes(f.name.toLowerCase()));
      if (sensitive.length > 0) {
        const fieldNames = sensitive.map(f => f.name).join(', ');
        warnings.push(
          `Line ${node.line}: Table '${tableName}' has sensitive field${sensitive.length > 1 ? 's' : ''}: ${fieldNames}. ` +
          `Make sure GET endpoints don't return ${sensitive.length > 1 ? 'these fields' : 'this field'} to clients. ` +
          `Consider removing ${fieldNames} from the 'showing' list or filtering server-side.`
        );
      }
    }
  }
  checkSensitiveFields(body);

  // Check 6: CORS enabled but no auth on any endpoint (wide-open API)
  const hasCORS = body.some(n => n.type === NodeType.ALLOW_CORS);
  const hasAnyAuth = body.some(n =>
    n.type === NodeType.ENDPOINT && n.body &&
    n.body.some(b => b.type === NodeType.REQUIRES_AUTH || b.type === NodeType.REQUIRES_ROLE)
  );
  const hasEndpoints = body.some(n => n.type === NodeType.ENDPOINT);
  if (hasCORS && hasEndpoints && !hasAnyAuth) {
    warnings.push(
      `CORS is enabled but no endpoint requires auth. Any website can call your API and read the responses. ` +
      `Add 'requires auth' to sensitive endpoints, or remove 'allow cross-origin requests' if this is an internal API.`
    );
  }
}

/**
 * DUPLICATE ENDPOINTS: Warn when two endpoints share the same method + path.
 * The second one silently overwrites the first, which is almost always a mistake.
 */
function validateDuplicateEndpoints(body, warnings) {
  const seen = new Map(); // "GET /api/users" -> line number
  function walk(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.ENDPOINT) {
        const key = `${node.method} ${node.path}`;
        if (seen.has(key)) {
          warnings.push(
            `Line ${node.line}: Duplicate endpoint ${key} -- this was already defined on line ${seen.get(key)}. ` +
            `The second definition will overwrite the first. Remove one or use different paths.`
          );
        } else {
          seen.set(key, node.line);
        }
      }
      if (node.type === NodeType.PAGE || node.type === NodeType.SECTION) walk(node.body || []);
    }
  }
  walk(body);
}

/**
 * DISPLAY ACTION VALIDATION: Warn when a table has "with delete" but no
 * DELETE endpoint, or "with edit" but no PUT/PATCH endpoint.
 */
function validateDisplayActions(body, warnings) {
  const endpoints = new Map();
  function collectEndpoints(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.ENDPOINT && node.path) {
        const match = node.path.match(/\/api\/(\w+)\/:id/);
        if (match) {
          endpoints.set(`${node.method} ${match[1].toLowerCase()}`, node.line);
        }
      }
      if (node.body) collectEndpoints(node.body);
    }
  }
  collectEndpoints(body);

  function checkDisplays(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.DISPLAY && node.actions) {
        const varName = node.expression && node.expression.name ? node.expression.name.toLowerCase() : '';
        for (const action of node.actions) {
          if (action === 'delete' && !endpoints.has(`DELETE ${varName}`)) {
            warnings.push(
              `Line ${node.line}: Table has "with delete" but no DELETE endpoint found for ${varName}. ` +
              `Add: when user calls DELETE /api/${varName}/:id`
            );
          }
          if (action === 'edit' && !endpoints.has(`PUT ${varName}`) && !endpoints.has(`PATCH ${varName}`)) {
            warnings.push(
              `Line ${node.line}: Table has "with edit" but no PUT or PATCH endpoint found for ${varName}. ` +
              `Add: when user calls PUT /api/${varName}/:id`
            );
          }
        }
      }
      if (node.body) checkDisplays(node.body);
    }
  }
  checkDisplays(body);
}

/**
 * ENDPOINT RESPONSES: Warn if an endpoint has no send back statement.
 * An endpoint without a response is almost always a bug — the client
 * gets no data back and the request hangs.
 */
function validateEndpointResponses(body, warnings) {
  function hasResponse(nodes) {
    for (const n of nodes) {
      if (n.type === NodeType.RESPOND) return true;
      if (n.body && hasResponse(n.body)) return true;
    }
    return false;
  }
  function walk(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.ENDPOINT) {
        if (!hasResponse(node.body || [])) {
          warnings.push(
            `Line ${node.line}: ${node.method} ${node.path} has no response. ` +
            `Add: send back data (or send back 'ok')`
          );
        }
      }
      if (node.body) walk(node.body);
    }
  }
  walk(body);
}

/**
 * FETCH URL MATCHING: Warn if a frontend fetch targets a URL that doesn't
 * match any declared endpoint. Catches typos like '/api/user' when the
 * endpoint is '/api/users'.
 */
function validateFetchURLsMatchEndpoints(body, warnings) {
  // Collect all declared endpoint paths
  const endpoints = new Map();
  function collectEndpoints(nodes) {
    for (const n of nodes) {
      if (n.type === NodeType.ENDPOINT) {
        // Normalize: strip :param segments for matching
        const normalized = n.path.replace(/:[\w]+/g, ':id');
        endpoints.set(`${n.method} ${normalized}`, n.line);
        // Also store just the base path for GET matching
        endpoints.set(`GET ${n.path.split('/:')[0]}`, n.line);
      }
      if (n.body) collectEndpoints(n.body);
    }
  }
  collectEndpoints(body);

  // If no endpoints declared, skip (frontend-only app)
  if (endpoints.size === 0) return;

  // Collect all fetch URLs from API_CALL nodes
  function checkFetches(nodes) {
    for (const n of nodes) {
      if (n.type === NodeType.API_CALL && n.url && n.url.startsWith('/api/')) {
        const method = n.method || 'GET';
        const url = n.url.split('?')[0]; // strip query params
        // Check if this URL matches any endpoint
        const normalized = url.replace(/\/[\w-]+$/, '/:id'); // try with :id
        const matchesExact = endpoints.has(`${method} ${url}`);
        const matchesParam = endpoints.has(`${method} ${normalized}`);
        const matchesBase = endpoints.has(`GET ${url}`);
        if (!matchesExact && !matchesParam && !matchesBase) {
          // Find closest endpoint for suggestion
          let closest = null;
          let closestDist = 999;
          for (const [key] of endpoints) {
            const epPath = key.split(' ')[1];
            if (!epPath) continue;
            const dist = Math.abs(epPath.length - url.length) + (epPath.includes(url.split('/').slice(0, -1).join('/')) ? 0 : 5);
            if (dist < closestDist) { closestDist = dist; closest = key; }
          }
          const suggestion = closest ? ` Did you mean ${closest}?` : '';
          warnings.push(
            `Line ${n.line}: ${method} ${url} doesn't match any endpoint.${suggestion}`
          );
        }
      }
      if (n.body) checkFetches(n.body);
    }
  }
  checkFetches(body);
}

// =============================================================================
// SILENT BUG GUARDS — Compile-time warnings for common logic errors
// =============================================================================

const BALANCE_WATCHLIST = ['balance', 'stock', 'inventory', 'quantity', 'credits', 'remaining', 'available'];

/**
 * Warn when subtracting from balance/stock/inventory fields without a guard.
 */
function validateArithmetic(body, warnings) {
  function check(nodes, hasGuard) {
    for (const n of nodes) {
      if (n.type === NodeType.GUARD) hasGuard = true;
      if (n.type === 'assign' && n.name && n.name.includes('.')) {
        const member = n.name.split('.').pop();
        if (BALANCE_WATCHLIST.includes(member) && n.expression &&
            n.expression.type === 'binary_op' && n.expression.operator === '-' && !hasGuard) {
          warnings.push(
            `Line ${n.line}: subtracting from '${member}' with no guard. Consider adding:\n` +
            `  check ${n.name.replace('.', "'s ")} is at least <amount>, otherwise error 'Insufficient ${member}'`
          );
        }
      }
      if (n.body) check(n.body, hasGuard);
    }
  }
  for (const n of body) {
    if (n.type === NodeType.ENDPOINT && n.body) check(n.body, false);
  }
}

const CAPACITY_FIELDS = ['capacity', 'limit', 'stock'];
const COUNTER_FIELDS = ['tickets_sold', 'sold', 'used', 'registered_count', 'enrolled_count'];

/**
 * Warn when inserting into child of capacity table without a guard.
 */
function validateCapacity(body, warnings) {
  const capacityTables = new Map();
  for (const n of body) {
    if (n.type !== NodeType.DATA_SHAPE) continue;
    const fields = n.fields.map(f => f.name);
    const hasCap = fields.some(f => CAPACITY_FIELDS.some(c => f === c || f.startsWith('max_')));
    const hasCounter = fields.some(f => COUNTER_FIELDS.some(c => f === c || f.endsWith('_count') || f.endsWith('_sold')));
    if (hasCap && hasCounter) capacityTables.set(n.name.toLowerCase(), n);
  }
  if (capacityTables.size === 0) return;

  for (const ep of body) {
    if (ep.type !== NodeType.ENDPOINT || !ep.body) continue;
    const hasGuard = ep.body.some(n => n.type === NodeType.GUARD);
    if (hasGuard) continue;
    for (const n of ep.body) {
      if (n.type !== NodeType.CRUD || n.operation !== 'save' || !n.resultVar) continue;
      const targetName = n.target?.toLowerCase();
      if (!targetName) continue;
      const targetShape = body.find(b => b.type === NodeType.DATA_SHAPE &&
        (b.name.toLowerCase() === targetName || b.name.toLowerCase() === targetName + 's' || b.name.toLowerCase() + 's' === targetName));
      if (!targetShape) continue;
      for (const f of targetShape.fields) {
        if (f.fieldType === 'fk' || f.name.endsWith('_id')) {
          const refBase = f.name.replace(/_id$/, '').toLowerCase();
          for (const [capName] of capacityTables) {
            if (capName.startsWith(refBase) || refBase.startsWith(capName.replace(/s$/, ''))) {
              warnings.push(
                `Line ${ep.line}: inserting into '${targetName}' which references '${capName}'. ` +
                `The ${capName} table has capacity/counter fields but this endpoint has no guard.`
              );
            }
          }
        }
      }
    }
  }
}

/**
 * Warn when frontend sends fields that don't match the backend table schema.
 */
function validateFieldMismatch(body, warnings) {
  // Collect table schemas
  const schemas = new Map();
  for (const n of body) {
    if (n.type === NodeType.DATA_SHAPE) {
      const fields = new Set(n.fields.map(f => f.name));
      schemas.set(n.name.toLowerCase(), { fields, name: n.name });
      const plural = n.name.toLowerCase() + (n.name.toLowerCase().endsWith('s') ? '' : 's');
      schemas.set(plural, { fields, name: n.name });
    }
  }
  // Collect endpoints and their target tables
  const endpointTables = new Map();
  for (const ep of body) {
    if (ep.type !== NodeType.ENDPOINT || !ep.body) continue;
    const crud = ep.body.find(n => n.type === NodeType.CRUD && n.operation === 'save');
    if (crud && crud.target) {
      const key = `${ep.method} ${ep.path}`;
      // Try both singular and plural forms
      const target = crud.target.toLowerCase();
      endpointTables.set(key, target);
      endpointTables.set(key + ':plural', target + (target.endsWith('s') ? '' : 's'));
    }
  }
  // Check frontend API calls
  function checkCalls(nodes) {
    for (const n of nodes) {
      if (n.type === NodeType.API_CALL && n.fields && n.fields.length > 0 && n.url) {
        const method = n.method || 'POST';
        const key = `${method} ${n.url}`;
        const tableName = endpointTables.get(key) || endpointTables.get(key + ':plural');
        if (tableName) {
          const schema = schemas.get(tableName) || schemas.get(tableName + 's');
          if (schema) {
            for (const sent of n.fields) {
              // 'nothing' means POST with no body — not a real field name
              if (sent === 'nothing' || sent === 'null' || sent === 'none') continue;
              if (!schema.fields.has(sent)) {
                let suggestion = '';
                for (const sf of schema.fields) {
                  if (sent.includes(sf) || sf.includes(sent)) suggestion = ` Did you mean '${sf}'?`;
                }
                warnings.push(
                  `Line ${n.line}: frontend sends '${sent}' to ${method} ${n.url}, but the ${schema.name} table has no '${sent}' field.${suggestion}`
                );
              }
            }
          }
        }
      }
      if (n.body) checkCalls(n.body);
    }
  }
  checkCalls(body);
}

/**
 * OWASP TOP 10 SECURITY CHECKS
 *
 * Catches security vulnerabilities at compile time based on the OWASP Top 10:2025.
 * Each check maps to a specific OWASP category.
 */
function validateOWASP(body, errors, warnings) {
  // ── A03: SQL Injection via raw queries with string interpolation ──
  // Raw queries that use string concatenation instead of parameterized queries
  function checkInjection(nodes) {
    for (const n of nodes) {
      if (n.type === NodeType.RAW_QUERY && n.sql) {
        // Check if SQL contains interpolation markers like {variable} or ' + variable
        if (n.sql.includes('{') || n.sql.includes("' +") || n.sql.includes("\" +")) {
          warnings.push(
            `Line ${n.line}: SQL query uses string interpolation which is vulnerable to SQL injection. ` +
            `Use parameterized queries instead: query 'SELECT * FROM users WHERE id = $1' with user_id`
          );
        }
      }
      // Check for raw SQL in assignments too
      if (n.type === NodeType.ASSIGN && n.expression?.type === NodeType.RAW_QUERY) {
        if (n.expression.sql && (n.expression.sql.includes('{') || n.expression.sql.includes("' +"))) {
          warnings.push(
            `Line ${n.line}: SQL query uses string interpolation — this is a SQL injection risk. ` +
            `Use parameterized queries: query 'SELECT * WHERE id = $1' with id_var`
          );
        }
      }
      if (n.body) checkInjection(n.body);
    }
  }
  checkInjection(body);

  // ── A04: Insecure Direct Object References (path traversal in file ops) ──
  // File operations that use user-controlled paths without validation
  function checkPathTraversal(nodes) {
    for (const n of nodes) {
      if (n.type === NodeType.FILE_OP) {
        // If file path is a variable reference (not a literal), warn about path traversal
        if (n.path && n.path.type === NodeType.VARIABLE_REF) {
          warnings.push(
            `Line ${n.line}: File operation uses a variable path ('${n.path.name}'). ` +
            `If this comes from user input, it could allow path traversal attacks (../../etc/passwd). ` +
            `Validate the path or use a fixed directory prefix.`
          );
        }
      }
      if (n.body) checkPathTraversal(n.body);
    }
  }
  checkPathTraversal(body);

  // ── A05: Security Misconfiguration — PATCH endpoints without auth ──
  function checkPatchWithoutAuth(nodes) {
    for (const n of nodes) {
      if (n.type === NodeType.ENDPOINT && n.method === 'PATCH') {
        const hasAuth = n.body?.some(b =>
          b.type === NodeType.REQUIRES_AUTH || b.type === NodeType.REQUIRES_ROLE
        );
        if (!hasAuth) {
          errors.push({
            line: n.line,
            patchable: true,
            fix: ['  requires auth'],
            insertAfter: n.line,
            message: `PATCH ${n.path} has no auth guard — anyone can modify data. Add: requires auth`
          });
        }
      }
      if (n.body) checkPatchWithoutAuth(n.body);
    }
  }
  checkPatchWithoutAuth(body);

  // ── A07: Cross-Site Request Forgery — POST endpoints that modify data without auth ──
  // POST endpoints that save/update/delete without auth are CSRF-vulnerable
  function checkCSRF(nodes) {
    for (const n of nodes) {
      if (n.type !== NodeType.ENDPOINT) continue;
      if (n.method !== 'POST') continue;
      const hasAuth = n.body?.some(b =>
        b.type === NodeType.REQUIRES_AUTH || b.type === NodeType.REQUIRES_ROLE
      );
      const hasCrud = n.body?.some(b => n.type === NodeType.CRUD);
      const modifiesData = n.body?.some(b =>
        b.type === NodeType.CRUD && (b.operation === 'save' || b.operation === 'remove')
      );
      if (modifiesData && !hasAuth) {
        const path = n.path?.toLowerCase() || '';
        // Skip signup/register — those are intentionally unauthenticated
        if (path.includes('signup') || path.includes('register') || path.includes('seed')) continue;
        warnings.push(
          `Line ${n.line}: POST ${n.path} modifies data without auth — CSRF vulnerable. ` +
          `A malicious site could trick a user's browser into submitting data. ` +
          `Fix: add 'requires auth' inside the endpoint.`
        );
      }
    }
  }
  checkCSRF(body);

  // ── A09: Security Logging — no logging on apps with auth ──
  const hasAuth = body.some(n =>
    n.type === NodeType.ENDPOINT && n.body &&
    n.body.some(b => b.type === NodeType.REQUIRES_AUTH || b.type === NodeType.REQUIRES_ROLE)
  );
  const hasLogging = body.some(n => n.type === NodeType.LOG_REQUESTS);
  if (hasAuth && !hasLogging) {
    warnings.push(
      `Your app requires auth but doesn't log requests. Without logging, you can't detect ` +
      `unauthorized access attempts or debug auth issues. Add: log every request`
    );
  }
}

/**
 * Validate agent tool references — verify each tool name matches a defined function.
 * Also validate guardrails: check that tool functions don't violate must-not restrictions.
 */
function validateAgentTools(body, errors) {
  // Collect all function definitions
  const functionDefs = {};
  for (const node of body) {
    if (node.type === NodeType.FUNCTION_DEF) functionDefs[node.name] = node;
  }

  // Helper: scan a function body for CRUD operations
  function findCrudOps(fnBody) {
    const ops = [];
    function scan(nodes) {
      for (const n of nodes) {
        if (n.type === NodeType.CRUD) {
          ops.push({ operation: n.operation, target: n.target });
        }
        if (n.body) scan(n.body);
        if (n.thenBranch) scan(n.thenBranch);
        if (n.otherwiseBranch) scan(n.otherwiseBranch);
        // Check expression-level CRUD (assignments with CRUD expressions)
        if (n.type === NodeType.ASSIGN && n.expression && n.expression.type === NodeType.CRUD) {
          ops.push({ operation: n.expression.operation, target: n.expression.target });
        }
      }
    }
    scan(fnBody);
    return ops;
  }

  // Check each agent
  for (const node of body) {
    if (node.type !== NodeType.AGENT) continue;

    // Validate tool references exist
    if (node.tools && node.tools.length > 0) {
      for (const tool of node.tools) {
        if (tool.type === 'ref' && !functionDefs[tool.name]) {
          errors.push({
            line: node.line,
            message: `agent '${node.name}' uses tool '${tool.name}' but no function '${tool.name}' is defined. Add: define function ${tool.name}(...):`
          });
        }
      }
    }

    // Validate guardrails: check tool functions against must-not restrictions
    if (node.restrictions && node.restrictions.length > 0 && node.tools && node.tools.length > 0) {
      const compileRestrictions = node.restrictions.filter(r => r.category === 'delete' || r.category === 'modify' || r.category === 'access');
      for (const tool of node.tools) {
        if (tool.type !== 'ref') continue;
        const fnDef = functionDefs[tool.name];
        if (!fnDef) continue;
        const crudOps = findCrudOps(fnDef.body);
        for (const restriction of compileRestrictions) {
          for (const op of crudOps) {
            if (restriction.category === 'delete' && (op.operation === 'remove' || op.operation === 'delete')) {
              errors.push({
                line: node.line,
                message: `agent '${node.name}' uses '${tool.name}' which deletes from ${op.target}, but the agent has 'must not: ${restriction.text}'. Remove the restriction or change the tool.`
              });
            }
            if (restriction.category === 'access') {
              // Extract table name from restriction: "access Users table" or "access Users"
              const tableMatch = restriction.text.match(/access\s+(\w+)/);
              const restrictedTable = tableMatch ? tableMatch[1] : '';
              // Handle singular/plural: "User" matches "Users" and vice versa
              const singularTarget = op.target.replace(/s$/, '');
              const singularRestricted = restrictedTable.replace(/s$/, '');
              if (restrictedTable && (op.target === restrictedTable || singularTarget === singularRestricted)) {
                errors.push({
                  line: node.line,
                  message: `agent '${node.name}' uses '${tool.name}' which accesses ${op.target}, but the agent has 'must not: ${restriction.text}'. Remove the restriction or change the tool.`
                });
              }
            }
            if (restriction.category === 'modify' && (op.operation === 'save' || op.operation === 'update' || op.operation === 'insert')) {
              const tableMatch = restriction.text.match(/modify\s+(\w+)/);
              const restrictedTable = tableMatch ? tableMatch[1] : '';
              if (restrictedTable && op.target === restrictedTable) {
                errors.push({
                  line: node.line,
                  message: `agent '${node.name}' uses '${tool.name}' which modifies ${op.target}, but the agent has 'must not: ${restriction.text}'. Remove the restriction or change the tool.`
                });
              }
            }
          }
        }
      }
    }
  }
}

// =============================================================================
// VALIDATE CALL TARGETS: agent, pipeline, workflow names must exist
// =============================================================================
function validateCallTargets(body, errors) {
  const agents = new Set();
  const pipelines = new Set();
  const workflows = new Set();
  for (const node of body) {
    if (node.type === NodeType.AGENT) agents.add(node.name.toLowerCase().replace(/\s+/g, '_'));
    if (node.type === NodeType.PIPELINE) pipelines.add(node.name.toLowerCase().replace(/\s+/g, '_'));
    if (node.type === NodeType.WORKFLOW) workflows.add(node.name.toLowerCase().replace(/\s+/g, '_'));
  }

  function checkExpr(expr, line) {
    if (!expr) return;
    if (expr.type === NodeType.RUN_AGENT && expr.agentName) {
      const normalized = expr.agentName.toLowerCase().replace(/\s+/g, '_');
      if (!agents.has(normalized)) {
        const all = [...agents];
        const hint = all.length > 0 ? ` Defined agents: ${all.join(', ')}` : '';
        errors.push({ line: expr.line || line, message: `agent '${expr.agentName}' is not defined.${hint}` });
      }
    }
    if (expr.type === NodeType.RUN_PIPELINE && expr.pipelineName) {
      const normalized = expr.pipelineName.toLowerCase().replace(/\s+/g, '_');
      if (!pipelines.has(normalized)) {
        errors.push({ line: expr.line || line, message: `pipeline '${expr.pipelineName}' is not defined. Add: pipeline '${expr.pipelineName}' with var:` });
      }
    }
    if (expr.type === NodeType.RUN_WORKFLOW && expr.workflowName) {
      const normalized = expr.workflowName.toLowerCase().replace(/\s+/g, '_');
      if (!workflows.has(normalized)) {
        errors.push({ line: expr.line || line, message: `workflow '${expr.workflowName}' is not defined. Add: workflow '${expr.workflowName}' with state:` });
      }
    }
    if (expr.left) checkExpr(expr.left, line);
    if (expr.right) checkExpr(expr.right, line);
    if (expr.argument) checkExpr(expr.argument, line);
  }

  function checkNodes(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.ASSIGN && node.expression) checkExpr(node.expression, node.line);
      if (node.body) checkNodes(node.body);
      if (node.thenBranch && Array.isArray(node.thenBranch)) checkNodes(node.thenBranch);
      if (node.otherwiseBranch && Array.isArray(node.otherwiseBranch)) checkNodes(node.otherwiseBranch);
      if (node.tryBody) checkNodes(node.tryBody);
      if (node.handleBody) checkNodes(node.handleBody);
    }
  }
  checkNodes(body);
}

// =============================================================================
// VALIDATE MEMBER ACCESS TYPES: warn about field access on known primitives
// =============================================================================
function validateMemberAccessTypes(body, warnings) {
  const varTypes = new Map();

  function inferType(expr) {
    if (!expr) return 'unknown';
    if (expr.type === 'literal_number' || expr.type === 'number') return 'number';
    if (expr.type === 'literal_string' || expr.type === 'string') return 'string';
    if (expr.type === 'literal_boolean' || expr.type === 'boolean') return 'boolean';
    if (expr.type === 'literal_record') return 'object';
    if (expr.type === 'literal_list') return 'list';
    if (expr.type === NodeType.ASK_AI && expr.schema && expr.schema.length > 0) return 'object';
    if (expr.type === NodeType.RUN_AGENT || expr.type === NodeType.RUN_WORKFLOW) return 'object';
    if (expr.type === 'binary_op') {
      const op = expr.operator;
      if (['+', '-', '*', '/', '%'].includes(op)) return 'number';
    }
    if (expr.type === 'variable_ref' && varTypes.has(expr.name)) return varTypes.get(expr.name);
    return 'unknown';
  }

  function checkNodes(nodes) {
    for (const node of nodes) {
      if (node.type === NodeType.ASSIGN && node.expression) {
        const t = inferType(node.expression);
        if (t !== 'unknown') varTypes.set(node.name, t);
      }
      if (node.type === NodeType.ASSIGN && node.expression?.type === 'member_access') {
        const obj = node.expression.object;
        const objName = obj?.name || obj?.value;
        if (objName && varTypes.has(objName)) {
          const t = varTypes.get(objName);
          if (t === 'number' || t === 'boolean') {
            warnings.push({
              line: node.line,
              message: `'${objName}' is a ${t}, not an object — accessing '${node.expression.property}' on it will fail at runtime.`
            });
          }
        }
      }
      if (node.body) checkNodes(node.body);
      if (node.thenBranch && Array.isArray(node.thenBranch)) checkNodes(node.thenBranch);
      if (node.otherwiseBranch && Array.isArray(node.otherwiseBranch)) checkNodes(node.otherwiseBranch);
    }
  }
  checkNodes(body);
}


// =============================================================================
// VALIDATE TYPE ANNOTATIONS: Warn on literal type mismatches at call sites.
// Only checks literal args (string, number, boolean) against typed params.
// =============================================================================
function validateTypedCallArgs(body, warnings) {
  // Build map of typed function signatures
  const typedFns = {};
  function collectDefs(nodes) {
    if (!Array.isArray(nodes)) return;
    for (const node of nodes) {
      if (node.type === NodeType.FUNCTION_DEF && node.params?.some(p => p.type)) {
        typedFns[node.name] = node.params;
      }
      if (Array.isArray(node.body)) collectDefs(node.body);
      if (Array.isArray(node.thenBranch)) collectDefs(node.thenBranch);
      if (Array.isArray(node.otherwiseBranch)) collectDefs(node.otherwiseBranch);
      if (node.handlers) node.handlers.forEach(h => collectDefs(h.body));
    }
  }
  collectDefs(body);

  const literalType = (expr) => {
    if (!expr) return null;
    if (expr.type === 'literal_string') return 'text';
    if (expr.type === 'literal_number') return 'number';
    if (expr.type === 'literal_boolean') return 'boolean';
    return null;
  };

  const compatible = (expected, actual) => {
    if (!expected || !actual) return true;
    if (expected === actual) return true;
    return false;
  };

  function checkExprs(nodes) {
    if (!Array.isArray(nodes)) return;
    for (const node of nodes) {
      checkNodeExprs(node);
      if (Array.isArray(node.body)) checkExprs(node.body);
      if (Array.isArray(node.thenBranch)) checkExprs(node.thenBranch);
      if (Array.isArray(node.otherwiseBranch)) checkExprs(node.otherwiseBranch);
      if (node.handlers) node.handlers.forEach(h => checkExprs(h.body));
    }
  }

  function checkCall(expr, line) {
    if (!expr || expr.type !== 'call' || !expr.name) return;
    const params = typedFns[expr.name];
    if (!params) return;
    for (let i = 0; i < Math.min(params.length, (expr.args || []).length); i++) {
      const expectedType = params[i].type;
      if (!expectedType) continue;
      const argType = literalType(expr.args[i]);
      if (argType && !compatible(expectedType, argType)) {
        warnings.push({
          line,
          message: `Type mismatch: '${params[i].name}' expects ${expectedType} but got ${argType} in call to '${expr.name}()'`
        });
      }
    }
    for (const arg of expr.args || []) checkExprForCalls(arg, line);
  }

  function checkExprForCalls(expr, line) {
    if (!expr) return;
    if (expr.type === 'call') checkCall(expr, line);
    if (expr.left) checkExprForCalls(expr.left, line);
    if (expr.right) checkExprForCalls(expr.right, line);
    if (expr.object) checkExprForCalls(expr.object, line);
    if (expr.args) expr.args.forEach(a => checkExprForCalls(a, line));
  }

  function checkNodeExprs(node) {
    if (!node) return;
    const line = node.line;
    if (node.expression) checkExprForCalls(node.expression, line);
    if (node.condition) checkExprForCalls(node.condition, line);
    if (node.value) checkExprForCalls(node.value, line);
  }

  checkExprs(body);
}

/**
 * INFERRED TYPE SYSTEM (Phase P1):
 * Walk assignments to build a type environment, then error on arithmetic on text.
 * Only fires when type is known from a literal assignment — never guesses.
 *
 * Catches:
 *   price = 'ten dollars'
 *   total = price * 1.08     ← error: price is text, used in arithmetic
 *
 * Uses typed param annotations (Phase 97) as authoritative type source.
 */
function validateInferredTypes(body, errors) {
  // Infer the type of a literal or known expression
  function inferLiteralType(expr) {
    if (!expr) return 'unknown';
    if (expr.type === NodeType.LITERAL_STRING) return 'text';
    if (expr.type === NodeType.LITERAL_NUMBER) return 'number';
    if (expr.type === NodeType.LITERAL_BOOLEAN) return 'boolean';
    if (expr.type === NodeType.LITERAL_LIST) return 'list';
    if (expr.type === NodeType.STRING_INTERPOLATION) return 'text';
    // Arithmetic always produces a number (if both sides are numbers)
    if (expr.type === NodeType.BINARY_OP) {
      if (['-', '*', '/', '%', '**'].includes(expr.operator)) return 'number';
      if (['+'].includes(expr.operator)) {
        const l = inferLiteralType(expr.left);
        const r = inferLiteralType(expr.right);
        if (l === 'number' && r === 'number') return 'number';
        if (l === 'text' || r === 'text') return 'text';
      }
    }
    return 'unknown';
  }

  // Build type environment by scanning all assignments in a node list
  function buildTypeEnv(nodes, env) {
    if (!Array.isArray(nodes)) return;
    for (const node of nodes) {
      if (node.type === NodeType.ASSIGN) {
        const t = inferLiteralType(node.expression);
        if (t !== 'unknown') env.set(node.name, { type: t, line: node.line });
      }
      // Typed function params are authoritative
      if (node.type === NodeType.FUNCTION_DEF && Array.isArray(node.params)) {
        for (const p of node.params) {
          if (p.type) {
            const mapped = p.type === 'text' ? 'text' : p.type === 'number' ? 'number' : p.type === 'boolean' ? 'boolean' : 'unknown';
            if (mapped !== 'unknown') env.set(p.name, { type: mapped, line: node.line, isParam: true });
          }
        }
        buildTypeEnv(node.body, env);
      }
      if (node.type === NodeType.ENDPOINT) buildTypeEnv(node.body, env);
      if (node.type === NodeType.FOR_EACH) buildTypeEnv(node.body, env);
      if (Array.isArray(node.thenBranch)) buildTypeEnv(node.thenBranch, env);
      if (Array.isArray(node.otherwiseBranch)) buildTypeEnv(node.otherwiseBranch, env);
    }
  }

  // Resolve the type of an expression given the current env
  function resolveType(expr, env) {
    if (!expr) return 'unknown';
    if (expr.type === NodeType.LITERAL_STRING) return 'text';
    if (expr.type === NodeType.LITERAL_NUMBER) return 'number';
    if (expr.type === NodeType.LITERAL_BOOLEAN) return 'boolean';
    if (expr.type === NodeType.STRING_INTERPOLATION) return 'text';
    if (expr.type === NodeType.VARIABLE_REF) return env.get(expr.name)?.type || 'unknown';
    if (expr.type === NodeType.BINARY_OP) {
      if (['-', '*', '/', '%', '**'].includes(expr.operator)) return 'number';
    }
    return 'unknown';
  }

  // Check expressions for type mismatches
  function checkExpr(expr, env, line) {
    if (!expr) return;
    if (expr.type === NodeType.BINARY_OP) {
      const op = expr.operator;
      // Arithmetic operators expect numbers
      if (['-', '*', '/', '%', '**'].includes(op)) {
        const lt = resolveType(expr.left, env);
        const rt = resolveType(expr.right, env);
        if (lt === 'text') {
          const varName = expr.left?.name || expr.left?.value || '?';
          errors.push({ line: expr.line || line, message: `'${varName}' is text, not a number — can't use it in ${op} arithmetic. Assign a number instead.` });
        } else if (rt === 'text') {
          const varName = expr.right?.name || expr.right?.value || '?';
          errors.push({ line: expr.line || line, message: `'${varName}' is text, not a number — can't use it in ${op} arithmetic. Assign a number instead.` });
        }
      }
      checkExpr(expr.left, env, line);
      checkExpr(expr.right, env, line);
    }
    if (expr.args) expr.args.forEach(a => checkExpr(a, env, line));
    if (expr.object) checkExpr(expr.object, env, line);
  }

  function walkNodes(nodes, env) {
    if (!Array.isArray(nodes)) return;
    for (const node of nodes) {
      const line = node.line;
      // Check expressions in assignments, conditions, and values
      if (node.type === NodeType.ASSIGN) {
        checkExpr(node.expression, env, line);
        // Update env with inferred type after checking
        const t = inferLiteralType(node.expression);
        if (t !== 'unknown') env.set(node.name, { type: t, line });
      } else if (node.expression) {
        checkExpr(node.expression, env, line);
      }
      if (node.condition) checkExpr(node.condition, env, line);
      if (node.value) checkExpr(node.value, env, line);
      // Recurse
      if (Array.isArray(node.body)) walkNodes(node.body, new Map(env));
      if (Array.isArray(node.thenBranch)) walkNodes(node.thenBranch, new Map(env));
      if (Array.isArray(node.otherwiseBranch)) walkNodes(node.otherwiseBranch, new Map(env));
      if (node.handlers) node.handlers.forEach(h => walkNodes(h.body, new Map(env)));
    }
  }

  // Build global type env, then walk checking for mismatches
  const globalEnv = new Map();
  buildTypeEnv(body, globalEnv);
  walkNodes(body, globalEnv);
}

// CHAIN DEPTH: warn when possessive chains go deeper than 4 levels.
// "user's profile's avatar's url's host" is 4 deep and already pushing it.
// Deep chains are a symptom of missing intermediate variables — exactly what
// Clear's one-operation-per-line rule is designed to prevent.
function validateChainDepth(body, warnings) {
  const MAX_DEPTH = 4;

  function chainDepth(expr) {
    if (!expr || expr.type !== NodeType.MEMBER_ACCESS) return 0;
    return 1 + chainDepth(expr.object);
  }

  function checkExpr(expr, line) {
    if (!expr) return;
    const depth = chainDepth(expr);
    if (depth >= MAX_DEPTH) {
      warnings.push({
        line: expr.line || line,
        message: `Possessive chain is ${depth} levels deep — break it into named steps. Example:\n  profile = user's profile\n  avatar = profile's avatar\n  url = avatar's url`,
      });
    }
    // Still recurse to catch chains nested inside other expressions
    if (expr.object) checkExpr(expr.object, line);
    if (expr.left) checkExpr(expr.left, line);
    if (expr.right) checkExpr(expr.right, line);
    if (expr.args) expr.args.forEach(a => checkExpr(a, line));
    if (expr.condition) checkExpr(expr.condition, line);
    if (expr.expression) checkExpr(expr.expression, line);
  }

  function walk(nodes) {
    if (!Array.isArray(nodes)) return;
    for (const node of nodes) {
      const line = node.line;
      if (node.expression) checkExpr(node.expression, line);
      if (node.condition) checkExpr(node.condition, line);
      if (node.value) checkExpr(node.value, line);
      if (Array.isArray(node.body)) walk(node.body);
      if (Array.isArray(node.thenBranch)) walk(node.thenBranch);
      if (Array.isArray(node.otherwiseBranch)) walk(node.otherwiseBranch);
      if (node.handlers) node.handlers.forEach(h => walk(h.body));
    }
  }

  walk(body);
}

// EXPRESSION COMPLEXITY: warn when a single expression uses 3+ binary operators.
// That's a sign the line is doing too much — Clear's design says name intermediates.
// Example: a = b plus c times d minus e   → warn, suggest breaking up
function validateExprComplexity(body, warnings) {
  const MAX_OPS = 2;

  function countOps(expr) {
    if (!expr) return 0;
    if (expr.type !== NodeType.BINARY_OP) return 0;
    return 1 + countOps(expr.left) + countOps(expr.right);
  }

  function checkExpr(expr, line) {
    if (!expr) return;
    if (expr.type === NodeType.BINARY_OP) {
      const ops = countOps(expr);
      if (ops > MAX_OPS) {
        warnings.push({
          line: expr.line || line,
          message: `This expression has ${ops} operations on one line. Break it into named steps:\n  step1 = ...\n  step2 = step1 ...`,
        });
        return; // Don't recurse — one warning per top-level expression
      }
    }
    if (expr.left) checkExpr(expr.left, line);
    if (expr.right) checkExpr(expr.right, line);
    if (expr.args) expr.args.forEach(a => checkExpr(a, line));
    if (expr.object) checkExpr(expr.object, line);
    if (expr.expression) checkExpr(expr.expression, line);
  }

  function walk(nodes) {
    if (!Array.isArray(nodes)) return;
    for (const node of nodes) {
      const line = node.line;
      if (node.expression) checkExpr(node.expression, line);
      if (node.condition) checkExpr(node.condition, line);
      if (Array.isArray(node.body)) walk(node.body);
      if (Array.isArray(node.thenBranch)) walk(node.thenBranch);
      if (Array.isArray(node.otherwiseBranch)) walk(node.otherwiseBranch);
      if (node.handlers) node.handlers.forEach(h => walk(h.body));
    }
  }

  walk(body);
}
