// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"177":2,"179":4,"186":8,"187":8,"192":9,"194":10,"196":11,"199":13,"201":14,"202":14,"203":15,"213":17,"214":17,"218":18,"220":19,"224":21,"233":23,"234":23,"238":24,"240":25,"244":27,"246":28} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Store: key!, value (line 4)
//
// ENDPOINTS:
//   POST /api/store (line 8)
//   GET /api/store/:key (line 17)
//   DELETE /api/store/:key (line 23)
//
// DATAFLOW: Client ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// CF-1: runtime instrumentation — fire-and-forget beacons to the Compiler Flywheel.
const _CLEAR_FLYWHEEL_URL = process.env.CLEAR_FLYWHEEL_URL;
const _CLEAR_COMPILE_ROW_ID = process.env.CLEAR_COMPILE_ROW_ID;
function _clearBeacon(event) {
  if (!_CLEAR_FLYWHEEL_URL || !_CLEAR_COMPILE_ROW_ID) return;
  try {
    fetch(_CLEAR_FLYWHEEL_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(Object.assign({ compile_row_id: _CLEAR_COMPILE_ROW_ID, ts: Date.now() }, event)),
      signal: AbortSignal.timeout(500),
    }).catch(() => {});
  } catch {}
}
app.use((req, res, next) => {
  const _t0 = Date.now();
  res.on('finish', () => {
    _clearBeacon({ event_type: 'endpoint_latency', method: req.method, path: req.route ? req.route.path : req.path, status: res.statusCode, duration_ms: Date.now() - _t0 });
  });
  next();
});
app.use((err, req, res, next) => {
  _clearBeacon({ event_type: 'endpoint_error', method: req.method, path: req.path, error_sig: (err && err.message ? String(err.message).substring(0, 200) : 'unknown') });
  next(err);
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    stores: { line: 4, file: "main.clear", fields: { key: { unique: true, type: "text" }, value: { type: "text" } } },
  },
  endpoints: {
    "POST /api/store": { line: 8, file: "main.clear", auth: false },
    "GET /api/store/:key": { line: 17, file: "main.clear", auth: false },
    "DELETE /api/store/:key": { line: 23, file: "main.clear", auth: false },
  }
} : null;

// clear:2
// Database: local memory (JSON file backup)
// clear:4
// Data shape: Store
const StoreSchema = {
  key: { type: "text", unique: true },
  value: { type: "text" }
};
db.createTable('stores', StoreSchema);
// clear:8
// clear:8 — POST /api/store
app.post('/api/store', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const entry = req.body;
    // clear:9
    const existing = (await db.findAll('stores', { key: entry?.key }, { limit: 50 })).map(_revive);
    // clear:10
    if (existing) {
      const saved = await _clearTry(() => db.insert('stores', _pick(entry, StoreSchema)), { op: 'insert', table: 'stores', line: 11, file: 'main.clear', source: "" }); // clear:11
      return res.json(saved);
    }
    // clear:13
    existing.value = entry?.value;
    // clear:14
    await _clearTry(() => db.update('stores', _pick(existing, StoreSchema)), { op: 'update', table: 'stores', line: 14, file: 'main.clear', source: "" }); // clear:14
    // clear:15
    return res.json(existing);
  } catch (err) {
    console.error('[POST /api/store] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/store', line: 8, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:17
// clear:17 — GET /api/store/:key
app.get('/api/store/:key', async (req, res) => {
  try {
    const incoming = req.params;
    // clear:18
    const entry = (await db.findAll('stores', { key: incoming?.key }, { limit: 50 })).map(_revive);
    // clear:19
    if (entry) {
      return res.status(404).json({ message: "not found" });
    }
    // clear:21
    return res.json(entry);
  } catch (err) {
    console.error('[GET /api/store/:key] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/store/:key', line: 17, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:23
// clear:23 — DELETE /api/store/:key
app.delete('/api/store/:key', async (req, res) => {
  try {
    const incoming = req.params;
    // clear:24
    const entry = (await db.findAll('stores', { key: incoming?.key }, { limit: 50 })).map(_revive);
    // clear:25
    if (entry) {
      return res.status(404).json({ message: "not found" });
    }
    // clear:27
    Store = Store.filter(_item => _item !== entry);
    // clear:28
    return res.json({ message: "ok" });
  } catch (err) {
    console.error('[DELETE /api/store/:key] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'DELETE /api/store/:key', line: 23, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});
process.on('SIGINT', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});