// Generated by Clear v1.0
const express = require('express');
const db = require('./clear-runtime/db');
const auth = require('./clear-runtime/auth');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
app.use(auth.middleware());

// Built-in utilities
function _validate(body, rules) {
  for (const r of rules) {
    const v = body[r.field];
    if (r.required && (v == null || v === '')) return r.field + ' is required';
    if (v == null) continue;
    if (r.type === 'number' && typeof v !== 'number') return r.field + ' must be a number';
    if (r.type === 'boolean' && typeof v !== 'boolean') return r.field + ' must be true or false';
    if (r.min != null && r.type === 'text' && String(v).length < r.min) return r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters');
    if (r.max != null && r.type === 'text' && String(v).length > r.max) return r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters');
    if (r.min != null && r.type !== 'text' && v < r.min) return r.field + ' must be at least ' + r.min;
    if (r.max != null && r.type !== 'text' && v > r.max) return r.field + ' must be at most ' + r.max;
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) return r.field + ' must be a valid email';
    if (r.oneOf && !r.oneOf.includes(v)) return r.field + ' must be one of: ' + r.oneOf.join(', ');
  }
  return null;
}

// SaaS Billing Service -- Stress Test App #5
// Tests: subscriptions, usage metering, tiered limits, upgrade/downgrade
// --- Data ---
// Data shape: User
const UserSchema = {
  email: { type: "text", required: true, unique: true },
  name: { type: "text", required: true },
  plan: { type: "text", default: "free" },
  created_at: { type: "timestamp", auto: true }
};
db.createTable('users', UserSchema);
// Data shape: Usage
const UsageSchema = {
  user_id: { type: "text", required: true },
  feature: { type: "text", required: true },
  count: { type: "number", default: 0 },
  period: { type: "text", required: true },
  created_at: { type: "timestamp", auto: true }
};
db.createTable('usages', UsageSchema);
// --- Billing Config ---
// Checkout config: Pro Plan
const CHECKOUT_PRO_PLAN = {
  price: 'price_pro_monthly',
  mode: 'subscription',
  success_url: '/billing/success',
  cancel_url: '/billing',
};
// Checkout config: Enterprise Plan
const CHECKOUT_ENTERPRISE_PLAN = {
  price: 'price_enterprise_monthly',
  mode: 'subscription',
  success_url: '/billing/success',
  cancel_url: '/billing',
};
// --- Usage Limits ---
// Usage limits: api_calls
const LIMITS_API_CALLS = {
  'free': { max: 100, period: 'month' },
  'pro': { max: 10000, period: 'month' },
  'enterprise': { max: Infinity, period: 'month' },
};
// Usage limits: file_uploads
const LIMITS_FILE_UPLOADS = {
  'free': { max: 5, period: 'month' },
  'pro': { max: 100, period: 'month' },
  'enterprise': { max: Infinity, period: 'month' },
};
// --- Endpoints ---
app.get('/api/billing/plans', async (req, res) => {
  try {
    return res.json({ message: "plans" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
app.get('/api/billing/usage', async (req, res) => {
  try {
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    const user_usage = await db.findAll('usages');
    return res.json(user_usage);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
app.post('/api/billing/subscribe', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const subscription_data = req.body;
    const incoming = req.params;
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    const _vErr = _validate(req.body, [{"field":"plan","type":"text","required":true}]);
    if (_vErr) return res.status(400).json({ error: _vErr });
    return res.json({ message: "subscribed" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// --- Webhook ---
app.post('/stripe/billing-events', async (req, res) => {
  const incoming = req.body;
  const crypto = require('crypto');
  const signature = req.headers['stripe-signature'] || '';
  const expected = crypto.createHmac('sha256', (process.env["STRIPE_BILLING_SECRET"] || "")).update(JSON.stringify(req.body)).digest('hex');
  if (signature !== expected) { return res.status(401).json({ error: "Invalid signature" }); }
  return res.json({ message: "ok" });
});

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});