#!/usr/bin/env node
// Browser UAT — auto-generated by Clear compiler. Do not hand-edit.
// Contract version: 1
// Pages: 8, controls: 25, apiCalls: 12

const BASE = process.env.TEST_URL || 'http://localhost:3000';
const CONTRACT = {
  "version": 1,
  "generatedAt": "compile-time-static",
  "app": {
    "hasWebTarget": true,
    "hasBackendTarget": true
  },
  "pages": [
    {
      "id": "Deal_Desk",
      "title": "Deal Desk",
      "route": "/",
      "line": 283,
      "expectedText": [
        "Deal Desk",
        "Clear",
        "Workspace / Deal Desk / Pending Queue",
        "Pending CRO approval",
        "deals waiting on you.",
        "New deal",
        "Pending",
        "Deal details",
        "List price",
        "Discount",
        "Risk score",
        "pending",
        "Clear Cloud"
      ],
      "routeSpecificText": "Deal Desk",
      "selector": "[data-clear-page-route=\"/\"]"
    },
    {
      "id": "Approved_today",
      "title": "Approved today",
      "route": "/approved",
      "line": 383,
      "expectedText": [
        "Approved today",
        "Approved requests cleared today and ready for audit.",
        "Approved Deals"
      ],
      "routeSpecificText": "Approved today",
      "selector": "[data-clear-page-route=\"/approved\"]"
    },
    {
      "id": "Rejected",
      "title": "Rejected",
      "route": "/rejected",
      "line": 393,
      "expectedText": [
        "Rejected",
        "Rejected deals",
        "Requests rejected after CRO review.",
        "Rejected Deals"
      ],
      "routeSpecificText": "Rejected deals",
      "selector": "[data-clear-page-route=\"/rejected\"]"
    },
    {
      "id": "Awaiting_customer",
      "title": "Awaiting customer",
      "route": "/awaiting",
      "line": 403,
      "expectedText": [
        "Awaiting customer",
        "Counters, signatures, and procurement follow-ups needing customer action.",
        "Awaiting Deals"
      ],
      "routeSpecificText": "Awaiting customer",
      "selector": "[data-clear-page-route=\"/awaiting\"]"
    },
    {
      "id": "All_deals",
      "title": "All deals",
      "route": "/all",
      "line": 413,
      "expectedText": [
        "All deals",
        "Total deal-desk requests across every status.",
        "Approval mix",
        "Segment pressure",
        "All Deals"
      ],
      "routeSpecificText": "All deals",
      "selector": "[data-clear-page-route=\"/all\"]"
    },
    {
      "id": "Reports",
      "title": "Reports",
      "route": "/reports",
      "line": 426,
      "expectedText": [
        "Reports",
        "Approval velocity, discount pressure, and value-at-stake reporting.",
        "Status mix",
        "Segment pressure",
        "Deal types",
        "All Deals"
      ],
      "routeSpecificText": "Reports",
      "selector": "[data-clear-page-route=\"/reports\"]"
    },
    {
      "id": "New_discount_request",
      "title": "New discount request",
      "route": "/new",
      "line": 440,
      "expectedText": [
        "New discount request",
        "Submit a discount request. Over 20 percent goes to the CRO queue.",
        "Back to queue"
      ],
      "routeSpecificText": "New discount request",
      "selector": "[data-clear-page-route=\"/new\"]"
    },
    {
      "id": "Sign_in",
      "title": "Sign in",
      "route": "/login",
      "line": 459,
      "expectedText": [
        "Sign in",
        "Sign in to the CRO console",
        "Use the signup or login form above. After signing in, head to /cro."
      ],
      "routeSpecificText": "Sign in to the CRO console",
      "selector": "[data-clear-page-route=\"/login\"]"
    }
  ],
  "routes": [
    {
      "path": "/",
      "pageId": "Deal_Desk",
      "directLoad": true
    },
    {
      "path": "/approved",
      "pageId": "Approved_today",
      "directLoad": true
    },
    {
      "path": "/rejected",
      "pageId": "Rejected",
      "directLoad": true
    },
    {
      "path": "/awaiting",
      "pageId": "Awaiting_customer",
      "directLoad": true
    },
    {
      "path": "/all",
      "pageId": "All_deals",
      "directLoad": true
    },
    {
      "path": "/reports",
      "pageId": "Reports",
      "directLoad": true
    },
    {
      "path": "/new",
      "pageId": "New_discount_request",
      "directLoad": true
    },
    {
      "path": "/login",
      "pageId": "Sign_in",
      "directLoad": true
    }
  ],
  "controls": [
    {
      "id": "nav_item_303_Pending",
      "kind": "nav-item",
      "label": "Pending",
      "line": 303,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_303_Pending\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/"
      },
      "expected": {
        "route": "/",
        "visiblePageId": "Deal_Desk",
        "visibleText": "Deal Desk"
      },
      "dataEffect": "navigates to /"
    },
    {
      "id": "nav_item_304_Approved_today",
      "kind": "nav-item",
      "label": "Approved today",
      "line": 304,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_304_Approved_today\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/approved"
      },
      "expected": {
        "route": "/approved",
        "visiblePageId": "Approved_today",
        "visibleText": "Approved today"
      },
      "dataEffect": "navigates to /approved"
    },
    {
      "id": "nav_item_305_Rejected",
      "kind": "nav-item",
      "label": "Rejected",
      "line": 305,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_305_Rejected\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/rejected"
      },
      "expected": {
        "route": "/rejected",
        "visiblePageId": "Rejected",
        "visibleText": "Rejected deals"
      },
      "dataEffect": "navigates to /rejected"
    },
    {
      "id": "nav_item_306_Awaiting_customer",
      "kind": "nav-item",
      "label": "Awaiting customer",
      "line": 306,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_306_Awaiting_customer\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/awaiting"
      },
      "expected": {
        "route": "/awaiting",
        "visiblePageId": "Awaiting_customer",
        "visibleText": "Awaiting customer"
      },
      "dataEffect": "navigates to /awaiting"
    },
    {
      "id": "nav_item_309_All_deals",
      "kind": "nav-item",
      "label": "All deals",
      "line": 309,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_309_All_deals\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/all"
      },
      "expected": {
        "route": "/all",
        "visiblePageId": "All_deals",
        "visibleText": "All deals"
      },
      "dataEffect": "navigates to /all"
    },
    {
      "id": "nav_item_310_Reports",
      "kind": "nav-item",
      "label": "Reports",
      "line": 310,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_310_Reports\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/reports"
      },
      "expected": {
        "route": "/reports",
        "visiblePageId": "Reports",
        "visibleText": "Reports"
      },
      "dataEffect": "navigates to /reports"
    },
    {
      "id": "route_tab_325_Pending",
      "kind": "route-tab",
      "label": "Pending",
      "line": 325,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"route_tab_325_Pending\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/"
      },
      "expected": {
        "route": "/",
        "visiblePageId": "Deal_Desk",
        "visibleText": "Deal Desk"
      },
      "dataEffect": "navigates to /"
    },
    {
      "id": "route_tab_326_My_approvals",
      "kind": "route-tab",
      "label": "My approvals",
      "line": 326,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"route_tab_326_My_approvals\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/approved"
      },
      "expected": {
        "route": "/approved",
        "visiblePageId": "Approved_today",
        "visibleText": "Approved today"
      },
      "dataEffect": "navigates to /approved"
    },
    {
      "id": "route_tab_327_All",
      "kind": "route-tab",
      "label": "All",
      "line": 327,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"route_tab_327_All\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/all"
      },
      "expected": {
        "route": "/all",
        "visiblePageId": "All_deals",
        "visibleText": "All deals"
      },
      "dataEffect": "navigates to /all"
    },
    {
      "id": "table_interaction_345_Pending",
      "kind": "table-interaction",
      "label": "Pending",
      "line": 345,
      "sourcePageRoute": "/",
      "selector": "#output_Pending_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Pending_table\"]",
        "sortSelector": "#output_Pending_table th[data-sortable]"
      },
      "dataEffect": "filters and sorts Pending"
    },
    {
      "id": "table_drilldown_345_Pending",
      "kind": "table-drilldown",
      "label": "Pending",
      "line": 345,
      "sourcePageRoute": "/",
      "selector": "#output_Pending_table button[data-row-select=\"true\"]",
      "action": {
        "type": "drilldown"
      },
      "expected": {
        "detailFor": "selected_deal",
        "detailSelector": "[data-detail-for=\"selected_deal\"]"
      },
      "dataEffect": "selects a Pending row for detail state"
    },
    {
      "id": "button_364_Draft_AI_summary",
      "kind": "button",
      "label": "Draft AI summary",
      "line": 364,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"button_364_Draft_AI_summary\"]",
      "action": {
        "type": "api-call",
        "method": "POST",
        "path": "/api/deals/draft"
      },
      "dataEffect": "calls POST /api/deals/draft"
    },
    {
      "id": "button_366_Reject",
      "kind": "button",
      "label": "Reject",
      "line": 366,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"button_366_Reject\"]",
      "action": {
        "type": "api-call",
        "method": "PUT",
        "path": "/api/deals/:id/reject"
      },
      "dataEffect": "calls PUT /api/deals/:id/reject"
    },
    {
      "id": "button_370_Counter",
      "kind": "button",
      "label": "Counter",
      "line": 370,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"button_370_Counter\"]",
      "action": {
        "type": "api-call",
        "method": "PUT",
        "path": "/api/deals/:id/counter"
      },
      "dataEffect": "calls PUT /api/deals/:id/counter"
    },
    {
      "id": "button_374_Approve",
      "kind": "button",
      "label": "Approve",
      "line": 374,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"button_374_Approve\"]",
      "action": {
        "type": "api-call",
        "method": "PUT",
        "path": "/api/deals/:id/approve"
      },
      "dataEffect": "calls PUT /api/deals/:id/approve"
    },
    {
      "id": "table_interaction_391_Approved_Deals",
      "kind": "table-interaction",
      "label": "Approved Deals",
      "line": 391,
      "sourcePageRoute": "/approved",
      "selector": "#output_Approved_Deals_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Approved_Deals_table\"]",
        "sortSelector": "#output_Approved_Deals_table th[data-sortable]"
      },
      "dataEffect": "filters and sorts Approved Deals"
    },
    {
      "id": "table_interaction_401_Rejected_Deals",
      "kind": "table-interaction",
      "label": "Rejected Deals",
      "line": 401,
      "sourcePageRoute": "/rejected",
      "selector": "#output_Rejected_Deals_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Rejected_Deals_table\"]",
        "sortSelector": "#output_Rejected_Deals_table th[data-sortable]"
      },
      "dataEffect": "filters and sorts Rejected Deals"
    },
    {
      "id": "table_interaction_411_Awaiting_Deals",
      "kind": "table-interaction",
      "label": "Awaiting Deals",
      "line": 411,
      "sourcePageRoute": "/awaiting",
      "selector": "#output_Awaiting_Deals_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Awaiting_Deals_table\"]",
        "sortSelector": "#output_Awaiting_Deals_table th[data-sortable]"
      },
      "dataEffect": "filters and sorts Awaiting Deals"
    },
    {
      "id": "table_interaction_424_All_Deals",
      "kind": "table-interaction",
      "label": "All Deals",
      "line": 424,
      "sourcePageRoute": "/all",
      "selector": "#output_All_Deals_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_All_Deals_table\"]",
        "sortSelector": "#output_All_Deals_table th[data-sortable]"
      },
      "dataEffect": "filters and sorts All Deals"
    },
    {
      "id": "table_interaction_438_All_Deals",
      "kind": "table-interaction",
      "label": "All Deals",
      "line": 438,
      "sourcePageRoute": "/reports",
      "selector": "#output_All_Deals_2_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_All_Deals_2_table\"]",
        "sortSelector": "#output_All_Deals_2_table th[data-sortable]"
      },
      "dataEffect": "filters and sorts All Deals"
    },
    {
      "id": "input_control_446_Your_name",
      "kind": "input-control",
      "label": "Your name",
      "line": 446,
      "sourcePageRoute": "/new",
      "selector": "#input_rep_name",
      "action": {
        "type": "input-change",
        "variable": "rep_name",
        "inputType": "text",
        "htmlType": "text",
        "htmlKind": "input",
        "choices": []
      },
      "dataEffect": "updates rep name"
    },
    {
      "id": "input_control_447_Customer",
      "kind": "input-control",
      "label": "Customer",
      "line": 447,
      "sourcePageRoute": "/new",
      "selector": "#input_customer",
      "action": {
        "type": "input-change",
        "variable": "customer",
        "inputType": "text",
        "htmlType": "text",
        "htmlKind": "input",
        "choices": []
      },
      "dataEffect": "updates customer"
    },
    {
      "id": "input_control_448_List_price____",
      "kind": "input-control",
      "label": "List price ($)",
      "line": 448,
      "sourcePageRoute": "/new",
      "selector": "#input_list_price",
      "action": {
        "type": "input-change",
        "variable": "list_price",
        "inputType": "number",
        "htmlType": "number",
        "htmlKind": "input",
        "choices": []
      },
      "dataEffect": "updates list price"
    },
    {
      "id": "input_control_449_Discount__",
      "kind": "input-control",
      "label": "Discount %",
      "line": 449,
      "sourcePageRoute": "/new",
      "selector": "#input_discount_percent",
      "action": {
        "type": "input-change",
        "variable": "discount_percent",
        "inputType": "number",
        "htmlType": "number",
        "htmlKind": "input",
        "choices": []
      },
      "dataEffect": "updates discount percent"
    },
    {
      "id": "button_450_Submit_for_approval",
      "kind": "button",
      "label": "Submit for approval",
      "line": 450,
      "sourcePageRoute": "/new",
      "selector": "[data-clear-uat-id=\"button_450_Submit_for_approval\"]",
      "action": {
        "type": "api-call",
        "method": "POST",
        "path": "/api/deals"
      },
      "dataEffect": "calls POST /api/deals"
    }
  ],
  "apiCalls": [
    {
      "method": "GET",
      "path": "/api/deals/pending",
      "line": 88,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/deals/approved",
      "line": 92,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/deals/rejected",
      "line": 95,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/deals/awaiting",
      "line": 98,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/deals/all",
      "line": 101,
      "usedByControlIds": []
    },
    {
      "method": "POST",
      "path": "/api/deals",
      "line": 111,
      "usedByControlIds": [
        "button_450_Submit_for_approval"
      ]
    },
    {
      "method": "POST",
      "path": "/api/deals/draft",
      "line": 136,
      "usedByControlIds": [
        "button_364_Draft_AI_summary"
      ]
    },
    {
      "method": "PUT",
      "path": "/api/deals/:id",
      "line": 141,
      "usedByControlIds": []
    },
    {
      "method": "POST",
      "path": "/api/seed",
      "line": 154,
      "usedByControlIds": []
    },
    {
      "method": "PUT",
      "path": "/api/deals/:id/reject",
      "line": 368,
      "usedByControlIds": [
        "button_366_Reject"
      ]
    },
    {
      "method": "PUT",
      "path": "/api/deals/:id/counter",
      "line": 372,
      "usedByControlIds": [
        "button_370_Counter"
      ]
    },
    {
      "method": "PUT",
      "path": "/api/deals/:id/approve",
      "line": 376,
      "usedByControlIds": [
        "button_374_Approve"
      ]
    }
  ],
  "warnings": [],
  "errors": []
};
const SCREENSHOT_DIR = process.env.CLEAR_UAT_SCREENSHOT_DIR || '.clear-uat-screenshots';

let passed = 0;
let failed = 0;
const failures = [];

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

async function test(name, fn) {
  try {
    await fn();
    passed += 1;
    console.log('PASS:', name);
  } catch (err) {
    failed += 1;
    const msg = err && err.message ? err.message : String(err);
    failures.push({ name, error: msg });
    console.log('FAIL:', name, '-', msg);
  }
}

function routeUrl(route) {
  return BASE + (route || '/');
}

function pageByRoute(route) {
  return CONTRACT.pages.find(p => p.route === route);
}

function screenshotName(spec) {
  const name = (spec.route || spec.title || 'route')
    .replace(/^\/+/, 'root-')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return (name || 'root') + '.png';
}

async function captureRouteScreenshot(page, spec) {
  if (process.env.CLEAR_UAT_SCREENSHOTS === '0') return;
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  await fs.mkdir(SCREENSHOT_DIR, { recursive: true });
  const file = path.join(SCREENSHOT_DIR, screenshotName(spec));
  await page.screenshot({ path: file, fullPage: false });
  console.log('SHOT:', file);
}

async function assertVisiblePage(page, spec, label) {
  if (!spec) return;
  const selector = '[data-clear-page-route="' + spec.route + '"]';
  const el = page.locator(selector).first();
  await el.waitFor({ state: 'visible', timeout: 3000 });
  if (spec.routeSpecificText) {
    const text = await el.innerText().catch(() => '');
    assert(text.includes(spec.routeSpecificText), label + ' expected page "' + spec.route + '" to show "' + spec.routeSpecificText + '".');
  }
}

async function assertNoPageOverflow(page, spec, label) {
  const layout = await page.evaluate(() => {
    const body = document.body;
    const viewportWidth = document.documentElement.clientWidth;
    const scrollWidth = Math.max(document.documentElement.scrollWidth, body ? body.scrollWidth : 0);
    return { viewportWidth, scrollWidth, overflowX: scrollWidth - viewportWidth };
  });
  assert(layout.overflowX <= 2, label + ' has page-level horizontal overflow on ' + spec.route + ': viewport=' + layout.viewportWidth + ', scrollWidth=' + layout.scrollWidth);
}

async function assertPersistentShell(page, spec, label) {
  if (/^\/(login|signup|auth)(\/|$)/.test(spec.route || '')) return;
  const root = page.locator('[data-clear-shell-root="true"]');
  if (await root.count() === 0) return;
  await root.first().waitFor({ state: 'visible', timeout: 3000 });
  const outlet = page.locator('[data-clear-shell-outlet="true"]').first();
  if (await outlet.count() > 0) await outlet.waitFor({ state: 'visible', timeout: 3000 });
  const shellText = await root.first().innerText().catch(() => '');
  assert(shellText.length > 0, label + ' expected the app shell to stay visible.');
}

let chromium;
try {
  ({ chromium } = await import('playwright'));
} catch (err) {
  console.log('FAIL: Browser UAT setup — generated browser UAT requires the dev dependency "playwright". Run: npm install --save-dev playwright');
  process.exitCode = 1;
}

if (chromium) {
  const browser = await chromium.launch({ headless: process.env.CLEAR_UAT_HEADLESS !== '0' });
  const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
  const consoleErrors = [];
  page.on('console', msg => {
    if (msg.type() === 'error' && !String(msg.text()).includes('favicon')) consoleErrors.push(msg.text());
  });
  page.on('pageerror', err => consoleErrors.push(err.message));

  try {
    for (const spec of CONTRACT.pages) {
      await test('Direct route: ' + spec.title, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(spec.route), { waitUntil: 'networkidle' });
        await assertVisiblePage(page, spec, 'Direct route ' + spec.title);
        await assertPersistentShell(page, spec, 'Direct route ' + spec.title);
        await assertNoPageOverflow(page, spec, 'Direct route ' + spec.title);
        await captureRouteScreenshot(page, spec);
        assert(consoleErrors.length === 0, 'Browser errors on ' + spec.route + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'navigate' && c.expected)) {
      await test('Click ' + control.kind + ': ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        await page.locator('[data-clear-uat-id="' + control.id + '"]').first().click();
        await page.waitForTimeout(75);
        const expectedPage = pageByRoute(control.expected.route);
        await assertVisiblePage(page, expectedPage, 'Click ' + control.kind + ' "' + control.label + '" [clear:' + control.line + ']');
        await assertPersistentShell(page, expectedPage, 'Click ' + control.kind + ' "' + control.label + '" [clear:' + control.line + ']');
        assert(consoleErrors.length === 0, 'Browser errors after clicking ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'input-change')) {
      await test('Use input control: ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        const input = page.locator(control.selector).first();
        await input.waitFor({ state: 'visible', timeout: 3000 });
        const htmlType = String(control.action.htmlType || '').toLowerCase();
        if (htmlType === 'select') {
          const choices = Array.isArray(control.action.choices) ? control.action.choices : [];
          if (choices.length > 0) {
            const choice = choices.length > 1 ? choices[1] : choices[0];
            await input.selectOption({ label: String(choice) }).catch(async () => {
              await input.selectOption(String(choice));
            });
            const value = await input.inputValue().catch(() => '');
            assert(String(value).length > 0, 'Select "' + control.label + '" should accept a choice.');
          }
        } else if (htmlType === 'checkbox') {
          const before = await input.isChecked();
          await input.setChecked(!before);
          const after = await input.isChecked();
          assert(after !== before, 'Input "' + control.label + '" should toggle checked state.');
        } else if (htmlType === 'file') {
          const disabled = await input.isDisabled().catch(() => false);
          assert(!disabled, 'File input "' + control.label + '" should be usable.');
        } else if (htmlType === 'rich-text') {
          await input.evaluate((el) => {
            el.textContent = 'UAT sample text';
            el.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText', data: 'UAT sample text' }));
          });
        } else {
          await input.fill(htmlType === 'number' ? '42' : 'UAT sample text');
          const value = await input.inputValue().catch(() => '');
          assert(String(value).length > 0, 'Input "' + control.label + '" should accept a value.');
        }
        await page.waitForTimeout(75);
        assert(consoleErrors.length === 0, 'Browser errors after using input control ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'table-interaction')) {
      await test('Use table controls: ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        const table = page.locator(control.selector).first();
        await table.waitFor({ state: 'visible', timeout: 3000 });
        const filter = page.locator(control.action.filterSelector).first();
        if (await filter.count() === 0) return;
        await filter.waitFor({ state: 'visible', timeout: 3000 });
        const rows = table.locator('tbody tr');
        const sortHeaders = page.locator(control.action.sortSelector);
        if (await sortHeaders.count() > 0) {
          const header = sortHeaders.first();
          await header.click();
          await page.waitForTimeout(75);
          const sortedClass = await header.getAttribute('class') || '';
          const sortedDir = await header.getAttribute('data-sort-dir') || '';
          assert(sortedClass.split(/\s+/).includes('is-sorted') || sortedDir.length > 0, 'Table "' + control.label + '" sortable header should show sorted state.');
        }
        if (await rows.count() > 0) {
          const rowText = (await rows.first().innerText().catch(() => '')).trim();
          const token = (rowText.match(/[A-Za-z][A-Za-z0-9_-]{2,}/) || [])[0] || '';
          if (token) {
            await filter.fill(token);
            await page.waitForTimeout(75);
            const filteredText = (await table.innerText().catch(() => '')).toLowerCase();
            assert(filteredText.includes(token.toLowerCase()), 'Table "' + control.label + '" quick filter should show matching text.');
          }
        }
        assert(consoleErrors.length === 0, 'Browser errors after using table controls ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'drilldown')) {
      await test('Click ' + control.kind + ': ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        const clickTarget = page.locator(control.selector).first();
        if (await clickTarget.count() === 0) return;
        await clickTarget.waitFor({ state: 'visible', timeout: 3000 });
        await clickTarget.click();
        await page.waitForTimeout(100);
        const detailSelector = control.expected && control.expected.detailSelector
          ? control.expected.detailSelector
          : '[data-detail-for="' + (control.expected?.detailFor || '') + '"]';
        const detail = page.locator(detailSelector).first();
        await detail.waitFor({ state: 'visible', timeout: 3000 });
        const text = (await detail.innerText().catch(() => '')).trim();
        assert(text.length > 0, 'Click table drilldown "' + control.label + '" should show detail text.');
        assert(consoleErrors.length === 0, 'Browser errors after clicking table drilldown ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }
  } finally {
    await browser.close();
  }
}

console.log('Browser UAT:', passed, 'passed,', failed, 'failed');
process.exitCode = failed > 0 ? 1 : 0;
