#!/usr/bin/env node
// Browser UAT — auto-generated by Clear compiler. Do not hand-edit.
// Contract version: 1
// Pages: 8, controls: 18, apiCalls: 9

const BASE = process.env.TEST_URL || 'http://localhost:3000';
const CONTRACT = {
  "version": 1,
  "generatedAt": "compile-time-static",
  "app": {
    "hasWebTarget": true,
    "hasBackendTarget": true
  },
  "pages": [
    {
      "id": "Deal_Desk",
      "title": "Deal Desk",
      "route": "/",
      "line": 266,
      "expectedText": [
        "Deal Desk",
        "Clear",
        "Workspace / Deal Desk / Pending Queue",
        "Pending CRO approval",
        "deals waiting on you.",
        "Pending",
        "Deal details",
        "List price",
        "Discount",
        "Risk score",
        "pending",
        "Clear Cloud"
      ],
      "routeSpecificText": "Deal Desk",
      "selector": "[data-clear-page-route=\"/\"]"
    },
    {
      "id": "Approved_today",
      "title": "Approved today",
      "route": "/approved",
      "line": 355,
      "expectedText": [
        "Approved today",
        "Approved requests cleared today and ready for audit.",
        "Approved Deals"
      ],
      "routeSpecificText": "Approved today",
      "selector": "[data-clear-page-route=\"/approved\"]"
    },
    {
      "id": "Rejected",
      "title": "Rejected",
      "route": "/rejected",
      "line": 365,
      "expectedText": [
        "Rejected",
        "Rejected deals",
        "Requests rejected after CRO review.",
        "Rejected Deals"
      ],
      "routeSpecificText": "Rejected deals",
      "selector": "[data-clear-page-route=\"/rejected\"]"
    },
    {
      "id": "Awaiting_customer",
      "title": "Awaiting customer",
      "route": "/awaiting",
      "line": 375,
      "expectedText": [
        "Awaiting customer",
        "Counters, signatures, and procurement follow-ups needing customer action.",
        "Awaiting Deals"
      ],
      "routeSpecificText": "Awaiting customer",
      "selector": "[data-clear-page-route=\"/awaiting\"]"
    },
    {
      "id": "All_deals",
      "title": "All deals",
      "route": "/all",
      "line": 385,
      "expectedText": [
        "All deals",
        "Total deal-desk requests across every status.",
        "Approval mix",
        "Segment pressure",
        "All Deals"
      ],
      "routeSpecificText": "All deals",
      "selector": "[data-clear-page-route=\"/all\"]"
    },
    {
      "id": "Reports",
      "title": "Reports",
      "route": "/reports",
      "line": 398,
      "expectedText": [
        "Reports",
        "Approval velocity, discount pressure, and value-at-stake reporting.",
        "Status mix",
        "Segment pressure",
        "Deal types",
        "All Deals"
      ],
      "routeSpecificText": "Reports",
      "selector": "[data-clear-page-route=\"/reports\"]"
    },
    {
      "id": "New_discount_request",
      "title": "New discount request",
      "route": "/new",
      "line": 412,
      "expectedText": [
        "New discount request",
        "Submit a discount request. Over 20 percent goes to the CRO queue.",
        "Back to queue"
      ],
      "routeSpecificText": "New discount request",
      "selector": "[data-clear-page-route=\"/new\"]"
    },
    {
      "id": "Sign_in",
      "title": "Sign in",
      "route": "/login",
      "line": 431,
      "expectedText": [
        "Sign in",
        "Sign in to the CRO console",
        "Use the signup or login form above. After signing in, head to /cro."
      ],
      "routeSpecificText": "Sign in to the CRO console",
      "selector": "[data-clear-page-route=\"/login\"]"
    }
  ],
  "routes": [
    {
      "path": "/",
      "pageId": "Deal_Desk",
      "directLoad": true
    },
    {
      "path": "/approved",
      "pageId": "Approved_today",
      "directLoad": true
    },
    {
      "path": "/rejected",
      "pageId": "Rejected",
      "directLoad": true
    },
    {
      "path": "/awaiting",
      "pageId": "Awaiting_customer",
      "directLoad": true
    },
    {
      "path": "/all",
      "pageId": "All_deals",
      "directLoad": true
    },
    {
      "path": "/reports",
      "pageId": "Reports",
      "directLoad": true
    },
    {
      "path": "/new",
      "pageId": "New_discount_request",
      "directLoad": true
    },
    {
      "path": "/login",
      "pageId": "Sign_in",
      "directLoad": true
    }
  ],
  "controls": [
    {
      "id": "nav_item_286_Pending",
      "kind": "nav-item",
      "label": "Pending",
      "line": 286,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_286_Pending\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/"
      },
      "expected": {
        "route": "/",
        "visiblePageId": "Deal_Desk",
        "visibleText": "Deal Desk"
      }
    },
    {
      "id": "nav_item_287_Approved_today",
      "kind": "nav-item",
      "label": "Approved today",
      "line": 287,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_287_Approved_today\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/approved"
      },
      "expected": {
        "route": "/approved",
        "visiblePageId": "Approved_today",
        "visibleText": "Approved today"
      }
    },
    {
      "id": "nav_item_288_Rejected",
      "kind": "nav-item",
      "label": "Rejected",
      "line": 288,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_288_Rejected\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/rejected"
      },
      "expected": {
        "route": "/rejected",
        "visiblePageId": "Rejected",
        "visibleText": "Rejected deals"
      }
    },
    {
      "id": "nav_item_289_Awaiting_customer",
      "kind": "nav-item",
      "label": "Awaiting customer",
      "line": 289,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_289_Awaiting_customer\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/awaiting"
      },
      "expected": {
        "route": "/awaiting",
        "visiblePageId": "Awaiting_customer",
        "visibleText": "Awaiting customer"
      }
    },
    {
      "id": "nav_item_292_All_deals",
      "kind": "nav-item",
      "label": "All deals",
      "line": 292,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_292_All_deals\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/all"
      },
      "expected": {
        "route": "/all",
        "visiblePageId": "All_deals",
        "visibleText": "All deals"
      }
    },
    {
      "id": "nav_item_293_Reports",
      "kind": "nav-item",
      "label": "Reports",
      "line": 293,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_293_Reports\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/reports"
      },
      "expected": {
        "route": "/reports",
        "visiblePageId": "Reports",
        "visibleText": "Reports"
      }
    },
    {
      "id": "route_tab_308_Pending",
      "kind": "route-tab",
      "label": "Pending",
      "line": 308,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"route_tab_308_Pending\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/"
      },
      "expected": {
        "route": "/",
        "visiblePageId": "Deal_Desk",
        "visibleText": "Deal Desk"
      }
    },
    {
      "id": "route_tab_309_My_approvals",
      "kind": "route-tab",
      "label": "My approvals",
      "line": 309,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"route_tab_309_My_approvals\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/approved"
      },
      "expected": {
        "route": "/approved",
        "visiblePageId": "Approved_today",
        "visibleText": "Approved today"
      }
    },
    {
      "id": "route_tab_310_All",
      "kind": "route-tab",
      "label": "All",
      "line": 310,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"route_tab_310_All\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/all"
      },
      "expected": {
        "route": "/all",
        "visiblePageId": "All_deals",
        "visibleText": "All deals"
      }
    },
    {
      "id": "table_interaction_328_Pending",
      "kind": "table-interaction",
      "label": "Pending",
      "line": 328,
      "sourcePageRoute": "/",
      "selector": "#output_Pending_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Pending_table\"]",
        "sortSelector": "#output_Pending_table th[data-sortable]"
      }
    },
    {
      "id": "table_drilldown_328_Pending",
      "kind": "table-drilldown",
      "label": "Pending",
      "line": 328,
      "sourcePageRoute": "/",
      "selector": "#output_Pending_table button[data-row-select=\"true\"]",
      "action": {
        "type": "drilldown"
      },
      "expected": {
        "detailFor": "selected_deal",
        "detailSelector": "[data-detail-for=\"selected_deal\"]"
      }
    },
    {
      "id": "button_345_Draft_AI_summary",
      "kind": "button",
      "label": "Draft AI summary",
      "line": 345,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"button_345_Draft_AI_summary\"]",
      "action": {
        "type": "api-call",
        "method": "POST",
        "path": "/api/deals/draft"
      }
    },
    {
      "id": "table_interaction_363_Approved_Deals",
      "kind": "table-interaction",
      "label": "Approved Deals",
      "line": 363,
      "sourcePageRoute": "/approved",
      "selector": "#output_Approved_Deals_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Approved_Deals_table\"]",
        "sortSelector": "#output_Approved_Deals_table th[data-sortable]"
      }
    },
    {
      "id": "table_interaction_373_Rejected_Deals",
      "kind": "table-interaction",
      "label": "Rejected Deals",
      "line": 373,
      "sourcePageRoute": "/rejected",
      "selector": "#output_Rejected_Deals_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Rejected_Deals_table\"]",
        "sortSelector": "#output_Rejected_Deals_table th[data-sortable]"
      }
    },
    {
      "id": "table_interaction_383_Awaiting_Deals",
      "kind": "table-interaction",
      "label": "Awaiting Deals",
      "line": 383,
      "sourcePageRoute": "/awaiting",
      "selector": "#output_Awaiting_Deals_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Awaiting_Deals_table\"]",
        "sortSelector": "#output_Awaiting_Deals_table th[data-sortable]"
      }
    },
    {
      "id": "table_interaction_396_All_Deals",
      "kind": "table-interaction",
      "label": "All Deals",
      "line": 396,
      "sourcePageRoute": "/all",
      "selector": "#output_All_Deals_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_All_Deals_table\"]",
        "sortSelector": "#output_All_Deals_table th[data-sortable]"
      }
    },
    {
      "id": "table_interaction_410_All_Deals",
      "kind": "table-interaction",
      "label": "All Deals",
      "line": 410,
      "sourcePageRoute": "/reports",
      "selector": "#output_All_Deals_2_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_All_Deals_2_table\"]",
        "sortSelector": "#output_All_Deals_2_table th[data-sortable]"
      }
    },
    {
      "id": "button_422_Submit_for_approval",
      "kind": "button",
      "label": "Submit for approval",
      "line": 422,
      "sourcePageRoute": "/new",
      "selector": "[data-clear-uat-id=\"button_422_Submit_for_approval\"]",
      "action": {
        "type": "api-call",
        "method": "POST",
        "path": "/api/deals"
      }
    }
  ],
  "apiCalls": [
    {
      "method": "GET",
      "path": "/api/deals/pending",
      "line": 88,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/deals/approved",
      "line": 92,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/deals/rejected",
      "line": 95,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/deals/awaiting",
      "line": 98,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/deals/all",
      "line": 101,
      "usedByControlIds": []
    },
    {
      "method": "POST",
      "path": "/api/deals",
      "line": 104,
      "usedByControlIds": [
        "button_422_Submit_for_approval"
      ]
    },
    {
      "method": "POST",
      "path": "/api/deals/draft",
      "line": 119,
      "usedByControlIds": [
        "button_345_Draft_AI_summary"
      ]
    },
    {
      "method": "PUT",
      "path": "/api/deals/:id",
      "line": 124,
      "usedByControlIds": []
    },
    {
      "method": "POST",
      "path": "/api/seed",
      "line": 137,
      "usedByControlIds": []
    }
  ],
  "warnings": [],
  "errors": []
};
const SCREENSHOT_DIR = process.env.CLEAR_UAT_SCREENSHOT_DIR || '.clear-uat-screenshots';

let passed = 0;
let failed = 0;
const failures = [];

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

async function test(name, fn) {
  try {
    await fn();
    passed += 1;
    console.log('PASS:', name);
  } catch (err) {
    failed += 1;
    const msg = err && err.message ? err.message : String(err);
    failures.push({ name, error: msg });
    console.log('FAIL:', name, '-', msg);
  }
}

function routeUrl(route) {
  return BASE + (route || '/');
}

function pageByRoute(route) {
  return CONTRACT.pages.find(p => p.route === route);
}

function screenshotName(spec) {
  const name = (spec.route || spec.title || 'route')
    .replace(/^\/+/, 'root-')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return (name || 'root') + '.png';
}

async function captureRouteScreenshot(page, spec) {
  if (process.env.CLEAR_UAT_SCREENSHOTS === '0') return;
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  await fs.mkdir(SCREENSHOT_DIR, { recursive: true });
  const file = path.join(SCREENSHOT_DIR, screenshotName(spec));
  await page.screenshot({ path: file, fullPage: false });
  console.log('SHOT:', file);
}

async function assertVisiblePage(page, spec, label) {
  if (!spec) return;
  const selector = '[data-clear-page-route="' + spec.route + '"]';
  const el = page.locator(selector).first();
  await el.waitFor({ state: 'visible', timeout: 3000 });
  if (spec.routeSpecificText) {
    const text = await el.innerText().catch(() => '');
    assert(text.includes(spec.routeSpecificText), label + ' expected page "' + spec.route + '" to show "' + spec.routeSpecificText + '".');
  }
}

async function assertNoPageOverflow(page, spec, label) {
  const layout = await page.evaluate(() => {
    const body = document.body;
    const viewportWidth = document.documentElement.clientWidth;
    const scrollWidth = Math.max(document.documentElement.scrollWidth, body ? body.scrollWidth : 0);
    return { viewportWidth, scrollWidth, overflowX: scrollWidth - viewportWidth };
  });
  assert(layout.overflowX <= 2, label + ' has page-level horizontal overflow on ' + spec.route + ': viewport=' + layout.viewportWidth + ', scrollWidth=' + layout.scrollWidth);
}

async function assertPersistentShell(page, spec, label) {
  if (/^\/(login|signup|auth)(\/|$)/.test(spec.route || '')) return;
  const root = page.locator('[data-clear-shell-root="true"]');
  if (await root.count() === 0) return;
  await root.first().waitFor({ state: 'visible', timeout: 3000 });
  const outlet = page.locator('[data-clear-shell-outlet="true"]').first();
  if (await outlet.count() > 0) await outlet.waitFor({ state: 'visible', timeout: 3000 });
  const shellText = await root.first().innerText().catch(() => '');
  assert(shellText.length > 0, label + ' expected the app shell to stay visible.');
}

let chromium;
try {
  ({ chromium } = await import('playwright'));
} catch (err) {
  console.log('FAIL: Browser UAT setup — generated browser UAT requires the dev dependency "playwright". Run: npm install --save-dev playwright');
  process.exitCode = 1;
}

if (chromium) {
  const browser = await chromium.launch({ headless: process.env.CLEAR_UAT_HEADLESS !== '0' });
  const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
  const consoleErrors = [];
  page.on('console', msg => {
    if (msg.type() === 'error' && !String(msg.text()).includes('favicon')) consoleErrors.push(msg.text());
  });
  page.on('pageerror', err => consoleErrors.push(err.message));

  try {
    for (const spec of CONTRACT.pages) {
      await test('Direct route: ' + spec.title, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(spec.route), { waitUntil: 'networkidle' });
        await assertVisiblePage(page, spec, 'Direct route ' + spec.title);
        await assertPersistentShell(page, spec, 'Direct route ' + spec.title);
        await assertNoPageOverflow(page, spec, 'Direct route ' + spec.title);
        await captureRouteScreenshot(page, spec);
        assert(consoleErrors.length === 0, 'Browser errors on ' + spec.route + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'navigate' && c.expected)) {
      await test('Click ' + control.kind + ': ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        await page.locator('[data-clear-uat-id="' + control.id + '"]').first().click();
        await page.waitForTimeout(75);
        const expectedPage = pageByRoute(control.expected.route);
        await assertVisiblePage(page, expectedPage, 'Click ' + control.kind + ' "' + control.label + '" [clear:' + control.line + ']');
        await assertPersistentShell(page, expectedPage, 'Click ' + control.kind + ' "' + control.label + '" [clear:' + control.line + ']');
        assert(consoleErrors.length === 0, 'Browser errors after clicking ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'table-interaction')) {
      await test('Use table controls: ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        const table = page.locator(control.selector).first();
        await table.waitFor({ state: 'visible', timeout: 3000 });
        const filter = page.locator(control.action.filterSelector).first();
        if (await filter.count() === 0) return;
        await filter.waitFor({ state: 'visible', timeout: 3000 });
        const rows = table.locator('tbody tr');
        const sortHeaders = page.locator(control.action.sortSelector);
        if (await sortHeaders.count() > 0) {
          const header = sortHeaders.first();
          await header.click();
          await page.waitForTimeout(75);
          const sortedClass = await header.getAttribute('class') || '';
          const sortedDir = await header.getAttribute('data-sort-dir') || '';
          assert(sortedClass.split(/\s+/).includes('is-sorted') || sortedDir.length > 0, 'Table "' + control.label + '" sortable header should show sorted state.');
        }
        if (await rows.count() > 0) {
          const rowText = (await rows.first().innerText().catch(() => '')).trim();
          const token = (rowText.match(/[A-Za-z][A-Za-z0-9_-]{2,}/) || [])[0] || '';
          if (token) {
            await filter.fill(token);
            await page.waitForTimeout(75);
            const filteredText = (await table.innerText().catch(() => '')).toLowerCase();
            assert(filteredText.includes(token.toLowerCase()), 'Table "' + control.label + '" quick filter should show matching text.');
          }
        }
        assert(consoleErrors.length === 0, 'Browser errors after using table controls ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'drilldown')) {
      await test('Click ' + control.kind + ': ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        const clickTarget = page.locator(control.selector).first();
        if (await clickTarget.count() === 0) return;
        await clickTarget.waitFor({ state: 'visible', timeout: 3000 });
        await clickTarget.click();
        await page.waitForTimeout(100);
        const detailSelector = control.expected && control.expected.detailSelector
          ? control.expected.detailSelector
          : '[data-detail-for="' + (control.expected?.detailFor || '') + '"]';
        const detail = page.locator(detailSelector).first();
        await detail.waitFor({ state: 'visible', timeout: 3000 });
        const text = (await detail.innerText().catch(() => '')).trim();
        assert(text.length > 0, 'Click table drilldown "' + control.label + '" should show detail text.');
        assert(consoleErrors.length === 0, 'Browser errors after clicking table drilldown ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }
  } finally {
    await browser.close();
  }
}

console.log('Browser UAT:', passed, 'passed,', failed, 'failed');
process.exitCode = failed > 0 ? 1 : 0;
