#!/usr/bin/env node
// E2E tests -- auto-generated by Clear compiler
// Run: node test.js
// Requires: server running on localhost:3000

const BASE = process.env.TEST_URL || "http://localhost:3000";
let passed = 0, failed = 0, skipped = 0;
let _emailCounter = 0;
let _uniqueCounter = 0;
let _response, _responseBody;
let _lastCall = { method: "", path: "", line: 0 };
function _uniqueEmail() { return "test" + (++_emailCounter) + "@example.com"; }
function _uniqueText(base) { return base + "_" + (++_uniqueCounter); }

// Note: for clean re-runs, delete clear-data.db before starting the server
// unique constraints may cause 500s if stale data exists from a previous run

// Generate a test auth token compatible with the server's JWT verification
// Uses jsonwebtoken (same library as compiled server) with JWT_SECRET env var
const jwt = require("jsonwebtoken");
const _testSecret = process.env.JWT_SECRET || "clear-test-secret";
const TEST_TOKEN = jwt.sign({ id: 1, role: "admin", email: "test@test.com" }, _testSecret, { expiresIn: "1h" });
const AUTH_HEADERS = { "Authorization": "Bearer " + TEST_TOKEN, "Content-Type": "application/json" };

const _concurrency = Math.max(1, parseInt(process.env.CLEAR_CONCURRENCY || "1", 10) || 1);
async function test(name, fn) {
  if (_concurrency > 1) {
    // Run the body N times in parallel and report aggregate result.
    const _results = await Promise.all(Array.from({length: _concurrency}, async () => {
      try { await fn(); return {ok: true}; }
      catch (err) { return {ok: false, err: err && err.message ? String(err.message) : String(err)}; }
    }));
    const _ok = _results.filter(r => r.ok).length;
    const _ko = _results.length - _ok;
    if (_ok === _results.length) {
      passed++;
      console.log("PASS:", name, "(" + _ok + "/" + _ok + " parallel runs OK)");
    } else if (_ok > 0 && _ko > 0) {
      // Some passed, some failed — reportable race signature.
      passed++;
      console.log("PASS:", name, "(" + _ok + "/" + _results.length + " parallel runs OK, " + _ko + " conflicted — expected for optimistic-lock endpoints)");
    } else {
      failed++;
      const _firstErr = _results.find(r => !r.ok);
      console.log("FAIL:", name, "(" + _ko + "/" + _results.length + " parallel runs failed) -", _firstErr ? _firstErr.err : "all failed");
    }
    return;
  }
  try {
    await fn();
    passed++;
    console.log("PASS:", name);
  } catch (err) {
    const _msg = err && err.message ? String(err.message) : "";
    if (_msg.indexOf("placeholder hit at line") === 0) {
      skipped++;
      console.log("SKIP:", name, "-", _msg, "(this test exercises a stub)");
    } else {
      failed++;
      console.log("FAIL:", name, "-", _msg);
    }
  }
}

function assert(condition, msg) { if (!condition) throw new Error(msg); }

async function run() {
  await test("Viewing all pending returns data", async () => {
    const r = await fetch(BASE + "/api/deals/pending");
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("Viewing all approved returns data", async () => {
    const r = await fetch(BASE + "/api/deals/approved");
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("Viewing all rejected returns data", async () => {
    const r = await fetch(BASE + "/api/deals/rejected");
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("Viewing all awaiting returns data", async () => {
    const r = await fetch(BASE + "/api/deals/awaiting");
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("Viewing all all returns data", async () => {
    const r = await fetch(BASE + "/api/deals/all");
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("Creating a new deal succeeds", async () => {
    const payload = {"rep_name":"Test value","customer":"Test value"};
    payload["rep_name"] = _uniqueText("rep_name");
    payload["customer"] = _uniqueText("customer");
    const r = await fetch(BASE + "/api/deals", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.id, "Response should have an id");
  });

  await test("Creating a deal without any data is rejected", async () => {
    const r = await fetch(BASE + "/api/deals", { method: "POST", headers: { "Authorization": "Bearer " + TEST_TOKEN } });
    assert(r.status >= 400 && r.status < 500, "Expected 4xx (rejection), got " + r.status);
  });

  await test("Creating a deal with a blank rep_name is rejected", async () => {
    const r = await fetch(BASE + "/api/deals", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify({ rep_name: "" })
    });
    assert(r.status >= 400 && r.status < 500, "Expected 4xx (rejection), got " + r.status);
  });

  await test("Creating a deal with a rep_name that's too long is rejected", async () => {
    const r = await fetch(BASE + "/api/deals", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify({ rep_name: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" })
    });
    assert(r.status >= 400 && r.status < 500, "Expected 4xx (rejection), got " + r.status);
  });

  await test("Extra fields are stripped when creating a deal", async () => {
    const payload = { ...{"rep_name":"Test value","customer":"Test value"}, admin: true, role: "superuser" };
    payload["rep_name"] = _uniqueText("rep_name");
    payload["customer"] = _uniqueText("customer");
    const r = await fetch(BASE + "/api/deals", {
      method: "POST", headers: AUTH_HEADERS,
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.admin === undefined, "admin field should have been stripped");
    assert(data.role === undefined, "role field should have been stripped");
  });

  await test("The app loads in the browser", async () => {
    const r = await fetch(BASE + "/");
    assert(r.status === 200, "Expected 200, got " + r.status);
    const html = await r.text();
    assert(html.includes("<!DOCTYPE html>"), "Expected HTML document");
  });

  // --- Frontend Element Tests (auto-generated) ---

  await test("The Deal Desk page renders", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes("Deal Desk"), "Page should contain title 'Deal Desk'");
  });

  await test("The Approved today page renders", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes("Approved today"), "Page should contain title 'Approved today'");
  });

  await test("The Rejected page renders", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes("Rejected"), "Page should contain title 'Rejected'");
  });

  await test("The Awaiting customer page renders", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes("Awaiting customer"), "Page should contain title 'Awaiting customer'");
  });

  await test("The All deals page renders", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes("All deals"), "Page should contain title 'All deals'");
  });

  await test("The Reports page renders", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes("Reports"), "Page should contain title 'Reports'");
  });

  await test("The New discount request page renders", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes("New discount request"), "Page should contain title 'New discount request'");
  });

  await test("The Sign in page renders", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes("Sign in"), "Page should contain title 'Sign in'");
  });

  await test("The Back to queue link goes to the right page", async () => {
    const r = await fetch(BASE + "/");
    const html = await r.text();
    assert(html.includes('href="#/"') || html.includes('href="/"'), "Link 'Back to queue' should have href to '/', not '#'");
  });

  // --- User-Written Tests (from test blocks in .clear source) ---
  const _baseUrl = BASE;
  // _response / _responseBody are globals (declared at top) so helpers can see them

  await test("happy path: discount under cap is accepted", async () => {
      // clear:483
      _response = await fetch(_baseUrl + "/api/deals", {
        method: "POST", headers: AUTH_HEADERS,
        body: JSON.stringify({ "rep_name": "mike.l", "customer": "Beta Co", "list_price": 50000, "discount_percent": 10 })
      });
      _responseBody = await _response.json().catch(() => null);
  
      // clear:484
      _expectSuccess(_response);
  });

  await test("happy path: discount at threshold-1 still accepted", async () => {
      // clear:487
      _response = await fetch(_baseUrl + "/api/deals", {
        method: "POST", headers: AUTH_HEADERS,
        body: JSON.stringify({ "rep_name": "sarah.j", "customer": "Acme Corp", "list_price": 240000, "discount_percent": 29 })
      });
      _responseBody = await _response.json().catch(() => null);
  
      // clear:488
      _expectSuccess(_response);
  });

  await test("rule discount-cap-thirty: discount of 30 is rejected", async () => {
      // clear:491
      _response = await fetch(_baseUrl + "/api/deals", {
        method: "POST", headers: AUTH_HEADERS,
        body: JSON.stringify({ "rep_name": "rejected.case", "customer": "Big Corp", "list_price": 100000, "discount_percent": 30 })
      });
      _responseBody = await _response.json().catch(() => null);
  
      // clear:492
      _expectFailure(_response);
  });

  await test("rule discount-cap-thirty: discount of 35 is rejected", async () => {
      // clear:495
      _response = await fetch(_baseUrl + "/api/deals", {
        method: "POST", headers: AUTH_HEADERS,
        body: JSON.stringify({ "rep_name": "rejected.case", "customer": "Big Corp", "list_price": 100000, "discount_percent": 35 })
      });
      _responseBody = await _response.json().catch(() => null);
  
      // clear:496
      _expectFailure(_response);
  });

  await test("rule discount-not-over-cap: discount of 100 is rejected", async () => {
      // clear:499
      _response = await fetch(_baseUrl + "/api/deals", {
        method: "POST", headers: AUTH_HEADERS,
        body: JSON.stringify({ "rep_name": "absurd.case", "customer": "Free Co", "list_price": 50000, "discount_percent": 100 })
      });
      _responseBody = await _response.json().catch(() => null);
  
      // clear:500
      _expectFailure(_response);
  });

  await test("rule price-floor-positive: list_price of 0 is rejected", async () => {
      // clear:503
      _response = await fetch(_baseUrl + "/api/deals", {
        method: "POST", headers: AUTH_HEADERS,
        body: JSON.stringify({ "rep_name": "free.case", "customer": "Zero Inc", "list_price": 0, "discount_percent": 10 })
      });
      _responseBody = await _response.json().catch(() => null);
  
      // clear:504
      _expectFailure(_response);
  });

  await test("rule price-floor-positive: negative list_price is rejected", async () => {
      // clear:507
      _response = await fetch(_baseUrl + "/api/deals", {
        method: "POST", headers: AUTH_HEADERS,
        body: JSON.stringify({ "rep_name": "neg.case", "customer": "Negative Inc", "list_price": -100, "discount_percent": 10 })
      });
      _responseBody = await _response.json().catch(() => null);
  
      // clear:508
      _expectFailure(_response);
  });

  await test("auth: updating a deal requires login", async () => {
      // clear:511
      // Could not find PUT endpoint for deal
  });

  await test("auth: creating a deal requires login", async () => {
      // clear:514
      _response = await fetch(_baseUrl + "/api/deals", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ test: true })
      });
      assert(_response.status === 401, "Should require login, got " + _response.status);
  });

  await test("happy path: approving a deal works", async () => {
      // clear:517
      // Could not find approve endpoint for deal
  });

  console.log("");
  console.log("Results:", passed, "passed,", failed, "failed,", skipped, "skipped due to stub");
  process.exit(failed > 0 ? 1 : 0);
}

// Expect shim for user-written test assertions
function expect(val) {
  return {
    toBe(expected) { if (val !== expected) throw new Error("Expected " + expected + ", got " + val); },
    toBeTruthy() { if (!val) throw new Error("Expected truthy, got " + val); },
    toHaveProperty(key) { if (!(key in (val || {}))) throw new Error("Expected property " + key); },
    toBeGreaterThan(n) { if (!(val > n)) throw new Error("Expected > " + n + ", got " + val); }
  };
}

function _expectStatus(response, expected) {
  const actual = response.status;
  if (actual === expected) return;
  const where = _lastCall && _lastCall.line ? " [clear:" + _lastCall.line + "]" : "";
  const call = _lastCall && _lastCall.method ? _lastCall.method + " " + _lastCall.path : "the request";
  const bodyHint = _responseBody && _responseBody.error ? " Server said: \"" + String(_responseBody.error).slice(0, 120) + "\"." : "";
  // Translate each status code into plain English. The hint names the problem
  // AND points at the Clear code that needs to change.
  let why = "";
  if (actual === 404) {
    why = "404 means \"there is no endpoint at that URL.\" Either the path in your test is wrong, or you forgot to write `when user calls " + _lastCall.method + " " + _lastCall.path + ":` in your Clear file.";
  } else if (actual === 401) {
    why = "401 means \"you have to be logged in to do this.\" The endpoint has `requires login` but the test didn't send an auth token.";
  } else if (actual === 403) {
    why = "403 means \"you're logged in but not allowed to do this.\" The endpoint has `requires role 'admin'` (or similar) and the test user doesn't have that role.";
  } else if (actual === 400) {
    why = "400 means \"the server didn't like the data you sent.\" Usually a `validate` rule rejected it — a required field is missing, empty, or the wrong type.";
  } else if (actual === 409) {
    why = "409 means \"something already exists with that value.\" A field marked `unique` (like email) already has a record with that value — use a different value or delete the old record first.";
  } else if (actual === 422) {
    why = "422 means \"the data was the right shape but failed a rule.\" A `validate` block rejected it (wrong format, out of range, etc).";
  } else if (actual === 429) {
    why = "429 means \"too many requests.\" A `rate limit` rule is throttling the test. Wait, or raise the limit in your Clear code.";
  } else if (actual >= 500 && actual < 600) {
    why = "5xx means \"the server crashed trying to handle this.\" Check the app logs for a stack trace — usually an unhandled error in the endpoint body.";
  } else if (expected === 201 && actual === 200) {
    why = "200 means \"success\" and 201 means \"success, and I created a new record.\" Your endpoint returned success but not the 'created' flavor. Add `with status 201` to the `send back` line after a save.";
  } else if (expected === 200 && actual === 201) {
    why = "201 means \"created\" and 200 means \"success.\" The test expected a plain success but got a created — change the test to expect 201, or change the endpoint to `send back X` without `with status 201`.";
  } else if (expected === 204 && actual === 200) {
    why = "204 means \"done, nothing to send back\" (used for deletes). The endpoint returned 200 with a body. Either change the test to 200, or drop the value from `send back` and add `with status 204`.";
  } else if (actual === 200 && expected === 200) {
    why = "This shouldn't happen — statuses match.";
  } else if (actual === 201 && expected === 201) {
    why = "This shouldn't happen — statuses match.";
  } else if (actual >= 200 && actual < 300 && expected >= 400) {
    why = "The test expected this to fail, but the server accepted it with " + actual + " (success). Either the validation rule you want is missing, or the test data is actually valid.";
  } else {
    why = "The server returned " + actual + " but the test expected " + expected + ". Statuses in the 2xx range mean success, 4xx means the request had a problem, 5xx means the server had a problem.";
  }
  throw new Error(call + " returned " + actual + " (expected " + expected + "). " + why + bodyHint + where);
}

function _expectBodyHas(body, key) {
  if (body && typeof body === "object" && key in body) return;
  const where = _lastCall && _lastCall.line ? " [clear:" + _lastCall.line + "]" : "";
  const call = _lastCall && _lastCall.method ? _lastCall.method + " " + _lastCall.path : "the endpoint";
  const got = body === null || body === undefined ? "nothing" : "{ " + Object.keys(body).slice(0, 5).join(", ") + " }";
  throw new Error(call + " didn't return a \"" + key + "\" field — got " + got + ". Your endpoint's `send back` line needs to include \"" + key + "\"." + where);
}

function _expectSuccess(response) {
  if (response.status >= 200 && response.status < 300) return;
  const where = _lastCall && _lastCall.line ? " [clear:" + _lastCall.line + "]" : "";
  const call = _lastCall && _lastCall.method ? _lastCall.method + " " + _lastCall.path : "the request";
  throw new Error(call + " returned " + response.status + " but the test expected any 2xx success." + where);
}

function _expectFailure(response) {
  if (response.status >= 400) return;
  const where = _lastCall && _lastCall.line ? " [clear:" + _lastCall.line + "]" : "";
  const call = _lastCall && _lastCall.method ? _lastCall.method + " " + _lastCall.path : "the request";
  throw new Error(call + " returned " + response.status + " (success) but the test expected it to fail with a 4xx or 5xx. Add a `validate` or `requires login` rule to the endpoint, or change the test data so the validation actually rejects it." + where);
}

function _expectBodyContains(body, value) {
  const as = JSON.stringify(body);
  if (as && as.includes(value)) return;
  const where = _lastCall && _lastCall.line ? " [clear:" + _lastCall.line + "]" : "";
  const call = _lastCall && _lastCall.method ? _lastCall.method + " " + _lastCall.path : "the endpoint";
  throw new Error(call + " response didn't contain \"" + value + "\". Got: " + (as || "nothing") + "." + where);
}

function _expectBodyLength(body, min) {
  const len = Array.isArray(body) ? body.length : (body && typeof body === "object" ? Object.keys(body).length : 0);
  if (len > min) return;
  const where = _lastCall && _lastCall.line ? " [clear:" + _lastCall.line + "]" : "";
  const call = _lastCall && _lastCall.method ? _lastCall.method + " " + _lastCall.path : "the endpoint";
  throw new Error(call + " returned " + len + " item(s) but the test expected more than " + min + ". Either the endpoint isn't reading from the table you think, or the test data hasn't been created yet." + where);
}

function _expectBodyTruthy(body) {
  if (body) return;
  const where = _lastCall && _lastCall.line ? " [clear:" + _lastCall.line + "]" : "";
  const call = _lastCall && _lastCall.method ? _lastCall.method + " " + _lastCall.path : "the endpoint";
  throw new Error(call + " returned an empty body. Your endpoint should `send back` something." + where);
}

function _expectErrorContains(body, value) {
  const as = JSON.stringify(body);
  if (as && as.includes(value)) return;
  const where = _lastCall && _lastCall.line ? " [clear:" + _lastCall.line + "]" : "";
  throw new Error("Error response didn't mention \"" + value + "\". Got: " + (as || "nothing") + ". Check the `fail with error '...'` or `validate` message in your endpoint." + where);
}

run();