// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"154":3,"165":18,"176":27,"177":27,"180":28,"182":29,"191":31,"192":31,"196":32,"198":33,"200":34,"209":36,"210":36,"213":37,"215":38,"224":40,"225":40,"230":41,"231":41,"232":42} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Companies: name*, industry, website, description, created_at_date (line 18)
//
// ENDPOINTS:
//   GET /api/companies (line 27)
//   GET /api/companies/search (line 31)
//   GET /api/companies/:id (line 36)
//   POST /api/companies (line 40)
//
// DATAFLOW: Client ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    companies: { line: 18, file: "main.clear", fields: { name: { required: true, type: "text" }, industry: { type: "text" }, website: { type: "text" }, description: { type: "text" }, created_at_date: { type: "timestamp" } } },
  },
  endpoints: {
    "GET /api/companies": { line: 27, file: "main.clear", auth: false },
    "GET /api/companies/search": { line: 31, file: "main.clear", auth: false },
    "GET /api/companies/:id": { line: 36, file: "main.clear", auth: false },
    "POST /api/companies": { line: 40, file: "main.clear", auth: false },
  }
} : null;

// clear:3
// Database: local memory (JSON file backup)
//   Company Directory — searchable catalog of company records
//   Tables:   Companies (name, industry, website, description, created_at_date)
//   Endpoints:
//     GET  /api/companies         — list all (public)
//     GET  /api/companies/search  — full-text search on name + industry (public)
//     GET  /api/companies/:id     — single record (public)
//     POST /api/companies         — create / seed (open for test seeding)
//   Star feature: search endpoint uses `search Companies for query_text`
// Data
// clear:18
// Data shape: Companies
const CompaniesSchema = {
  name: { type: "text", required: true },
  industry: { type: "text" },
  website: { type: "text" },
  description: { type: "text" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('companies', CompaniesSchema);
// Backend
// clear:27
// clear:27 — GET /api/companies
app.get('/api/companies', async (req, res) => {
  try {
    // clear:28
    const companies = (await db.findAll('companies', {}, { limit: 50 })).map(_revive);
    // clear:29
    return res.json(companies);
  } catch (err) {
    console.error('[GET /api/companies] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/companies', line: 27, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:31
// clear:31 — GET /api/companies/search
app.get('/api/companies/search', async (req, res) => {
  try {
    const incoming = req.query;
    // clear:32
    let query_text = incoming?.q;
    // clear:33
    let results = (await db.findAll('companies', {})).filter(_r => Object.values(_r).some(_v => String(_v).toLowerCase().includes(String(query_text).toLowerCase()))).slice(0, 100);
    // clear:34
    return res.json(results);
  } catch (err) {
    console.error('[GET /api/companies/search] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/companies/search', line: 31, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:36
// clear:36 — GET /api/companies/:id
app.get('/api/companies/:id', async (req, res) => {
  try {
    // clear:37
    const company = (await db.findAll('companies', {}, { limit: 50 })).map(_revive);
    // clear:38
    return res.json(company);
  } catch (err) {
    console.error('[GET /api/companies/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/companies/:id', line: 36, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:40
// clear:40 — POST /api/companies
app.post('/api/companies', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const company = req.body;
    // clear:41
    const saved = await _clearTry(() => db.insert('companies', _pick(company, CompaniesSchema)), { op: 'insert', table: 'companies', line: 41, file: 'main.clear', source: "" }); // clear:41
    // clear:42
    return res.status(201).json(saved);
  } catch (err) {
    console.error('[POST /api/companies] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/companies', line: 40, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});