// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"273":22,"275":24,"284":33,"285":33,"288":34,"290":34,"299":36,"300":36,"306":37,"308":38,"311":40,"312":40,"313":41} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Orders: amount*, status, created_at_date (line 24)
//
// ENDPOINTS:
//   GET /api/orders (line 33)
//   POST /api/orders [auth] (line 36)
//
// PAGES:
//   'Dashboard' at / (line 45)
//
// DATAFLOW: Frontend ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// Auth scaffolding from `allow signup and login` (clear:31)
//   emits: POST /auth/signup, POST /auth/login, GET /auth/me
//   plus:  requireLogin middleware, requireRole middleware, JWT secret, bcrypt + jwt requires
const _JWT_SECRET = process.env.JWT_SECRET || require('crypto').randomBytes(32).toString('hex');
const _users = [];

// JWT middleware — extracts user from token on every request
app.use((req, res, next) => {
  const authHeader = req.headers.authorization || '';
  if (authHeader.startsWith('Bearer ')) {
    try {
      req.user = jwt.verify(authHeader.slice(7), _JWT_SECRET);
    } catch(e) { req.user = null; }
  }
  next();
});

// POST /auth/signup — create new user
app.post('/auth/signup', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    if (_users.find(u => u.email === email)) return res.status(400).json({ error: 'Email already registered' });
    const password_hash = await bcrypt.hash(password, 10);
    const user = { id: _users.length + 1, email, password_hash, role: 'user', created_at: new Date().toISOString() };
    _users.push(user);
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.status(201).json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// POST /auth/login — authenticate user
app.post('/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    const user = _users.find(u => u.email === email);
    if (!user) return res.status(401).json({ error: 'Invalid email or password' });
    const valid = await bcrypt.compare(password, user.password_hash);
    if (!valid) return res.status(401).json({ error: 'Invalid email or password' });
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// GET /auth/me — return current user
app.get('/auth/me', (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
  const user = _users.find(u => u.id === req.user.id);
  if (!user) return res.status(404).json({ error: 'User not found' });
  res.json({ id: user.id, email: user.email, role: user.role, created_at: user.created_at });
});

// --- Live App Editing routes (Meph edit widget) ---
// Widget is served from a static file in clear-runtime/. API calls
// proxy to Studio (when STUDIO_PORT is set in the environment). In
// a standalone deploy STUDIO_PORT is unset and the API path 503s.
const _MEPH_WIDGET_PATH = require('path').join(__dirname, 'clear-runtime', 'meph-widget.js');
app.get('/__meph__/widget.js', (req, res) => {
  try {
    res.type('application/javascript').send(require('fs').readFileSync(_MEPH_WIDGET_PATH, 'utf8'));
  } catch(e) { res.status(404).send('// widget bundle not found'); }
});
app.all('/__meph__/api/:action', async (req, res) => {
  const studioPort = process.env.STUDIO_PORT;
  if (!studioPort) {
    return res.status(503).json({ error: 'Live editing is not available in this environment (STUDIO_PORT not set)' });
  }
  try {
    const upstream = 'http://localhost:' + studioPort + '/__meph__/api/' + req.params.action;
    const r = await fetch(upstream, {
      method: req.method,
      headers: { 'Content-Type': 'application/json', 'Authorization': req.headers.authorization || '' },
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined : JSON.stringify(req.body || {}),
    });
    const body = await r.text();
    res.status(r.status).type(r.headers.get('content-type') || 'application/json').send(body);
  } catch(e) {
    res.status(502).json({ error: 'Proxy to Studio failed: ' + e.message });
  }
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _validate(body, rules) {
  if (body == null || typeof body !== 'object') return [{ field: '_body', message: 'Request body is required' }];
  const _errs = [];
  for (const r of rules) {
    let v = body[r.field];
    if (r.required && (v == null || v === '')) { _errs.push({ field: r.field, message: r.field + ' is required' }); continue; }
    if (v == null) continue;
    if (r.type === 'number' && typeof v === 'string' && v.trim() !== '' && !isNaN(Number(v))) { body[r.field] = Number(v); v = body[r.field]; }
    if (r.type === 'number' && typeof v !== 'number') { _errs.push({ field: r.field, message: r.field + ' must be a number' }); continue; }
    if (r.type === 'boolean' && typeof v !== 'boolean') { _errs.push({ field: r.field, message: r.field + ' must be true or false' }); continue; }
    if (r.min != null && r.type === 'text' && String(v).length < r.min) _errs.push({ field: r.field, message: r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters') });
    if (r.max != null && r.type === 'text' && String(v).length > r.max) _errs.push({ field: r.field, message: r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters') });
    if (r.min != null && r.type !== 'text' && v < r.min) _errs.push({ field: r.field, message: r.field + ' must be at least ' + r.min });
    if (r.max != null && r.type !== 'text' && v > r.max) _errs.push({ field: r.field, message: r.field + ' must be at most ' + r.max });
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid email' });
    if (r.matches === 'time' && !/^([01]\d|2[0-3]):[0-5]\d$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid time (HH:MM)' });
    if (r.matches === 'phone' && !/^[\+]?[\d\s\-\.\(\)]{7,15}$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid phone number' });
    if (r.matches === 'url' && !/^https?:\/\/.+/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid URL' });
    if (r.oneOf && !r.oneOf.includes(v)) _errs.push({ field: r.field, message: r.field + ' must be one of: ' + r.oneOf.join(', ') });
  }
  return _errs.length ? _errs : null;
}
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    orders: { line: 24, file: "main.clear", fields: { amount: { required: true, type: "number" }, status: { type: "text" }, created_at_date: { type: "timestamp" } } },
  },
  endpoints: {
    "GET /api/orders": { line: 33, file: "main.clear", auth: false },
    "POST /api/orders": { line: 36, file: "main.clear", auth: true },
  }
} : null;

// Metrics Dashboard — orders tracking with 3 charts
// 
//   DATAFLOW:
//   ┌──────────┐   POST /api/orders    ┌──────────┐   save   ┌────────┐
//   │ Browser  │ ─────────────────►    │  Server  │ ──────►  │ Orders │
//   │ (page)   │ ◄─────────────────    │ (Express)│          └────────┘
//   └──────────┘   GET /api/orders     └──────────┘
//        │
//        │  page '/' (login-gated)
//        │  ┌──────────────────────────────────┐
//        │  │ pie chart   — orders by status   │
//        │  │ line chart  — orders over time   │
//        │  │ bar chart   — amount by status   │
//        └──┘──────────────────────────────────┘
// Database
// clear:22
// Database: local memory (JSON file backup)
// clear:24
// Data shape: Orders
const OrdersSchema = {
  amount: { type: "number", required: true },
  status: { type: "text", default: "pending" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('orders', OrdersSchema);
// Backend
// clear:33
// clear:33 — GET /api/orders
app.get('/api/orders', async (req, res) => {
  try {
    // clear:34
    const _resp_34 = (await db.findAll('orders', {}, { limit: 50 })).map(_revive);
    // clear:34
    return res.json(_resp_34);
  } catch (err) {
    console.error('[GET /api/orders] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/orders', line: 33, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:36
// clear:36 — POST /api/orders
app.post('/api/orders', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const order = req.body;
    const incoming = req.params;
    // clear:37
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:38
    const _vErrs = _validate(req.body, [{"field":"amount","type":"number","required":true}]);
    if (_vErrs) return res.status(400).json({ errors: _vErrs });
    // clear:40
    const new_order = await _clearTry(() => db.insert('orders', _pick(order, OrdersSchema)), { op: 'insert', table: 'orders', line: 40, file: 'main.clear', source: "" }); // clear:40
    // clear:41
    return res.status(201).json(new_order);
  } catch (err) {
    console.error('[POST /api/orders] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/orders', line: 36, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// Frontend

const path = require('path');
app.use(express.static(__dirname));
app.get("/", (req, res) => res.sendFile('index.html', { root: __dirname }));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});