// Generated by Clear v1.0
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Projects: name*, status, owner*, priority, created_at_date (line 10)
//   Tasks: title*, project*, assignee, status, created_at_date (line 17)
//
// ENDPOINTS:
//   GET /api/projects (line 29)
//   POST /api/projects (line 33)
//   GET /api/tasks (line 40)
//   POST /api/tasks (line 44)
//
// PAGES:
//   'Team Dashboard' at / (line 53)
//
// DATAFLOW: Frontend ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// Log every request
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const ms = Date.now() - start;
    console.log(`${req.method} ${req.path} ${res.statusCode} ${ms}ms`);
  });
  next();
});
// Allow cross-origin requests
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema)); }
function _validate(body, rules) {
  for (const r of rules) {
    let v = body[r.field];
    if (r.required && (v == null || v === '')) return r.field + ' is required';
    if (v == null) continue;
    if (r.type === 'number' && typeof v === 'string' && v.trim() !== '' && !isNaN(Number(v))) { body[r.field] = Number(v); v = body[r.field]; }
    if (r.type === 'number' && typeof v !== 'number') return r.field + ' must be a number';
    if (r.type === 'boolean' && typeof v !== 'boolean') return r.field + ' must be true or false';
    if (r.min != null && r.type === 'text' && String(v).length < r.min) return r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters');
    if (r.max != null && r.type === 'text' && String(v).length > r.max) return r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters');
    if (r.min != null && r.type !== 'text' && v < r.min) return r.field + ' must be at least ' + r.min;
    if (r.max != null && r.type !== 'text' && v > r.max) return r.field + ' must be at most ' + r.max;
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) return r.field + ' must be a valid email';
    if (r.matches === 'time' && !/^([01]\d|2[0-3]):[0-5]\d$/.test(v)) return r.field + ' must be a valid time (HH:MM)';
    if (r.matches === 'phone' && !/^[\+]?[\d\s\-\.\(\)]{7,15}$/.test(v)) return r.field + ' must be a valid phone number';
    if (r.matches === 'url' && !/^https?:\/\/.+/.test(v)) return r.field + ' must be a valid URL';
    if (r.oneOf && !r.oneOf.includes(v)) return r.field + ' must be one of: ' + r.oneOf.join(', ');
  }
  return null;
}
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  if (!debug) return { status, response: { error: safeMsg } };
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: ctx.line || null,
      clear_file: ctx.file || null,
      clear_source: ctx.source || null,
      hint: hint,
      technical: msg
    }
  };
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    projects: { line: 10, file: "main.clear", fields: { name: { required: true, type: "text" }, status: { type: "text" }, owner: { required: true, type: "text" }, priority: { type: "text" }, created_at_date: { type: "timestamp" } } },
    tasks: { line: 17, file: "main.clear", fields: { title: { required: true, type: "text" }, project: { required: true, type: "text" }, assignee: { type: "text" }, status: { type: "text" }, created_at_date: { type: "timestamp" } } },
  },
  endpoints: {
    "GET /api/projects": { line: 29, file: "main.clear", auth: false },
    "POST /api/projects": { line: 33, file: "main.clear", auth: false },
    "GET /api/tasks": { line: 40, file: "main.clear", auth: false },
    "POST /api/tasks": { line: 44, file: "main.clear", auth: false },
  }
} : null;

// Team Dashboard -- project and task management with sidebar layout
// Database
// clear:8
// Database: local memory (JSON file backup)
// clear:10
// Data shape: Projects
const ProjectsSchema = {
  name: { type: "text", required: true },
  status: { type: "text", default: "active" },
  owner: { type: "text", required: true },
  priority: { type: "text", default: "medium" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('projects', ProjectsSchema);
// clear:17
// Data shape: Tasks
const TasksSchema = {
  title: { type: "text", required: true },
  project: { type: "text", required: true },
  assignee: { type: "text" },
  status: { type: "text", default: "todo" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('tasks', TasksSchema);
// Backend
// clear:29
// clear:29 — GET /api/projects
app.get('/api/projects', async (req, res) => {
  try {
    const all_projects = await db.findAll('projects');
    return res.json(all_projects);
  } catch (err) {
    console.error('[GET /api/projects] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/projects', line: 29, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:33
// clear:33 — POST /api/projects
app.post('/api/projects', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const project_data = req.body;
    const incoming = req.params;
    const _vErr = _validate(req.body, [{"field":"name","type":"text","required":true,"min":1,"max":100}, {"field":"owner","type":"text","required":true}]);
    if (_vErr) return res.status(400).json({ error: _vErr });
    const new_project = await _clearTry(() => db.insert('projects', _pick(project_data, ProjectsSchema)), { op: 'insert', table: 'projects', line: 37, file: 'main.clear', source: "" }); // clear:37
    return res.status(201).json({ ...new_project, message: "success" });
  } catch (err) {
    console.error('[POST /api/projects] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/projects', line: 33, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:40
// clear:40 — GET /api/tasks
app.get('/api/tasks', async (req, res) => {
  try {
    const all_tasks = await db.findAll('tasks');
    return res.json(all_tasks);
  } catch (err) {
    console.error('[GET /api/tasks] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/tasks', line: 40, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:44
// clear:44 — POST /api/tasks
app.post('/api/tasks', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const task_data = req.body;
    const incoming = req.params;
    const _vErr = _validate(req.body, [{"field":"title","type":"text","required":true,"min":1,"max":200}, {"field":"project","type":"text","required":true}]);
    if (_vErr) return res.status(400).json({ error: _vErr });
    const new_task = await _clearTry(() => db.insert('tasks', _pick(task_data, TasksSchema)), { op: 'insert', table: 'tasks', line: 48, file: 'main.clear', source: "" }); // clear:48
    return res.status(201).json({ ...new_task, message: "success" });
  } catch (err) {
    console.error('[POST /api/tasks] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/tasks', line: 44, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// Frontend

const path = require('path');
app.use(express.static(__dirname));
app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});