#!/usr/bin/env node
// E2E tests -- auto-generated by Clear compiler
// Run: node test.js
// Requires: server running on localhost:3000

const BASE = process.env.TEST_URL || "http://localhost:3000";
let passed = 0, failed = 0;
let _emailCounter = 0;
let _uniqueCounter = 0;
function _uniqueEmail() { return "test" + (++_emailCounter) + "@example.com"; }
function _uniqueText(base) { return base + "_" + (++_uniqueCounter); }

// Note: for clean re-runs, delete clear-data.json before starting the server
// unique constraints may cause 500s if stale data exists from a previous run

async function test(name, fn) {
  try {
    await fn();
    passed++;
    console.log("PASS:", name);
  } catch (err) {
    failed++;
    console.log("FAIL:", name, "-", err.message);
  }
}

function assert(condition, msg) { if (!condition) throw new Error(msg); }

async function run() {
  await test("GET /api/projects returns 200", async () => {
    const r = await fetch(BASE + "/api/projects");
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("GET /api/tasks returns 200", async () => {
    const r = await fetch(BASE + "/api/tasks");
    assert(r.status === 200, "Expected 200, got " + r.status);
  });

  await test("POST /api/projects with valid data returns 201", async () => {
    const payload = {"name":"Test value","owner":"Test value"};
    payload["name"] = _uniqueText("name");
    payload["owner"] = _uniqueText("owner");
    const r = await fetch(BASE + "/api/projects", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.id, "Response should have an id");
  });

  await test("POST /api/projects with no body returns 400", async () => {
    const r = await fetch(BASE + "/api/projects", { method: "POST" });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/projects with empty required field returns 400", async () => {
    const r = await fetch(BASE + "/api/projects", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: "" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/tasks with valid data returns 201", async () => {
    const payload = {"title":"Test value","project":"Test value"};
    payload["title"] = _uniqueText("title");
    payload["project"] = _uniqueText("project");
    const r = await fetch(BASE + "/api/tasks", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.id, "Response should have an id");
  });

  await test("POST /api/tasks with no body returns 400", async () => {
    const r = await fetch(BASE + "/api/tasks", { method: "POST" });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/tasks with empty required field returns 400", async () => {
    const r = await fetch(BASE + "/api/tasks", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/projects with name over max length returns 400", async () => {
    const r = await fetch(BASE + "/api/projects", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/tasks with title over max length returns 400", async () => {
    const r = await fetch(BASE + "/api/tasks", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" })
    });
    assert(r.status === 400, "Expected 400, got " + r.status);
  });

  await test("POST /api/projects strips unknown fields (mass assignment protection)", async () => {
    const payload = { ...{"name":"Test value","owner":"Test value"}, admin: true, role: "superuser" };
    payload["name"] = _uniqueText("name");
    payload["owner"] = _uniqueText("owner");
    const r = await fetch(BASE + "/api/projects", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });
    assert(r.status === 201, "Expected 201, got " + r.status);
    const data = await r.json();
    assert(data.admin === undefined, "admin field should have been stripped");
    assert(data.role === undefined, "role field should have been stripped");
  });

  await test("GET /api/projects returns created records after POST", async () => {
    const r = await fetch(BASE + "/api/projects");
    const data = await r.json();
    assert(Array.isArray(data), "Expected array");
    assert(data.length > 0, "Expected at least one record (from earlier POST test)");
  });

  await test("GET / serves HTML", async () => {
    const r = await fetch(BASE + "/");
    assert(r.status === 200, "Expected 200, got " + r.status);
    const html = await r.text();
    assert(html.includes("<!DOCTYPE html>"), "Expected HTML document");
  });

  console.log("");
  console.log("Results:", passed, "passed,", failed, "failed");
  process.exit(failed > 0 ? 1 : 0);
}

run();