// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"256":3,"258":5,"266":10,"275":18,"276":18,"279":19,"281":19,"290":21,"291":21,"294":22,"296":23,"305":25,"306":25,"310":26,"312":26,"321":28,"322":28,"327":29,"329":30,"330":30,"331":31,"341":33,"342":33,"347":34,"349":35,"352":35,"354":36,"364":38,"365":38,"368":39,"370":40,"371":40,"372":41,"382":44,"383":44,"386":45,"388":45,"397":47,"398":47,"402":48,"404":48,"413":50,"414":50,"419":51,"421":52,"422":52,"423":53,"433":55,"434":55,"439":56,"441":57,"444":57,"446":58,"456":60,"457":60,"460":61,"462":62,"463":62,"464":63} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Customers: name*, company*, status (line 5)
//   OnboardingSteps: customer_id*, step_name*, completed (line 10)
//
// ENDPOINTS:
//   GET /api/customers (line 18)
//   GET /api/customers/onboarding (line 21)
//   GET /api/customers/:id (line 25)
//   POST /api/customers [auth] (line 28)
//   PUT /api/customers/:id [auth] (line 33)
//   DELETE /api/customers/:id [auth] (line 38)
//   GET /api/steps (line 44)
//   GET /api/steps/:id (line 47)
//   POST /api/steps [auth] (line 50)
//   PUT /api/steps/:id [auth] (line 55)
//   DELETE /api/steps/:id [auth] (line 60)
//
// PAGES:
//   'Onboarding Tracker' at / (line 66)
//
// DATAFLOW: Frontend ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// Auth scaffolding from `allow signup and login` (clear:15)
//   emits: POST /auth/signup, POST /auth/login, GET /auth/me
//   plus:  requireLogin middleware, requireRole middleware, JWT secret, bcrypt + jwt requires
const _JWT_SECRET = process.env.JWT_SECRET || require('crypto').randomBytes(32).toString('hex');
const _users = [];

// JWT middleware — extracts user from token on every request
app.use((req, res, next) => {
  const authHeader = req.headers.authorization || '';
  if (authHeader.startsWith('Bearer ')) {
    try {
      req.user = jwt.verify(authHeader.slice(7), _JWT_SECRET);
    } catch(e) { req.user = null; }
  }
  next();
});

// POST /auth/signup — create new user
app.post('/auth/signup', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    if (_users.find(u => u.email === email)) return res.status(400).json({ error: 'Email already registered' });
    const password_hash = await bcrypt.hash(password, 10);
    const user = { id: _users.length + 1, email, password_hash, role: 'user', created_at: new Date().toISOString() };
    _users.push(user);
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.status(201).json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// POST /auth/login — authenticate user
app.post('/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    const user = _users.find(u => u.email === email);
    if (!user) return res.status(401).json({ error: 'Invalid email or password' });
    const valid = await bcrypt.compare(password, user.password_hash);
    if (!valid) return res.status(401).json({ error: 'Invalid email or password' });
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// GET /auth/me — return current user
app.get('/auth/me', (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
  const user = _users.find(u => u.id === req.user.id);
  if (!user) return res.status(404).json({ error: 'User not found' });
  res.json({ id: user.id, email: user.email, role: user.role, created_at: user.created_at });
});

// --- Live App Editing routes (Meph edit widget) ---
// Widget is served from a static file in clear-runtime/. API calls
// proxy to Studio (when STUDIO_PORT is set in the environment). In
// a standalone deploy STUDIO_PORT is unset and the API path 503s.
const _MEPH_WIDGET_PATH = require('path').join(__dirname, 'clear-runtime', 'meph-widget.js');
app.get('/__meph__/widget.js', (req, res) => {
  try {
    res.type('application/javascript').send(require('fs').readFileSync(_MEPH_WIDGET_PATH, 'utf8'));
  } catch(e) { res.status(404).send('// widget bundle not found'); }
});
app.all('/__meph__/api/:action', async (req, res) => {
  const studioPort = process.env.STUDIO_PORT;
  if (!studioPort) {
    return res.status(503).json({ error: 'Live editing is not available in this environment (STUDIO_PORT not set)' });
  }
  try {
    const upstream = 'http://localhost:' + studioPort + '/__meph__/api/' + req.params.action;
    const r = await fetch(upstream, {
      method: req.method,
      headers: { 'Content-Type': 'application/json', 'Authorization': req.headers.authorization || '' },
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined : JSON.stringify(req.body || {}),
    });
    const body = await r.text();
    res.status(r.status).type(r.headers.get('content-type') || 'application/json').send(body);
  } catch(e) {
    res.status(502).json({ error: 'Proxy to Studio failed: ' + e.message });
  }
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    customers: { line: 5, file: "main.clear", fields: { name: { required: true, type: "text" }, company: { required: true, type: "text" }, status: { type: "text" } } },
    onboardingsteps: { line: 10, file: "main.clear", fields: { customer_id: { required: true, type: "fk" }, step_name: { required: true, type: "text" }, completed: { type: "boolean" } } },
  },
  endpoints: {
    "GET /api/customers": { line: 18, file: "main.clear", auth: false },
    "GET /api/customers/onboarding": { line: 21, file: "main.clear", auth: false },
    "GET /api/customers/:id": { line: 25, file: "main.clear", auth: false },
    "POST /api/customers": { line: 28, file: "main.clear", auth: true },
    "PUT /api/customers/:id": { line: 33, file: "main.clear", auth: true },
    "DELETE /api/customers/:id": { line: 38, file: "main.clear", auth: true },
    "GET /api/steps": { line: 44, file: "main.clear", auth: false },
    "GET /api/steps/:id": { line: 47, file: "main.clear", auth: false },
    "POST /api/steps": { line: 50, file: "main.clear", auth: true },
    "PUT /api/steps/:id": { line: 55, file: "main.clear", auth: true },
    "DELETE /api/steps/:id": { line: 60, file: "main.clear", auth: true },
  }
} : null;

// clear:3
// Database: local memory (JSON file backup)
// clear:5
// Data shape: Customers
const CustomersSchema = {
  name: { type: "text", required: true },
  company: { type: "text", required: true },
  status: { type: "text", default: "onboarding" }
};
db.createTable('customers', CustomersSchema);
// clear:10
// Data shape: OnboardingSteps
const OnboardingStepsSchema = {
  customer_id: { type: "fk", required: true },
  step_name: { type: "text", required: true },
  completed: { type: "boolean", default: false }
};
db.createTable('onboardingsteps', OnboardingStepsSchema);
// Customer endpoints — specific paths before parameterized ones
// clear:18
// clear:18 — GET /api/customers
app.get('/api/customers', async (req, res) => {
  try {
    // clear:19
    const _resp_19 = (await db.findAll('customers', {}, { limit: 50 })).map(_revive);
    // clear:19
    return res.json(_resp_19);
  } catch (err) {
    console.error('[GET /api/customers] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/customers', line: 18, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:21
// clear:21 — GET /api/customers/onboarding
app.get('/api/customers/onboarding', async (req, res) => {
  try {
    // clear:22
    const customers = (await db.findAll('customers', {}, { limit: 50 })).map(_revive);
    // clear:23
    return res.json(customers);
  } catch (err) {
    console.error('[GET /api/customers/onboarding] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/customers/onboarding', line: 21, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:25
// clear:25 — GET /api/customers/:id
app.get('/api/customers/:id', async (req, res) => {
  try {
    const incoming = req.params;
    // clear:26
    const _resp_26 = _revive(await db.findOne('customers', { id: incoming?.id }));
    // clear:26
    return res.json(_resp_26);
  } catch (err) {
    console.error('[GET /api/customers/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/customers/:id', line: 25, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:28
// clear:28 — POST /api/customers
app.post('/api/customers', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const customer = req.body;
    // clear:29
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:30
    const saved = await _clearTry(() => db.insert('customers', _pick(customer, CustomersSchema)), { op: 'insert', table: 'customers', line: 30, file: 'main.clear', source: "" }); // clear:30
    // clear:31
    return res.status(201).json(saved);
  } catch (err) {
    console.error('[POST /api/customers] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/customers', line: 28, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:33
// clear:33 — PUT /api/customers/:id
app.put('/api/customers/:id', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const changes = req.body;
    // clear:34
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:35
    const _picked_changes = _pick(changes, CustomersSchema);
    _picked_changes.id = req.params.id;
    await _clearTry(() => db.update('customers', _picked_changes), { op: 'update', table: 'customers', line: 35, file: 'main.clear', source: "" }); // clear:35
    Object.assign(changes, await db.findOne('customers', { id: _picked_changes.id }) || {});
    // clear:36
    return res.json(changes);
  } catch (err) {
    console.error('[PUT /api/customers/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'PUT /api/customers/:id', line: 33, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:38
// clear:38 — DELETE /api/customers/:id
app.delete('/api/customers/:id', async (req, res) => {
  try {
    // clear:39
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:40
    await _clearTry(() => db.remove('customers', { id: req.params.id }), { op: 'remove', table: 'customers', line: 40, file: 'main.clear', source: "" }); // clear:40
    // clear:41
    return res.json({ message: "deleted" });
  } catch (err) {
    console.error('[DELETE /api/customers/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'DELETE /api/customers/:id', line: 38, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// OnboardingStep endpoints
// clear:44
// clear:44 — GET /api/steps
app.get('/api/steps', async (req, res) => {
  try {
    // clear:45
    const _resp_45 = (await db.findAll('onboardingsteps', {}, { limit: 50 })).map(_revive);
    // clear:45
    return res.json(_resp_45);
  } catch (err) {
    console.error('[GET /api/steps] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/steps', line: 44, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:47
// clear:47 — GET /api/steps/:id
app.get('/api/steps/:id', async (req, res) => {
  try {
    const incoming = req.params;
    // clear:48
    const _resp_48 = _revive(await db.findOne('onboardingsteps', { id: incoming?.id }));
    // clear:48
    return res.json(_resp_48);
  } catch (err) {
    console.error('[GET /api/steps/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/steps/:id', line: 47, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:50
// clear:50 — POST /api/steps
app.post('/api/steps', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const step = req.body;
    // clear:51
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:52
    const saved = await _clearTry(() => db.insert('onboardingsteps', _pick(step, OnboardingStepsSchema)), { op: 'insert', table: 'onboardingsteps', line: 52, file: 'main.clear', source: "" }); // clear:52
    // clear:53
    return res.status(201).json(saved);
  } catch (err) {
    console.error('[POST /api/steps] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/steps', line: 50, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:55
// clear:55 — PUT /api/steps/:id
app.put('/api/steps/:id', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const changes = req.body;
    // clear:56
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:57
    const _picked_changes = _pick(changes, OnboardingStepsSchema);
    _picked_changes.id = req.params.id;
    await _clearTry(() => db.update('onboardingsteps', _picked_changes), { op: 'update', table: 'onboardingsteps', line: 57, file: 'main.clear', source: "" }); // clear:57
    Object.assign(changes, await db.findOne('onboardingsteps', { id: _picked_changes.id }) || {});
    // clear:58
    return res.json(changes);
  } catch (err) {
    console.error('[PUT /api/steps/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'PUT /api/steps/:id', line: 55, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:60
// clear:60 — DELETE /api/steps/:id
app.delete('/api/steps/:id', async (req, res) => {
  try {
    // clear:61
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:62
    await _clearTry(() => db.remove('onboardingsteps', { id: req.params.id }), { op: 'remove', table: 'onboardingsteps', line: 62, file: 'main.clear', source: "" }); // clear:62
    // clear:63
    return res.json({ message: "deleted" });
  } catch (err) {
    console.error('[DELETE /api/steps/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'DELETE /api/steps/:id', line: 60, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// Frontend

const path = require('path');
app.use(express.static(__dirname));
app.get("/", (req, res) => res.sendFile('index.html', { root: __dirname }));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});