// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"436":33,"439":37,"455":57,"456":57,"459":58,"461":58,"470":60,"471":60,"474":61,"476":61,"485":63,"486":63,"492":64,"494":65,"496":66,"498":67,"500":68,"502":69,"505":34,"506":34,"514":78,"515":78,"516":79,"526":81,"527":81,"532":82,"534":83,"537":83,"539":84,"550":88,"551":88,"559":89,"561":97,"562":97,"563":98,"565":106,"566":106,"567":107,"569":115,"570":115,"571":116,"573":124,"574":124,"575":125,"591":286,"593":287,"600":288,"602":289,"607":291,"609":292,"616":293,"621":295,"623":296,"630":297,"635":299,"637":300} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Leads: name*, email*, company, size, source, assigned_to, status, created_at_date (line 37)
//
// ENDPOINTS:
//   GET /api/leads (line 57)
//   GET /api/leads/new (line 60)
//   POST /api/leads [auth] (line 63)
//   PUT /api/leads/:id [auth] (line 81)
//   POST /api/seed (line 88)
//
// PAGES:
//   'Lead Router' at / (line 129)
//   'Routing rules' at /routing-rules (line 202)
//   'Owners' at /owners (line 235)
//
// DATAFLOW: Frontend ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// CF-1: runtime instrumentation — fire-and-forget beacons to the Compiler Flywheel.
const _CLEAR_FLYWHEEL_URL = process.env.CLEAR_FLYWHEEL_URL;
const _CLEAR_COMPILE_ROW_ID = process.env.CLEAR_COMPILE_ROW_ID;
function _clearBeacon(event) {
  if (!_CLEAR_FLYWHEEL_URL || !_CLEAR_COMPILE_ROW_ID) return;
  try {
    fetch(_CLEAR_FLYWHEEL_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(Object.assign({ compile_row_id: _CLEAR_COMPILE_ROW_ID, ts: Date.now() }, event)),
      signal: AbortSignal.timeout(500),
    }).catch(() => {});
  } catch {}
}
app.use((req, res, next) => {
  const _t0 = Date.now();
  res.on('finish', () => {
    _clearBeacon({ event_type: 'endpoint_latency', method: req.method, path: req.route ? req.route.path : req.path, status: res.statusCode, duration_ms: Date.now() - _t0 });
  });
  next();
});
app.use((err, req, res, next) => {
  _clearBeacon({ event_type: 'endpoint_error', method: req.method, path: req.path, error_sig: (err && err.message ? String(err.message).substring(0, 200) : 'unknown') });
  next(err);
});
// Log every request
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const ms = Date.now() - start;
    console.log(`${req.method} ${req.path} ${res.statusCode} ${ms}ms`);
  });
  next();
});
// Allow cross-origin requests
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});
// Auth scaffolding from `allow signup and login` (clear:52)
//   emits: POST /auth/signup, POST /auth/login, GET /auth/me
//   plus:  requireLogin middleware, requireRole middleware, JWT secret, bcrypt + jwt requires
const _JWT_SECRET = process.env.JWT_SECRET || require('crypto').randomBytes(32).toString('hex');
db.createTable('_auth_users', { email: { type: 'text', required: true, unique: true }, password_hash: { type: 'text', required: true }, role: { type: 'text' }, created_at: { type: 'text' } });
db.createTable('audit_log', { ts: { type: 'text' }, user_id: { type: 'number' }, user_email: { type: 'text' }, method: { type: 'text' }, path: { type: 'text' }, status: { type: 'number' }, body_summary: { type: 'text' } });

// JWT middleware — extracts user from token on every request
app.use((req, res, next) => {
  const authHeader = req.headers.authorization || '';
  if (authHeader.startsWith('Bearer ')) {
    try {
      req.user = jwt.verify(authHeader.slice(7), _JWT_SECRET);
    } catch(e) { req.user = null; }
  }
  next();
});

// API-call audit middleware — captures every state-change to the
// audit_log table. Runs AFTER the JWT middleware so req.user is
// populated when available; runs BEFORE routes so every state-
// changing request (POST/PUT/PATCH/DELETE) is logged regardless of
// where it lands. The db.insert is fire-and-forget — the response
// already shipped, so insert latency doesn't add to user-visible time.
function _sanitizeAuditBody(body) {
  if (body === null || body === undefined) return null;
  if (typeof body !== 'object') return String(body).slice(0, 1024);
  const sensitive = /password|token|secret|api[_-]?key|jwt|auth/i;
  const cleaned = {};
  for (const k in body) {
    if (!Object.prototype.hasOwnProperty.call(body, k)) continue;
    if (sensitive.test(k)) { cleaned[k] = '[redacted]'; continue; }
    const v = body[k];
    if (v === null || typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
      cleaned[k] = v;
    } else {
      try { cleaned[k] = JSON.stringify(v).slice(0, 200); } catch { cleaned[k] = '[unserializable]'; }
    }
  }
  try { return JSON.stringify(cleaned).slice(0, 1024); } catch { return '[unserializable-body]'; }
}
app.use((req, res, next) => {
  if (req.method === 'GET' || req.method === 'HEAD' || req.method === 'OPTIONS') return next();
  if (req.path && req.path.startsWith('/__meph__')) return next();
  const _audit_started_at = new Date().toISOString();
  const _audit_body = _sanitizeAuditBody(req.body);
  res.on('finish', () => {
    Promise.resolve(db.insert('audit_log', {
      ts: _audit_started_at,
      user_id: req.user ? req.user.id : null,
      user_email: req.user ? req.user.email : null,
      tenant_id: req.user ? (req.user.tenant_id !== undefined ? req.user.tenant_id : null) : null,
      method: req.method,
      path: req.path,
      status: res.statusCode,
      body_summary: _audit_body,
    })).catch(e => { console.error('[clear:audit] insert failed:', e.message); });
  });
  next();
});

// GET /audit — list audit entries the caller is allowed to see.
// Tenant-scoped when shared scope is on (caller sees only their
// tenant); whole log otherwise. Authentication required so the
// log isn't a public-facing data leak. Reads from the durable
// audit_log table so a process restart doesn't wipe history.
app.get('/audit', async (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
  try {
    const rows = await db.findAll('audit_log');
    res.json(rows);
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// GET /audit.csv — same data as /audit but in CSV format. SOC 2
// evidence collectors and most compliance tools ingest CSV more
// naturally than JSON. Same auth + tenant scoping as /audit.
// Quote-escape every value to handle body_summary text that may
// contain commas, quotes, or newlines.
function _csvEscape(value) {
  if (value === null || value === undefined) return '';
  const str = String(value);
  if (/[",\n\r]/.test(str)) return '"' + str.replace(/"/g, '""') + '"';
  return str;
}
app.get('/audit.csv', async (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
  try {
    const rows = await db.findAll('audit_log');
    const cols = ['id', 'ts', 'user_id', 'user_email', 'tenant_id', 'method', 'path', 'status', 'body_summary'];
    const header = cols.join(',');
    const body = rows.map(r => cols.map(c => _csvEscape(r[c])).join(',')).join('\n');
    res.set('Content-Type', 'text/csv; charset=utf-8');
    res.set('Content-Disposition', 'attachment; filename="audit.csv"');
    res.send(header + '\n' + body + (body ? '\n' : ''));
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// POST /auth/signup — create new user
app.post('/auth/signup', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    const _existing = await db.findOne('_auth_users', { email });
    if (_existing) return res.status(400).json({ error: 'Email already registered' });
    const password_hash = await bcrypt.hash(password, 10);
    const _user_record = { email, password_hash, role: 'user', created_at: new Date().toISOString() };
    let user = await db.insert('_auth_users', _user_record);
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.status(201).json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// POST /auth/login — authenticate user
app.post('/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    const user = await db.findOne('_auth_users', { email });
    if (!user) return res.status(401).json({ error: 'Invalid email or password' });
    const valid = await bcrypt.compare(password, user.password_hash);
    if (!valid) return res.status(401).json({ error: 'Invalid email or password' });
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// GET /auth/me — return current user
app.get('/auth/me', async (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
  try {
    const user = await db.findOne('_auth_users', { id: req.user.id });
    if (!user) return res.status(404).json({ error: 'User not found' });
    res.json({ id: user.id, email: user.email, role: user.role, created_at: user.created_at });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// --- Live App Editing routes (Meph edit widget) ---
// Widget is served from a static file in clear-runtime/. API calls
// proxy to Studio (when STUDIO_PORT is set in the environment). In
// a standalone deploy STUDIO_PORT is unset and the API path 503s.
const _MEPH_WIDGET_PATH = require('path').join(__dirname, 'clear-runtime', 'meph-widget.js');
app.get('/__meph__/widget.js', (req, res) => {
  try {
    res.type('application/javascript').send(require('fs').readFileSync(_MEPH_WIDGET_PATH, 'utf8'));
  } catch(e) { res.status(404).send('// widget bundle not found'); }
});
app.all('/__meph__/api/:action', async (req, res) => {
  const studioPort = process.env.STUDIO_PORT;
  if (!studioPort) {
    return res.status(503).json({ error: 'Live editing is not available in this environment (STUDIO_PORT not set)' });
  }
  try {
    const upstream = 'http://localhost:' + studioPort + '/__meph__/api/' + req.params.action;
    const r = await fetch(upstream, {
      method: req.method,
      headers: { 'Content-Type': 'application/json', 'Authorization': req.headers.authorization || '' },
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined : JSON.stringify(req.body || {}),
    });
    const body = await r.text();
    res.status(r.status).type(r.headers.get('content-type') || 'application/json').send(body);
  } catch(e) {
    res.status(502).json({ error: 'Proxy to Studio failed: ' + e.message });
  }
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _validate(body, rules) {
  if (body == null || typeof body !== 'object') return [{ field: '_body', message: 'Request body is required' }];
  const _errs = [];
  for (const r of rules) {
    let v = body[r.field];
    if (r.required && (v == null || v === '')) { _errs.push({ field: r.field, message: r.field + ' is required' }); continue; }
    if (v == null) continue;
    if (r.type === 'number' && typeof v === 'string' && v.trim() !== '' && !isNaN(Number(v))) { body[r.field] = Number(v); v = body[r.field]; }
    if (r.type === 'number' && typeof v !== 'number') { _errs.push({ field: r.field, message: r.field + ' must be a number' }); continue; }
    if (r.type === 'boolean' && typeof v !== 'boolean') { _errs.push({ field: r.field, message: r.field + ' must be true or false' }); continue; }
    if (r.min != null && r.type === 'text' && String(v).length < r.min) _errs.push({ field: r.field, message: r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters') });
    if (r.max != null && r.type === 'text' && String(v).length > r.max) _errs.push({ field: r.field, message: r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters') });
    if (r.min != null && r.type !== 'text' && v < r.min) _errs.push({ field: r.field, message: r.field + ' must be at least ' + r.min });
    if (r.max != null && r.type !== 'text' && v > r.max) _errs.push({ field: r.field, message: r.field + ' must be at most ' + r.max });
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid email' });
    if (r.matches === 'time' && !/^([01]\d|2[0-3]):[0-5]\d$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid time (HH:MM)' });
    if (r.matches === 'phone' && !/^[\+]?[\d\s\-\.\(\)]{7,15}$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid phone number' });
    if (r.matches === 'url' && !/^https?:\/\/.+/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid URL' });
    if (r.oneOf && !r.oneOf.includes(v)) _errs.push({ field: r.field, message: r.field + ' must be one of: ' + r.oneOf.join(', ') });
  }
  return _errs.length ? _errs : null;
}
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  // Concurrency Phase 2: a VERSION_CONFLICT from updateWithVersion
  // surfaces as 409 with the original message (not "Something went
  // wrong") so clients can retry against the live row. Plan:
  // plans/plan-concurrency-proofs-2026-05-02.md.
  if (err && err.code === 'VERSION_CONFLICT') {
    return {
      status: 409,
      response: {
        error: err.message || 'version conflict',
        code: 'VERSION_CONFLICT',
        expectedVersion: err.expectedVersion,
        currentVersion: err.currentVersion,
        hint: 'Another request modified this record after you read it. Re-read the record and retry the save.',
      },
    };
  }
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    leads: { line: 37, file: "main.clear", fields: { name: { required: true, type: "text" }, email: { required: true, type: "text" }, company: { type: "text" }, size: { type: "text" }, source: { type: "text" }, assigned_to: { type: "text" }, status: { type: "text" }, created_at_date: { type: "timestamp" } } },
  },
  endpoints: {
    "GET /api/leads": { line: 57, file: "main.clear", auth: false },
    "GET /api/leads/new": { line: 60, file: "main.clear", auth: false },
    "POST /api/leads": { line: 63, file: "main.clear", auth: true },
    "PUT /api/leads/:id": { line: 81, file: "main.clear", auth: true },
    "POST /api/seed": { line: 88, file: "main.clear", auth: false },
  }
} : null;

// Lead Router - sales intake workbench
//
// LAYOUT:
// +-------------+----------------------------------------------+
// | Sidebar     | Top bar                                      |
// | - New queue +----------------------------------------------+
// | - Routing   | Page header                                  |
// | - Owners    | Stats: new leads, owners, rules              |
// |             | Intake form                                  |
// |             | Lead table + selected lead detail panel      |
// +-------------+----------------------------------------------+
//
// Lead Router — intake form, apply rules, assign to owner
//
//   ┌──────────┐  submit   ┌──────────┐   rules    ┌──────────┐
//   │ Prospect │ ────────► │  Server  │ ─────────► │  Leads   │
//   └──────────┘           └──────────┘            └──────────┘
//                                │                      │
//                                │ route by size        │
//                                ▼                      │
//                         SMB → Alice                   │
//                         Mid → Bob                     │
//                         Enterprise → Charlie          │
//                                                       │
//                           ┌──────────┐                │
//                           │   Ops    │ ◄──────────────┘
//                           │   View   │
//                           └──────────┘
// clear:33
// Database: local memory (JSON file backup)
// Database
// clear:37
// Data shape: Leads
const LeadsSchema = {
  name: { type: "text", required: true },
  email: { type: "text", required: true },
  company: { type: "text" },
  size: { type: "text", default: "SMB" },
  source: { type: "text" },
  assigned_to: { type: "text" },
  status: { type: "text", default: "new" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('leads', LeadsSchema);
// Backend
// # Middleware
// # Endpoints
// clear:57
// clear:57 — GET /api/leads
app.get('/api/leads', async (req, res) => {
  try {
    // clear:58
    const _resp_58 = (await db.findAll('leads', {}, { limit: 50 })).map(_revive);
    // clear:58
    return res.json(_resp_58);
  } catch (err) {
    console.error('[GET /api/leads] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/leads', line: 57, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:60
// clear:60 — GET /api/leads/new
app.get('/api/leads/new', async (req, res) => {
  try {
    // clear:61
    const _resp_61 = (await db.findAll('leads', { status: "new" }, { limit: 50 })).map(_revive);
    // clear:61
    return res.json(_resp_61);
  } catch (err) {
    console.error('[GET /api/leads/new] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/leads/new', line: 60, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:63
// clear:63 — POST /api/leads
app.post('/api/leads', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const lead = req.body;
    const incoming = req.params;
    // clear:64
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:65
    // rule: lead-must-have-name (line 65)
    // clear:66
    if (!(lead?.name != "")) { return res.status(403).json({ error: "Every lead needs a name field — leads without names cannot be routed", rule: "lead-must-have-name" }); }
    // clear:67
    // rule: lead-must-have-email (line 67)
    // clear:68
    if (!(lead?.email != "")) { return res.status(403).json({ error: "Every lead needs an email address — leads without emails cannot be contacted", rule: "lead-must-have-email" }); }
    // clear:69
    const _vErrs = _validate(req.body, [{"field":"name","type":"text","required":true,"min":1,"max":100}, {"field":"email","type":"text","required":true}, {"field":"size","type":"text"}]);
    if (_vErrs) return res.status(400).json({ errors: _vErrs });
    // clear:34
    // clear:34 — route lead by size
    {
      const _v = lead.size;
      if (_v === "SMB") lead.assigned_to = "alice";
      else if (_v === "Mid-market") lead.assigned_to = "bob";
      else if (_v === "Enterprise") lead.assigned_to = "charlie";
      else lead.assigned_to = "alice";
    }
    // clear:78
    const new_lead = await _clearTry(() => db.insert('leads', _pick(lead, LeadsSchema)), { op: 'insert', table: 'leads', line: 78, file: 'main.clear', source: "" }); // clear:78
    // clear:79
    return res.status(201).json({ ...new_lead, message: "success" });
  } catch (err) {
    console.error('[POST /api/leads] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/leads', line: 63, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:81
// clear:81 — PUT /api/leads/:id
app.put('/api/leads/:id', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const lead = req.body;
    // clear:82
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:83
    const _picked_lead = _pick(lead, LeadsSchema);
    _picked_lead.id = req.params.id;
    await _clearTry(() => db.update('leads', _picked_lead), { op: 'update', table: 'leads', line: 83, file: 'main.clear', source: "" }); // clear:83
    Object.assign(lead, await db.findOne('leads', { id: _picked_lead.id }) || {});
    // clear:84
    return res.status(200).json({ message: "updated" });
  } catch (err) {
    console.error('[PUT /api/leads/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'PUT /api/leads/:id', line: 81, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// # Seed Data
// clear:88
// clear:88 — POST /api/seed
app.post('/api/seed', async (req, res) => {
  try {
    if (process.env.NODE_ENV === 'production') return res.status(403).json({ error: 'Seed endpoint is disabled in production' });
    const _existing = await db.findAll('leads');
    if (_existing.length > 0) return res.json({ message: 'already seeded' });
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const seed = req.body;
    // clear:89
    let l1 = { name: "Priya Shah", email: "priya@acmecorp.com", company: "Acme Corp", size: "Enterprise", source: "webinar", assigned_to: "charlie", status: "new" };
    // clear:97
    l1 = await _clearTry(() => db.insert('leads', _pick(l1, LeadsSchema)), { op: 'insert', table: 'leads', line: 97, file: 'main.clear', source: "" }); // clear:97
    // clear:98
    let l2 = { name: "Marcus Jones", email: "mj@shopify-shops.com", company: "Shopify Shops", size: "Mid-market", source: "content", assigned_to: "bob", status: "new" };
    // clear:106
    l2 = await _clearTry(() => db.insert('leads', _pick(l2, LeadsSchema)), { op: 'insert', table: 'leads', line: 106, file: 'main.clear', source: "" }); // clear:106
    // clear:107
    let l3 = { name: "Jenna Liu", email: "jenna@tinystudio.co", company: "Tiny Studio", size: "SMB", source: "referral", assigned_to: "alice", status: "new" };
    // clear:115
    l3 = await _clearTry(() => db.insert('leads', _pick(l3, LeadsSchema)), { op: 'insert', table: 'leads', line: 115, file: 'main.clear', source: "" }); // clear:115
    // clear:116
    let l4 = { name: "Derek Patel", email: "dp@biginc.com", company: "Big Inc", size: "Enterprise", source: "outbound", assigned_to: "charlie", status: "qualified" };
    // clear:124
    l4 = await _clearTry(() => db.insert('leads', _pick(l4, LeadsSchema)), { op: 'insert', table: 'leads', line: 124, file: 'main.clear', source: "" }); // clear:124
    // clear:125
    return res.status(201).json({ message: "seeded" });
  } catch (err) {
    console.error('[POST /api/seed] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/seed', line: 88, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// Frontend
// Tests
// Real business-rule coverage. Each test exercises one of the named
// rules in the POST /api/leads handler. Tests below check the rule
// NAMES the prover and audit PDF report on.
if (typeof test === 'function') {
// clear:286
test("happy path: full lead is accepted", async () => {
  // clear:287
  _response = await fetch(_baseUrl + "/api/leads", {
    method: "POST", headers: AUTH_HEADERS,
    body: JSON.stringify({ "name": "Test", "email": "test@x.com", "size": "SMB" })
  });
  _responseBody = await _response.json().catch(() => null);

  // clear:288
  _expectSuccess(_response);
  // clear:289
  _expectBodyHas(_responseBody, "id");
});
}
if (typeof test === 'function') {
// clear:291
test("rule lead-must-have-name: blank name is rejected", async () => {
  // clear:292
  _response = await fetch(_baseUrl + "/api/leads", {
    method: "POST", headers: AUTH_HEADERS,
    body: JSON.stringify({ "name": "", "email": "test@x.com", "size": "SMB" })
  });
  _responseBody = await _response.json().catch(() => null);

  // clear:293
  _expectFailure(_response);
});
}
if (typeof test === 'function') {
// clear:295
test("rule lead-must-have-email: blank email is rejected", async () => {
  // clear:296
  _response = await fetch(_baseUrl + "/api/leads", {
    method: "POST", headers: AUTH_HEADERS,
    body: JSON.stringify({ "name": "Test", "email": "", "size": "SMB" })
  });
  _responseBody = await _response.json().catch(() => null);

  // clear:297
  _expectFailure(_response);
});
}
if (typeof test === 'function') {
// clear:299
test("auth: updating a lead requires login", async () => {
  // clear:300
  // Could not find PUT endpoint for lead
});
}

const path = require('path');
app.use(express.static(__dirname));
app.get("/", (req, res) => res.sendFile('index.html', { root: __dirname }));
app.get("/routing-rules", (req, res) => res.sendFile('index.html', { root: __dirname }));
app.get("/owners", (req, res) => res.sendFile('index.html', { root: __dirname }));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});
process.on('SIGINT', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});