// Generated by Clear v1.0
const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// Log every request
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const ms = Date.now() - start;
    console.log(`${req.method} ${req.path} ${res.statusCode} ${ms}ms`);
  });
  next();
});
// Allow cross-origin requests
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema)); }
function _validate(body, rules) {
  for (const r of rules) {
    const v = body[r.field];
    if (r.required && (v == null || v === '')) return r.field + ' is required';
    if (v == null) continue;
    if (r.type === 'number' && typeof v !== 'number') return r.field + ' must be a number';
    if (r.type === 'boolean' && typeof v !== 'boolean') return r.field + ' must be true or false';
    if (r.min != null && r.type === 'text' && String(v).length < r.min) return r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters');
    if (r.max != null && r.type === 'text' && String(v).length > r.max) return r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters');
    if (r.min != null && r.type !== 'text' && v < r.min) return r.field + ' must be at least ' + r.min;
    if (r.max != null && r.type !== 'text' && v > r.max) return r.field + ' must be at most ' + r.max;
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) return r.field + ' must be a valid email';
    if (r.oneOf && !r.oneOf.includes(v)) return r.field + ' must be one of: ' + r.oneOf.join(', ');
  }
  return null;
}

// Cast Editor — Acid Test: Rebuild Cast's core UI in Clear
// Two-column layout: editor (left) + results/chat (right)
// --- Theme ---
// clear:7
let brand = "#2563eb";
// clear:8
let dark = "#0f172a";
// clear:9
let surface = "#f1f5f9";
// --- Backend ---
// clear:51
// Data shape: Sheets
const SheetsSchema = {
  title: { type: "text", required: true },
  code: { type: "text", required: true },
  created_at: { type: "timestamp", auto: true }
};
db.createTable('sheets', SheetsSchema);
// clear:56
// Data shape: Messages
const MessagesSchema = {
  role: { type: "text", required: true },
  content: { type: "text", required: true },
  sheet_id: { type: "fk", required: true },
  created_at: { type: "timestamp", auto: true }
};
db.createTable('messages', MessagesSchema);
// clear:65
app.get('/api/sheets', async (req, res) => {
  try {
    const all_sheets = await db.findAll('sheets');
    return res.json(all_sheets);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// clear:69
app.post('/api/sheets', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const sheet = req.body;
    const incoming = req.params;
    const _vErr = _validate(req.body, [{"field":"title","type":"text","required":true}, {"field":"code","type":"text","required":true}]);
    if (_vErr) return res.status(400).json({ error: _vErr });
    const new_sheet = await db.insert('sheets', _pick(sheet, SheetsSchema));
    return res.status(201).json(new_sheet);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// clear:76
app.post('/api/chat', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const message = req.body;
    const incoming = req.params;
    const _vErr = _validate(req.body, [{"field":"content","type":"text","required":true}]);
    if (_vErr) return res.status(400).json({ error: _vErr });
    const new_message = await db.insert('messages', _pick(message, MessagesSchema));
    return res.status(201).json(new_message);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// clear:82
app.get('/api/chat', async (req, res) => {
  try {
    const all_messages = await db.findAll('messages');
    return res.json(all_messages);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// --- Frontend ---

const path = require('path');
app.use(express.static(__dirname));
app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});