// Generated by Clear v1.0
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Posts: title*, excerpt, body*, category, author_name, author_avatar, image_url, created_at_date (line 10)
//
// ENDPOINTS:
//   GET /api/posts (line 25)
//   GET /api/posts/:id (line 29)
//   POST /api/posts (line 34)
//   DELETE /api/posts/:id [auth] (line 41)
//   POST /api/seed (line 46)
//
// PAGES:
//   'Blog' at / (line 78)
//
// DATAFLOW: Frontend ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const auth = require('./clear-runtime/auth');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// Log every request
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const ms = Date.now() - start;
    console.log(`${req.method} ${req.path} ${res.statusCode} ${ms}ms`);
  });
  next();
});
// Allow cross-origin requests
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});
app.use(auth.middleware());

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema)); }
function _validate(body, rules) {
  for (const r of rules) {
    let v = body[r.field];
    if (r.required && (v == null || v === '')) return r.field + ' is required';
    if (v == null) continue;
    if (r.type === 'number' && typeof v === 'string' && v.trim() !== '' && !isNaN(Number(v))) { body[r.field] = Number(v); v = body[r.field]; }
    if (r.type === 'number' && typeof v !== 'number') return r.field + ' must be a number';
    if (r.type === 'boolean' && typeof v !== 'boolean') return r.field + ' must be true or false';
    if (r.min != null && r.type === 'text' && String(v).length < r.min) return r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters');
    if (r.max != null && r.type === 'text' && String(v).length > r.max) return r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters');
    if (r.min != null && r.type !== 'text' && v < r.min) return r.field + ' must be at least ' + r.min;
    if (r.max != null && r.type !== 'text' && v > r.max) return r.field + ' must be at most ' + r.max;
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) return r.field + ' must be a valid email';
    if (r.matches === 'time' && !/^([01]\d|2[0-3]):[0-5]\d$/.test(v)) return r.field + ' must be a valid time (HH:MM)';
    if (r.matches === 'phone' && !/^[\+]?[\d\s\-\.\(\)]{7,15}$/.test(v)) return r.field + ' must be a valid phone number';
    if (r.matches === 'url' && !/^https?:\/\/.+/.test(v)) return r.field + ' must be a valid URL';
    if (r.oneOf && !r.oneOf.includes(v)) return r.field + ' must be one of: ' + r.oneOf.join(', ');
  }
  return null;
}
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  if (!debug) return { status, response: { error: safeMsg } };
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: ctx.line || null,
      clear_file: ctx.file || null,
      clear_source: ctx.source || null,
      hint: hint,
      technical: msg
    }
  };
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    posts: { line: 10, file: "main.clear", fields: { title: { required: true, type: "text" }, excerpt: { type: "text" }, body: { required: true, type: "text" }, category: { type: "text" }, author_name: { type: "text" }, author_avatar: { type: "text" }, image_url: { type: "text" }, created_at_date: { type: "timestamp" } } },
  },
  endpoints: {
    "GET /api/posts": { line: 25, file: "main.clear", auth: false },
    "GET /api/posts/:id": { line: 29, file: "main.clear", auth: false },
    "POST /api/posts": { line: 34, file: "main.clear", auth: false },
    "DELETE /api/posts/:id": { line: 41, file: "main.clear", auth: true },
    "POST /api/seed": { line: 46, file: "main.clear", auth: false },
  }
} : null;

// Blog — full-stack CRUD blog with card grid + article view
// ── Database ──────────────────────────────────────────────────────────────────
// Database: local memory (JSON file backup)
// Data shape: Posts
const PostsSchema = {
  title: { type: "text", required: true },
  excerpt: { type: "text" },
  body: { type: "text", required: true },
  category: { type: "text", default: "Article" },
  author_name: { type: "text", default: "Anonymous" },
  author_avatar: { type: "text" },
  image_url: { type: "text" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('posts', PostsSchema);
// ── Backend ───────────────────────────────────────────────────────────────────
// clear:25 — GET /api/posts
app.get('/api/posts', async (req, res) => {
  try {
    const all_posts = await db.findAll('posts');
    return res.json(all_posts);
  } catch (err) {
    console.error('[GET /api/posts] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/posts', line: 25, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:29 — GET /api/posts/:id
app.get('/api/posts/:id', async (req, res) => {
  try {
    const incoming = req.params;
    const post = await db.findOne('posts', { id: incoming.id });
    if (post == null) {
      return res.status(404).json({ message: "Post not found" });
    }
    return res.json(post);
  } catch (err) {
    console.error('[GET /api/posts/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/posts/:id', line: 29, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:34 — POST /api/posts
app.post('/api/posts', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const post_data = req.body;
    const incoming = req.params;
    const _vErr = _validate(req.body, [{"field":"title","type":"text","required":true,"min":1,"max":200}, {"field":"body","type":"text","required":true,"min":1}]);
    if (_vErr) return res.status(400).json({ error: _vErr });
    const new_post = await _clearTry(() => db.insert('posts', _pick(post_data, PostsSchema)), { op: 'insert', table: 'posts', line: 38, file: 'main.clear', source: "" }); // clear:38
    return res.json(new_post);
  } catch (err) {
    console.error('[POST /api/posts] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/posts', line: 34, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:41 — DELETE /api/posts/:id
app.delete('/api/posts/:id', async (req, res) => {
  try {
    const incoming = req.params;
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    await _clearTry(() => db.remove('posts', { id: incoming.id }), { op: 'remove', table: 'posts', line: 43, file: 'main.clear', source: "" }); // clear:43
    return res.json({ message: "deleted" });
  } catch (err) {
    console.error('[DELETE /api/posts/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'DELETE /api/posts/:id', line: 41, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:46 — POST /api/seed
app.post('/api/seed', async (req, res) => {
  try {
    if (process.env.NODE_ENV === 'production') return res.status(403).json({ error: 'Seed endpoint is disabled in production' });
    const _existing = await db.findAll('posts');
    if (_existing.length > 0) return res.json({ message: 'already seeded' });
    let p1 = { title: "Boost your conversion rate", excerpt: "Learn the best practices for improving your site conversion rates with proven strategies.", body: "Conversion rate optimization is one of the most impactful things you can do for your business. Start by understanding your funnel — where do users drop off? Use A/B testing to validate hypotheses. Small changes to copy, button placement, and page load speed can yield 20-30% improvements. The key is to measure everything and iterate quickly.", category: "Article", author_name: "Lindsay Walton", author_avatar: "https://randomuser.me/api/portraits/women/44.jpg", image_url: "https://images.unsplash.com/photo-1496128858413-b36217c2ce36?w=600&h=340&fit=crop" };
    await _clearTry(() => db.insert('posts', _pick(p1, PostsSchema)), { op: 'insert', table: 'posts', line: 55, file: 'main.clear', source: "" }); // clear:55
    let p2 = { title: "How to use search engine optimization", excerpt: "A deep dive into modern SEO techniques that actually work in 2026.", body: "SEO has evolved dramatically. Gone are the days of keyword stuffing and link farms. Modern SEO focuses on user intent, content quality, and technical performance. Core Web Vitals are now a ranking factor. Structured data helps search engines understand your content. The best SEO strategy is to create genuinely useful content that answers real questions.", category: "Tutorial", author_name: "Tom Cook", author_avatar: "https://randomuser.me/api/portraits/men/32.jpg", image_url: "https://images.unsplash.com/photo-1547586696-ea22b4d4235d?w=600&h=340&fit=crop" };
    await _clearTry(() => db.insert('posts', _pick(p2, PostsSchema)), { op: 'insert', table: 'posts', line: 64, file: 'main.clear', source: "" }); // clear:64
    let p3 = { title: "Improve your customer experience", excerpt: "Real results from companies that invested in customer experience design.", body: "Customer experience is the new competitive advantage. Companies that invest in CX see 1.5x higher customer lifetime value. Start with journey mapping — understand every touchpoint from discovery to renewal. Use NPS and CSAT surveys, but more importantly, watch session recordings. The gap between what customers say and what they do is where the real insights live.", category: "Case Study", author_name: "Dries Vincent", author_avatar: "https://randomuser.me/api/portraits/men/64.jpg", image_url: "https://images.unsplash.com/photo-1492724441997-5dc865305da7?w=600&h=340&fit=crop" };
    await _clearTry(() => db.insert('posts', _pick(p3, PostsSchema)), { op: 'insert', table: 'posts', line: 73, file: 'main.clear', source: "" }); // clear:73
    return res.json({ message: "seeded" });
  } catch (err) {
    console.error('[POST /api/seed] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/seed', line: 46, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// ── Frontend ──────────────────────────────────────────────────────────────────

const path = require('path');
app.use(express.static(__dirname));
app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});