#!/usr/bin/env python3
"""
Audit report PDF writer — consumes the JSON bundle from
`scripts/audit-bundle.mjs` and produces a navy/amber compliance PDF.

Usage:
  node scripts/audit-bundle.mjs apps/audit-demo/main.clear > /tmp/bundle.json
  python scripts/audit-pdf.py /tmp/bundle.json /tmp/audit.pdf

The PDF is what an auditor receives: every named business rule, the math
verdict for that rule, and (when available) the runtime witness data
showing 20 violating inputs and the rejection responses they produced.
"""

import json
import sys
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer,
    Table, TableStyle, PageBreak, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_JUSTIFY

# ---- Color palette (navy/amber from pe-document-style skill) ----
NAVY      = colors.HexColor('#0A1628')
AMBER     = colors.HexColor('#D4920B')
PALE      = colors.HexColor('#F7F5F0')
DARK_GRAY = colors.HexColor('#2D3748')
MED_GRAY  = colors.HexColor('#4A5568')
LT_GRAY   = colors.HexColor('#E2E8F0')
GREEN     = colors.HexColor('#276749')
RED       = colors.HexColor('#C53030')


def header_footer(canvas, doc):
    """CONFIDENTIAL bar at top + page number at bottom."""
    w, h = LETTER
    canvas.saveState()
    canvas.setFillColor(NAVY)
    canvas.rect(0, h - 0.4 * inch, w, 0.4 * inch, fill=1, stroke=0)
    canvas.setFillColor(AMBER)
    canvas.setFont('Helvetica-Bold', 9)
    canvas.drawString(0.6 * inch, h - 0.25 * inch, 'CONFIDENTIAL — AUDIT EVIDENCE')
    canvas.setFillColor(colors.white)
    canvas.setFont('Helvetica', 8)
    canvas.drawRightString(w - 0.6 * inch, h - 0.25 * inch, f'Generated by Clear · {datetime.now().strftime("%Y-%m-%d")}')

    canvas.setFillColor(LT_GRAY)
    canvas.rect(0, 0, w, 0.3 * inch, fill=1, stroke=0)
    canvas.setFillColor(MED_GRAY)
    canvas.setFont('Helvetica', 8)
    canvas.drawCentredString(w / 2, 0.1 * inch, f'Page {canvas.getPageNumber()}')
    canvas.restoreState()


def build_styles():
    s = getSampleStyleSheet()
    s.add(ParagraphStyle(name='Title1', fontName='Helvetica-Bold', fontSize=20, textColor=NAVY, spaceAfter=12, leading=24))
    s.add(ParagraphStyle(name='Sub', fontName='Helvetica', fontSize=11, textColor=MED_GRAY, spaceAfter=18, leading=14))
    s.add(ParagraphStyle(name='H1', fontName='Helvetica-Bold', fontSize=14, textColor=NAVY, spaceBefore=14, spaceAfter=8, leading=18))
    s.add(ParagraphStyle(name='H2', fontName='Helvetica-Bold', fontSize=11, textColor=NAVY, spaceBefore=10, spaceAfter=4, leading=14))
    s.add(ParagraphStyle(name='Body', fontName='Helvetica', fontSize=9.5, textColor=DARK_GRAY, leading=13, spaceAfter=6, alignment=TA_JUSTIFY))
    s.add(ParagraphStyle(name='Mono', fontName='Courier', fontSize=8.5, textColor=DARK_GRAY, leading=11, spaceAfter=4))
    s.add(ParagraphStyle(name='Verdict', fontName='Helvetica-Bold', fontSize=10, textColor=GREEN, spaceAfter=4, leading=12))
    s.add(ParagraphStyle(name='VerdictBad', fontName='Helvetica-Bold', fontSize=10, textColor=RED, spaceAfter=4, leading=12))
    s.add(ParagraphStyle(name='CodeBlock', fontName='Courier', fontSize=8, textColor=DARK_GRAY, leading=10, spaceAfter=6,
                        leftIndent=8, rightIndent=8, borderColor=LT_GRAY, borderWidth=0.5, borderPadding=6,
                        backColor=PALE))
    return s


def code_block_html(code_text):
    """Escape a JS string for ReportLab's mini-HTML, preserving spacing.

    ReportLab paragraphs collapse whitespace, so we replace leading
    indentation with non-breaking spaces and use <br/> for hard wraps.
    """
    safe = (code_text or '').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    return safe


def amber_underline(width=60):
    """Small amber accent line above section headers."""
    t = Table([['']], colWidths=[width], rowHeights=[3])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), AMBER),
        ('LINEABOVE', (0, 0), (-1, -1), 0, colors.white),
        ('LINEBELOW', (0, 0), (-1, -1), 0, colors.white),
    ]))
    return t


def summary_metric_row(rule_counts, witness_passed, witness_total):
    """4-across KPI display row — proved / verified / total / file."""
    proved = rule_counts.get('proved', 0)
    total = rule_counts.get('total', 0)
    cells = [
        [
            Paragraph(f'<b><font size="22" color="#0A1628">{proved}/{total}</font></b>', getSampleStyleSheet()['Normal']),
            Paragraph('<font size="8" color="#4A5568">RULES PROVED<br/>by structural enforcement</font>', getSampleStyleSheet()['Normal']),
        ],
        [
            Paragraph(f'<b><font size="22" color="#0A1628">{witness_passed}/{witness_total}</font></b>', getSampleStyleSheet()['Normal']),
            Paragraph('<font size="8" color="#4A5568">VIOLATING INPUTS<br/>rejected at runtime</font>', getSampleStyleSheet()['Normal']),
        ],
        [
            Paragraph(f'<b><font size="22" color="#D4920B">{rule_counts.get("disproved", 0)}</font></b>', getSampleStyleSheet()['Normal']),
            Paragraph('<font size="8" color="#4A5568">RULES DISPROVED<br/>(should be 0)</font>', getSampleStyleSheet()['Normal']),
        ],
        [
            Paragraph(f'<b><font size="22" color="#0A1628">{rule_counts.get("unverifiable", 0)}</font></b>', getSampleStyleSheet()['Normal']),
            Paragraph('<font size="8" color="#4A5568">UNVERIFIABLE<br/>(impure body)</font>', getSampleStyleSheet()['Normal']),
        ],
    ]
    t = Table([cells], colWidths=[1.5 * inch] * 4, rowHeights=[1.0 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), PALE),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 0.5, LT_GRAY),
    ]))
    return t


def article_for(noun):
    """Pick 'a' or 'an' for a noun. Approximate but right for the
    business-domain words the prover surfaces (deal, lead, input,
    expense, ticket, booking, user, etc.)."""
    if not noun:
        return 'a'
    return 'an' if noun[0].lower() in 'aeiou' else 'a'


def render_enforcement_tag(tag, entity_noun, rule_name, styles):
    """Turn one structured enforcement tag into a list of platypus elements.

    The prover emits a small set of tag kinds; each maps to a different
    auditor-facing paragraph. No prover internals leak into the PDF —
    this function owns all the human-readable framing.
    """
    out = []
    kind = tag.get('kind')
    line = tag.get('line') or '?'
    source_line = (tag.get('sourceLine') or '').strip()
    compiled = tag.get('compiledCheck') or {}
    code_text = compiled.get('code') or ''
    art = article_for(entity_noun)

    if kind == 'tautology':
        # Vacuous guard — the condition is universally true on constants.
        out.append(Paragraph(
            f'<b>This guard is a constant tautology.</b> The math-checker simplified the '
            f'expression on line {line} to <i>true</i>. No input can violate this rule because '
            f'the condition does not depend on input — it is true for every possible value.',
            styles['Body']))
        if source_line:
            out.append(Paragraph(f'<b>Source (line {line}):</b>', styles['Body']))
            out.append(Paragraph(
                f'<font name="Courier" size="8">{code_block_html(source_line)}</font>',
                styles['CodeBlock']))
        return out

    if kind == 'structural-enforcement':
        # Proof by construction. The math-checker can't simulate every
        # possible input, but the runtime guard makes "no execution past
        # this line satisfies the failing condition" a structural fact
        # about the program.
        out.append(Paragraph(
            f'<b>This rule is enforced by construction of the program</b>, not by math '
            f'simulation. The math-checker can\'t simulate every possible {code_block_html(entity_noun)} — '
            f'the values are not bounded. So instead it reads the structure of the compiled '
            f'application and confirms that the compiler put a hard check at line {line} that '
            f'rejects any {code_block_html(entity_noun)} that fails the condition.',
            styles['Body']))

        if source_line:
            out.append(Paragraph(f'<b>Your source (line {line}):</b>', styles['Body']))
            out.append(Paragraph(
                f'<font name="Courier" size="8">{code_block_html(source_line)}</font>',
                styles['CodeBlock']))

        if code_text:
            out.append(Paragraph(
                f'<b>The actual runtime check (compiled from line {line}):</b>',
                styles['Body']))
            out.append(Paragraph(
                f'<font name="Courier" size="8">{code_block_html(code_text)}</font>',
                styles['CodeBlock']))

        out.append(Paragraph(
            f'<b>The claim, in plain English:</b> no line of compiled code after this check '
            f'ever runs for {art} {code_block_html(entity_noun)} that fails the condition. Not because the '
            f'math-checker proved it abstractly, but because the program literally rejects '
            f'those inputs before reaching the next line. The runtime evidence below '
            f'corroborates that the rejection actually fires.',
            styles['Body']))
        return out

    # Unknown tag kind — fall back to a neutral statement so the PDF
    # never silently drops content.
    out.append(Paragraph(
        f'<i>(Enforcement tag of kind {kind!r} at line {line} — renderer pending update.)</i>',
        styles['Body']))
    return out


def build_rule_section(rule, styles):
    """One rule's full audit entry: math verdict + witness data + samples."""
    parts = []
    parts.append(amber_underline(60))
    parts.append(Spacer(1, 4))
    parts.append(Paragraph(f"Rule: {rule['name']}", styles['H1']))

    verdict = rule['verdict']
    if verdict == 'proved':
        parts.append(Paragraph('VERDICT: PROVED', styles['Verdict']))
    elif verdict == 'disproved':
        parts.append(Paragraph('VERDICT: DISPROVED', styles['VerdictBad']))
    else:
        parts.append(Paragraph(f'VERDICT: {verdict.upper()}', styles['VerdictBad']))

    # Math verdict — render based on the structured enforcement tags from
    # the prover. Each guard contributes one explanation block. Falls back
    # to the legacy `reason` field for older bundles or for verdicts that
    # don't carry enforcement tags (DISPROVED, UNVERIFIABLE).
    parts.append(Paragraph('How it was proved formally', styles['H2']))
    enforcement = rule.get('enforcement') or []
    entity_noun = rule.get('entity') or 'incoming input'
    if verdict == 'proved' and enforcement:
        for tag in enforcement:
            parts.extend(render_enforcement_tag(tag, entity_noun, rule['name'], styles))
    elif rule.get('reason'):
        parts.append(Paragraph(rule['reason'], styles['Body']))
    elif verdict == 'proved':
        parts.append(Paragraph(
            'Constant tautology — the guard expression is universally true (e.g. <code>1 &lt; 2</code>). '
            'No input can violate this rule because the condition does not depend on input.',
            styles['Body']))

    # Runtime witness
    witness = rule.get('witness')
    parts.append(Paragraph('How it was verified at runtime', styles['H2']))
    if not witness or not witness.get('automated'):
        reason = (witness or {}).get('reason', 'no witness data available')
        parts.append(Paragraph(
            f'<i>Runtime witness automation pending for this rule shape.</i><br/>{reason}',
            styles['Body']))
    else:
        sent = witness['inputs_sent']
        rej = witness['rejected']
        rule_named = witness['rule_name_in_body']
        parts.append(Paragraph(
            f'The compiled application was spawned on a free port. <b>{sent}</b> inputs that violate '
            f'this rule were sent to <code>POST {witness["route"]}</code>. Of those, '
            f'<b>{rej}</b> came back as HTTP 403 rejections, and <b>{rule_named}</b> carried this rule\'s '
            f'name in the response body — the audit trail attribution.',
            styles['Body']))
        if rej == sent and rule_named == sent:
            parts.append(Paragraph(
                '<b>Two-witness verification: PASS.</b> Math claim corroborated by measured runtime evidence.',
                styles['Verdict']))
        else:
            parts.append(Paragraph(
                f'<b>Two-witness verification: PARTIAL ({rej}/{sent} rejected, {rule_named}/{sent} named).</b> '
                f'Math claim is not fully corroborated.',
                styles['VerdictBad']))

        # Sample table
        samples = witness.get('samples', [])
        if samples:
            parts.append(Spacer(1, 6))
            parts.append(Paragraph('Sample violating inputs and their rejections', styles['H2']))
            data = [['Input sent', 'Status', 'Rejection message', 'Rule named?']]
            for s in samples:
                input_str = ', '.join(f'{k}={v}' for k, v in s['input'].items())
                body = s.get('body') or {}
                msg = body.get('error', '(no body)')
                rule_in = body.get('rule', '(missing)')
                named = '✓' if rule_in == rule['name'] else '✗'
                data.append([
                    Paragraph(f'<font name="Courier" size="7.5">{input_str}</font>', styles['Mono']),
                    str(s['status']),
                    Paragraph(f'<font size="7.5">{msg[:80]}</font>', styles['Body']),
                    named,
                ])
            tbl = Table(data, colWidths=[2.0 * inch, 0.6 * inch, 3.0 * inch, 0.7 * inch])
            tbl.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), NAVY),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 8.5),
                ('ALIGN', (1, 0), (1, -1), 'CENTER'),
                ('ALIGN', (3, 0), (3, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 0.4, LT_GRAY),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, PALE]),
            ]))
            parts.append(tbl)

    parts.append(Spacer(1, 16))
    return KeepTogether(parts)


def build_pdf(bundle, out_path):
    styles = build_styles()
    doc = BaseDocTemplate(
        str(out_path),
        pagesize=LETTER,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        topMargin=0.7 * inch, bottomMargin=0.5 * inch,
        title='Clear — Business Rule Audit Report',
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='main')
    doc.addPageTemplates([PageTemplate(id='all', frames=[frame], onPage=header_footer)])

    story = []

    # Title block
    story.append(Paragraph('Business Rule Audit Report', styles['Title1']))
    story.append(Paragraph(
        f'Source: <b>{bundle["file_basename"]}</b><br/>'
        f'Generated: {bundle["generated_at"]}<br/>'
        f'This report shows every named business rule in the source application, '
        f'how each was proved formally by the math-checker, and how each was verified at runtime '
        f'by sending violating inputs to the running application and observing rejections.',
        styles['Sub']))

    # Summary metrics
    rule_counts = bundle.get('rule_counts', {})
    rules = bundle.get('rules', [])
    automated_rules = [r for r in rules if (r.get('witness') or {}).get('automated')]
    witness_total = sum((r.get('witness') or {}).get('inputs_sent', 0) for r in automated_rules)
    witness_passed = sum((r.get('witness') or {}).get('rejected', 0) for r in automated_rules)
    story.append(summary_metric_row(rule_counts, witness_passed, witness_total))
    story.append(Spacer(1, 16))

    # Trust basis section
    story.append(amber_underline(60))
    story.append(Spacer(1, 4))
    story.append(Paragraph('Trust basis: how to read this report', styles['H1']))
    story.append(Paragraph(
        '<b>Math-proved.</b> The compiler\'s prover walks every named rule and decides whether the rule '
        'holds for every possible input. Two paths are possible: (a) the guard expression simplifies '
        'to a constant true (a tautology), or (b) the guard exists as a control-flow check — any '
        'execution past the guard satisfies the condition because the runtime rejects any input '
        'that fails it before control reaches the next line.',
        styles['Body']))
    story.append(Paragraph(
        '<b>Runtime-verified.</b> The math claim depends on the compiler correctly emitting the '
        'runtime guard. To corroborate, this report spawns the compiled application on a free port '
        'and sends 20 inputs that violate the rule. If every input is rejected with HTTP 403 and '
        'every response body carries the rule\'s name, the math claim is corroborated. If even one '
        'input slips through with a 200 response, the math claim is not trustworthy.',
        styles['Body']))
    story.append(Paragraph(
        '<b>Two-witness verification.</b> A rule earns full audit confidence only when BOTH witnesses '
        'agree — math says it\'s impossible to violate, AND runtime measurably rejects violators. The '
        'metrics row at the top shows both counts.',
        styles['Body']))
    story.append(Spacer(1, 12))

    # Per-rule sections
    story.append(amber_underline(60))
    story.append(Spacer(1, 4))
    story.append(Paragraph('Rule-by-rule audit', styles['H1']))

    for rule in rules:
        story.append(build_rule_section(rule, styles))

    doc.build(story)


def main():
    if len(sys.argv) < 3:
        print('Usage: python audit-pdf.py <bundle.json> <out.pdf>', file=sys.stderr)
        sys.exit(2)
    bundle_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    bundle = json.loads(bundle_path.read_text(encoding='utf-8'))
    build_pdf(bundle, out_path)
    print(f'Wrote {out_path} ({out_path.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
