// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"322":21,"325":25,"339":15,"420":51,"421":51,"424":52,"426":52,"435":54,"436":54,"439":55,"441":55,"450":57,"451":57,"457":58,"460":61,"461":61,"462":62,"472":64,"473":64,"478":65,"480":66,"483":66,"485":67,"496":71,"497":71,"505":72,"507":78,"508":78,"509":79,"511":85,"512":85,"513":86,"515":92,"516":92,"517":93,"519":99,"520":99,"521":100,"523":106,"524":106,"525":107,"538":201,"540":202,"547":203,"549":204,"554":206,"556":207} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Requests: title*, description, amount, status, notes, requester, created_at_date (line 25)
//
// ENDPOINTS:
//   GET /api/requests (line 51)
//   GET /api/requests/pending (line 54)
//   POST /api/requests (line 57)
//   PUT /api/requests/:id [auth] (line 64)
//   POST /api/seed (line 71)
//
// PAGES:
//   'Approval Queue' at / (line 111)
//
// DATAFLOW: Frontend ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// CF-1: runtime instrumentation — fire-and-forget beacons to the Compiler Flywheel.
const _CLEAR_FLYWHEEL_URL = process.env.CLEAR_FLYWHEEL_URL;
const _CLEAR_COMPILE_ROW_ID = process.env.CLEAR_COMPILE_ROW_ID;
function _clearBeacon(event) {
  if (!_CLEAR_FLYWHEEL_URL || !_CLEAR_COMPILE_ROW_ID) return;
  try {
    fetch(_CLEAR_FLYWHEEL_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(Object.assign({ compile_row_id: _CLEAR_COMPILE_ROW_ID, ts: Date.now() }, event)),
      signal: AbortSignal.timeout(500),
    }).catch(() => {});
  } catch {}
}
app.use((req, res, next) => {
  const _t0 = Date.now();
  res.on('finish', () => {
    _clearBeacon({ event_type: 'endpoint_latency', method: req.method, path: req.route ? req.route.path : req.path, status: res.statusCode, duration_ms: Date.now() - _t0 });
  });
  next();
});
app.use((err, req, res, next) => {
  _clearBeacon({ event_type: 'endpoint_error', method: req.method, path: req.path, error_sig: (err && err.message ? String(err.message).substring(0, 200) : 'unknown') });
  next(err);
});
// Log every request
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const ms = Date.now() - start;
    console.log(`${req.method} ${req.path} ${res.statusCode} ${ms}ms`);
  });
  next();
});
// Allow cross-origin requests
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});
// Auth scaffolding from `allow signup and login` (clear:46)
//   emits: POST /auth/signup, POST /auth/login, GET /auth/me
//   plus:  requireLogin middleware, requireRole middleware, JWT secret, bcrypt + jwt requires
const _JWT_SECRET = process.env.JWT_SECRET || require('crypto').randomBytes(32).toString('hex');
const _users = [];

// JWT middleware — extracts user from token on every request
app.use((req, res, next) => {
  const authHeader = req.headers.authorization || '';
  if (authHeader.startsWith('Bearer ')) {
    try {
      req.user = jwt.verify(authHeader.slice(7), _JWT_SECRET);
    } catch(e) { req.user = null; }
  }
  next();
});

// POST /auth/signup — create new user
app.post('/auth/signup', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    if (_users.find(u => u.email === email)) return res.status(400).json({ error: 'Email already registered' });
    const password_hash = await bcrypt.hash(password, 10);
    const user = { id: _users.length + 1, email, password_hash, role: 'user', created_at: new Date().toISOString() };
    _users.push(user);
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.status(201).json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// POST /auth/login — authenticate user
app.post('/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    const user = _users.find(u => u.email === email);
    if (!user) return res.status(401).json({ error: 'Invalid email or password' });
    const valid = await bcrypt.compare(password, user.password_hash);
    if (!valid) return res.status(401).json({ error: 'Invalid email or password' });
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// GET /auth/me — return current user
app.get('/auth/me', (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
  const user = _users.find(u => u.id === req.user.id);
  if (!user) return res.status(404).json({ error: 'User not found' });
  res.json({ id: user.id, email: user.email, role: user.role, created_at: user.created_at });
});

// --- Live App Editing routes (Meph edit widget) ---
// Widget is served from a static file in clear-runtime/. API calls
// proxy to Studio (when STUDIO_PORT is set in the environment). In
// a standalone deploy STUDIO_PORT is unset and the API path 503s.
const _MEPH_WIDGET_PATH = require('path').join(__dirname, 'clear-runtime', 'meph-widget.js');
app.get('/__meph__/widget.js', (req, res) => {
  try {
    res.type('application/javascript').send(require('fs').readFileSync(_MEPH_WIDGET_PATH, 'utf8'));
  } catch(e) { res.status(404).send('// widget bundle not found'); }
});
app.all('/__meph__/api/:action', async (req, res) => {
  const studioPort = process.env.STUDIO_PORT;
  if (!studioPort) {
    return res.status(503).json({ error: 'Live editing is not available in this environment (STUDIO_PORT not set)' });
  }
  try {
    const upstream = 'http://localhost:' + studioPort + '/__meph__/api/' + req.params.action;
    const r = await fetch(upstream, {
      method: req.method,
      headers: { 'Content-Type': 'application/json', 'Authorization': req.headers.authorization || '' },
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined : JSON.stringify(req.body || {}),
    });
    const body = await r.text();
    res.status(r.status).type(r.headers.get('content-type') || 'application/json').send(body);
  } catch(e) {
    res.status(502).json({ error: 'Proxy to Studio failed: ' + e.message });
  }
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _validate(body, rules) {
  if (body == null || typeof body !== 'object') return [{ field: '_body', message: 'Request body is required' }];
  const _errs = [];
  for (const r of rules) {
    let v = body[r.field];
    if (r.required && (v == null || v === '')) { _errs.push({ field: r.field, message: r.field + ' is required' }); continue; }
    if (v == null) continue;
    if (r.type === 'number' && typeof v === 'string' && v.trim() !== '' && !isNaN(Number(v))) { body[r.field] = Number(v); v = body[r.field]; }
    if (r.type === 'number' && typeof v !== 'number') { _errs.push({ field: r.field, message: r.field + ' must be a number' }); continue; }
    if (r.type === 'boolean' && typeof v !== 'boolean') { _errs.push({ field: r.field, message: r.field + ' must be true or false' }); continue; }
    if (r.min != null && r.type === 'text' && String(v).length < r.min) _errs.push({ field: r.field, message: r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters') });
    if (r.max != null && r.type === 'text' && String(v).length > r.max) _errs.push({ field: r.field, message: r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters') });
    if (r.min != null && r.type !== 'text' && v < r.min) _errs.push({ field: r.field, message: r.field + ' must be at least ' + r.min });
    if (r.max != null && r.type !== 'text' && v > r.max) _errs.push({ field: r.field, message: r.field + ' must be at most ' + r.max });
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid email' });
    if (r.matches === 'time' && !/^([01]\d|2[0-3]):[0-5]\d$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid time (HH:MM)' });
    if (r.matches === 'phone' && !/^[\+]?[\d\s\-\.\(\)]{7,15}$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid phone number' });
    if (r.matches === 'url' && !/^https?:\/\/.+/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid URL' });
    if (r.oneOf && !r.oneOf.includes(v)) _errs.push({ field: r.field, message: r.field + ' must be one of: ' + r.oneOf.join(', ') });
  }
  return _errs.length ? _errs : null;
}
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    requests: { line: 25, file: "main.clear", fields: { title: { required: true, type: "text" }, description: { type: "text" }, amount: { type: "number" }, status: { type: "text" }, notes: { type: "text" }, requester: { type: "text" }, created_at_date: { type: "timestamp" } } },
  },
  endpoints: {
    "GET /api/requests": { line: 51, file: "main.clear", auth: false },
    "GET /api/requests/pending": { line: 54, file: "main.clear", auth: false },
    "POST /api/requests": { line: 57, file: "main.clear", auth: false },
    "PUT /api/requests/:id": { line: 64, file: "main.clear", auth: true },
    "POST /api/seed": { line: 71, file: "main.clear", auth: false },
  }
} : null;

// LAYOUT:
// +----------------+-----------------------------------------------+
// | Approval Queue | Header: intake workspace                       |
// |                +-----------------------------------------------+
// | Queues         | Pending approvals + KPI strip                  |
// | - Pending      | +-------------------------+ +---------------+ |
// | - All requests | | pending table           | | detail panel  | |
// |                | | requester / amount      | | decision view | |
// |                | +-------------------------+ +---------------+ |
// |                | Submit request form                           |
// +----------------+-----------------------------------------------+
//
// DATAFLOW:
// Submitter -> POST /api/requests -> Requests table
// Approver  -> GET /api/requests/pending -> table -> detail panel
// Approver  -> PUT /api/requests/:id -> approved or rejected
// clear:21
// Database: local memory (JSON file backup)
// Database
// clear:25
// Data shape: Requests
const RequestsSchema = {
  title: { type: "text", required: true },
  description: { type: "text" },
  amount: { type: "number", default: 0 },
  status: { type: "text", default: "pending" },
  notes: { type: "text" },
  requester: { type: "text" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('requests', RequestsSchema);
// Approval queue — auto-generates audit table, notification queue,
// filtered URL, and PUT URLs for each action. Each PUT requires login.
// clear:15
// Auto-generated audit table for queue 'request'
const RequestDecisionsSchema = {
  request_id: { type: "text", required: true },
  decision: { type: "text", required: true },
  decided_by: { type: "text" },
  decision_note: { type: "text" },
  next_status: { type: "text" },
  decided_at: { type: "timestamp", auto: true }
};
db.createTable('request_decisions', RequestDecisionsSchema);
// Auto-generated: GET filtered queue for 'request'
app.get('/api/requests/queue', (req, res) => {
  const _all = db.findAll('requests') || [];
  const _pending = _all.filter(_r => (_r && _r.status) === 'pending');
  res.json(_pending);
});
// Auto-generated: GET decision history for 'request'
app.get('/api/request-decisions', (req, res) => {
  res.json(db.findAll('request_decisions') || []);
});
// Auto-generated: approve action for 'request'
app.put('/api/requests/:id/approve', (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Authentication required' });
  const _id = req.params.id;
  const _record = db.findById('requests', _id);
  if (!_record) return res.status(404).json({ error: 'not found' });
  _record.status = "approved";
  db.update('requests', _id, _record);
  // Insert audit row
  db.insert('request_decisions', {
    request_id: _id,
    decision: "approve",
    decided_by: "approver",
    next_status: "approved",
    decided_at: new Date().toISOString()
  });
  res.json(_record);
});
// Auto-generated: reject action for 'request'
app.put('/api/requests/:id/reject', (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Authentication required' });
  const _id = req.params.id;
  const _record = db.findById('requests', _id);
  if (!_record) return res.status(404).json({ error: 'not found' });
  _record.status = "rejected";
  db.update('requests', _id, _record);
  // Insert audit row
  db.insert('request_decisions', {
    request_id: _id,
    decision: "reject",
    decided_by: "approver",
    next_status: "rejected",
    decided_at: new Date().toISOString()
  });
  res.json(_record);
});
// Auto-generated: CSV export for 'request'
const _csvSensitive_request = /^(password|password_hash|bcrypt|hash|token|api_token|api_key|secret|salt)$/i;
function _clearCsvEscape_request(cell) {
  if (cell == null) return '';
  let s = typeof cell === 'object' ? JSON.stringify(cell) : String(cell);
  if (/[",\n\r]/.test(s)) s = '"' + s.replace(/"/g, '""') + '"';
  return s;
}
app.get('/api/requests/export.csv', (req, res) => {
  const _rows = db.findAll('requests') || [];
  const _allKeys = new Set();
  for (const _r of _rows) { if (_r && typeof _r === 'object') Object.keys(_r).forEach(k => _allKeys.add(k)); }
  const _cols = Array.from(_allKeys).filter(k => !_csvSensitive_request.test(k));
  const _header = _cols.map(c => _clearCsvEscape_request(c)).join(',');
  const _body = _rows.map(_r => _cols.map(c => _clearCsvEscape_request(_r ? _r[c] : '')).join(',')).join('\n');
  const _date = new Date().toISOString().slice(0, 10);
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', 'attachment; filename="requests-export-' + _date + '.csv"');
  res.send(_header + '\n' + _body);
});

// Backend
// # Middleware
// # Endpoints
// clear:51
// clear:51 — GET /api/requests
app.get('/api/requests', async (req, res) => {
  try {
    // clear:52
    const _resp_52 = (await db.findAll('requests', {}, { limit: 50 })).map(_revive);
    // clear:52
    return res.json(_resp_52);
  } catch (err) {
    console.error('[GET /api/requests] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/requests', line: 51, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:54
// clear:54 — GET /api/requests/pending
app.get('/api/requests/pending', async (req, res) => {
  try {
    // clear:55
    const _resp_55 = (await db.findAll('requests', { status: "pending" }, { limit: 50 })).map(_revive);
    // clear:55
    return res.json(_resp_55);
  } catch (err) {
    console.error('[GET /api/requests/pending] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/requests/pending', line: 54, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:57
// clear:57 — POST /api/requests
app.post('/api/requests', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const request = req.body;
    const incoming = req.params;
    // clear:58
    const _vErrs = _validate(req.body, [{"field":"title","type":"text","required":true,"min":1,"max":200}, {"field":"amount","type":"number","min":0}]);
    if (_vErrs) return res.status(400).json({ errors: _vErrs });
    // clear:61
    const new_request = await _clearTry(() => db.insert('requests', _pick(request, RequestsSchema)), { op: 'insert', table: 'requests', line: 61, file: 'main.clear', source: "" }); // clear:61
    // clear:62
    return res.status(201).json({ ...new_request, message: "success" });
  } catch (err) {
    console.error('[POST /api/requests] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/requests', line: 57, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:64
// clear:64 — PUT /api/requests/:id
app.put('/api/requests/:id', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const request = req.body;
    // clear:65
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:66
    const _picked_request = _pick(request, RequestsSchema);
    _picked_request.id = req.params.id;
    await _clearTry(() => db.update('requests', _picked_request), { op: 'update', table: 'requests', line: 66, file: 'main.clear', source: "" }); // clear:66
    Object.assign(request, await db.findOne('requests', { id: _picked_request.id }) || {});
    // clear:67
    return res.status(200).json({ message: "updated" });
  } catch (err) {
    console.error('[PUT /api/requests/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'PUT /api/requests/:id', line: 64, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// # Seed Data
// clear:71
// clear:71 — POST /api/seed
app.post('/api/seed', async (req, res) => {
  try {
    if (process.env.NODE_ENV === 'production') return res.status(403).json({ error: 'Seed endpoint is disabled in production' });
    const _existing = await db.findAll('requests');
    if (_existing.length > 0) return res.json({ message: 'already seeded' });
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const seed = req.body;
    // clear:72
    let r1 = { title: "Quarterly software budget - Acme Corp", description: "Standard renewal, 15 seats", amount: 4500, status: "pending", requester: "sarah.j" };
    // clear:78
    r1 = await _clearTry(() => db.insert('requests', _pick(r1, RequestsSchema)), { op: 'insert', table: 'requests', line: 78, file: 'main.clear', source: "" }); // clear:78
    // clear:79
    let r2 = { title: "Travel expenses - sales conference", description: "Airfare and hotel for 2 reps", amount: 2800, status: "pending", requester: "mike.l" };
    // clear:85
    r2 = await _clearTry(() => db.insert('requests', _pick(r2, RequestsSchema)), { op: 'insert', table: 'requests', line: 85, file: 'main.clear', source: "" }); // clear:85
    // clear:86
    let r3 = { title: "Contractor engagement - design", description: "Design contractor, 3 months", amount: 18000, status: "pending", requester: "alex.p" };
    // clear:92
    r3 = await _clearTry(() => db.insert('requests', _pick(r3, RequestsSchema)), { op: 'insert', table: 'requests', line: 92, file: 'main.clear', source: "" }); // clear:92
    // clear:93
    let r4 = { title: "New office chairs", description: "Ergonomic chairs for 8 desks", amount: 2400, status: "approved", requester: "jamie.k" };
    // clear:99
    r4 = await _clearTry(() => db.insert('requests', _pick(r4, RequestsSchema)), { op: 'insert', table: 'requests', line: 99, file: 'main.clear', source: "" }); // clear:99
    // clear:100
    let r5 = { title: "Expired credit card", description: "Card expired last week, need replacement", amount: 0, status: "rejected", requester: "taylor.w" };
    // clear:106
    r5 = await _clearTry(() => db.insert('requests', _pick(r5, RequestsSchema)), { op: 'insert', table: 'requests', line: 106, file: 'main.clear', source: "" }); // clear:106
    // clear:107
    return res.status(201).json({ message: "seeded" });
  } catch (err) {
    console.error('[POST /api/seed] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/seed', line: 71, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// Frontend
// Tests
if (typeof test === 'function') {
// clear:201
test("can user submit a request with title is 'Budget approval' , amount is 500", async () => {
  // clear:202
  _response = await fetch(_baseUrl + "/api/requests", {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ "title": "Budget approval", "amount": 500 })
  });
  _responseBody = await _response.json().catch(() => null);
  assert(_response.status >= 200 && _response.status < 300, "Create should succeed, got " + _response.status);
  // clear:203
  _expectSuccess(_response);
  // clear:204
  _expectBodyHas(_responseBody, "id");
});
}
if (typeof test === 'function') {
// clear:206
test("updating a request should require login", async () => {
  // clear:207
  // Could not find PUT endpoint for request
});
}

const path = require('path');
app.use(express.static(__dirname));
app.get("/", (req, res) => res.sendFile('index.html', { root: __dirname }));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});
process.on('SIGINT', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});