// Generated by Clear v1.0
const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema)); }
function _validate(body, rules) {
  for (const r of rules) {
    const v = body[r.field];
    if (r.required && (v == null || v === '')) return r.field + ' is required';
    if (v == null) continue;
    if (r.type === 'number' && typeof v !== 'number') return r.field + ' must be a number';
    if (r.type === 'boolean' && typeof v !== 'boolean') return r.field + ' must be true or false';
    if (r.min != null && r.type === 'text' && String(v).length < r.min) return r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters');
    if (r.max != null && r.type === 'text' && String(v).length > r.max) return r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters');
    if (r.min != null && r.type !== 'text' && v < r.min) return r.field + ' must be at least ' + r.min;
    if (r.max != null && r.type !== 'text' && v > r.max) return r.field + ' must be at most ' + r.max;
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) return r.field + ' must be a valid email';
    if (r.oneOf && !r.oneOf.includes(v)) return r.field + ' must be one of: ' + r.oneOf.join(', ');
  }
  return null;
}

// Database
// clear:4
// Database: local memory (JSON file backup)
// clear:6
// Data shape: Models
const ModelsSchema = {
  name: { type: "text", required: true },
  accuracy: { type: "number", default: 0 },
  status: { type: "text", default: "pending" },
  created_at_date: { type: "timestamp", auto: true }
};
db.createTable('models', ModelsSchema);
// clear:12
// Data shape: Results
const ResultsSchema = {
  model_id: { type: "number", required: true },
  metric: { type: "text", required: true },
  value: { type: "number", required: true }
};
db.createTable('results', ResultsSchema);
// Backend
// Allow the frontend to talk to the backend
// clear:20
// Allow cross-origin requests
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});
// clear:21
// Log every request
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const ms = Date.now() - start;
    console.log(`${req.method} ${req.path} ${res.statusCode} ${ms}ms`);
  });
  next();
});
// clear:23
app.get('/api/models', async (req, res) => {
  try {
    const all_models = await db.findAll('models');
    return res.json(all_models);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// clear:27
app.get('/api/results', async (req, res) => {
  try {
    const all_results = await db.findAll('results');
    return res.json(all_results);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// clear:31
app.post('/api/models', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const model_data = req.body;
    const _vErr = _validate(req.body, [{"field":"name","type":"text","required":true,"min":1,"max":100}]);
    if (_vErr) return res.status(400).json({ error: _vErr });
    const new_model = await db.insert('models', _pick(model_data, ModelsSchema));
    return res.status(201).json({ ...new_model, message: "success" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// Frontend
// clear:39
let primary = "#2563eb";
// clear:40
let surface = "#ffffff";
// clear:41
let dark_bg = "#0f172a";

const path = require('path');
app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});