// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"158":3,"160":5,"166":8,"173":12,"180":16,"181":16,"186":17,"187":17,"188":18,"198":20,"199":20,"202":21,"204":22,"213":24,"214":24,"220":25,"222":26,"223":26,"224":27,"234":29,"235":29,"238":30,"240":31} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Workspaces: name* (line 5)
//   Members: workspace_id*, user_id* (line 8)
//   Items: title*, workspace_id* (line 12)
//
// ENDPOINTS:
//   POST /api/workspaces (line 16)
//   GET /api/workspaces (line 20)
//   POST /api/workspaces/:id/members (line 24)
//   GET /api/workspaces/:id/items (line 29)
//
// DATAFLOW: Client ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    workspaces: { line: 5, file: "main.clear", fields: { name: { required: true, type: "text" } } },
    members: { line: 8, file: "main.clear", fields: { workspace_id: { required: true, type: "fk" }, user_id: { required: true, type: "fk" } } },
    items: { line: 12, file: "main.clear", fields: { title: { required: true, type: "text" }, workspace_id: { required: true, type: "fk" } } },
  },
  endpoints: {
    "POST /api/workspaces": { line: 16, file: "main.clear", auth: false },
    "GET /api/workspaces": { line: 20, file: "main.clear", auth: false },
    "POST /api/workspaces/:id/members": { line: 24, file: "main.clear", auth: false },
    "GET /api/workspaces/:id/items": { line: 29, file: "main.clear", auth: false },
  }
} : null;

// clear:3
// Database: local memory (JSON file backup)
// clear:5
// Data shape: Workspaces
const WorkspacesSchema = {
  name: { type: "text", required: true }
};
db.createTable('workspaces', WorkspacesSchema);
// clear:8
// Data shape: Members
const MembersSchema = {
  workspace_id: { type: "fk", required: true },
  user_id: { type: "fk", required: true }
};
db.createTable('members', MembersSchema);
// clear:12
// Data shape: Items
const ItemsSchema = {
  title: { type: "text", required: true },
  workspace_id: { type: "fk", required: true }
};
db.createTable('items', ItemsSchema);
// clear:16
// clear:16 — POST /api/workspaces
app.post('/api/workspaces', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const workspace = req.body;
    // clear:17
    const saved = await _clearTry(() => db.insert('workspaces', _pick(workspace, WorkspacesSchema)), { op: 'insert', table: 'workspaces', line: 17, file: 'main.clear', source: "" }); // clear:17
    // clear:18
    return res.status(201).json(saved);
  } catch (err) {
    console.error('[POST /api/workspaces] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/workspaces', line: 16, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:20
// clear:20 — GET /api/workspaces
app.get('/api/workspaces', async (req, res) => {
  try {
    // clear:21
    const workspaces = (await db.findAll('workspaces', {}, { limit: 50 })).map(_revive);
    // clear:22
    return res.json(workspaces);
  } catch (err) {
    console.error('[GET /api/workspaces] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/workspaces', line: 20, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:24
// clear:24 — POST /api/workspaces/:id/members
app.post('/api/workspaces/:id/members', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const member = req.body;
    const incoming = req.params;
    // clear:25
    member.workspace_id = incoming?.id;
    // clear:26
    const saved = await _clearTry(() => db.insert('members', _pick(member, MembersSchema)), { op: 'insert', table: 'members', line: 26, file: 'main.clear', source: "" }); // clear:26
    // clear:27
    return res.status(201).json(saved);
  } catch (err) {
    console.error('[POST /api/workspaces/:id/members] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/workspaces/:id/members', line: 24, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:29
// clear:29 — GET /api/workspaces/:id/items
app.get('/api/workspaces/:id/items', async (req, res) => {
  try {
    // clear:30
    const items = (await db.findAll('items', {}, { limit: 50 })).map(_revive);
    // clear:31
    return res.json(items);
  } catch (err) {
    console.error('[GET /api/workspaces/:id/items] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/workspaces/:id/items', line: 29, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});