#!/usr/bin/env node
// Browser UAT — auto-generated by Clear compiler. Do not hand-edit.
// Contract version: 1
// Pages: 1, controls: 9, apiCalls: 8

const BASE = process.env.TEST_URL || 'http://localhost:3000';
const CONTRACT = {
  "version": 1,
  "generatedAt": "compile-time-static",
  "app": {
    "hasWebTarget": true,
    "hasBackendTarget": true
  },
  "pages": [
    {
      "id": "Onboarding_Tracker",
      "title": "Onboarding Tracker",
      "route": "/",
      "line": 143,
      "expectedText": [
        "Onboarding Tracker",
        "Onboarding",
        "Customer Success",
        "Onboarding command center",
        "Customer Onboarding",
        "Active setup queue for new accounts",
        "customers actively onboarding",
        "Customers",
        "New Customer",
        "Steps"
      ],
      "routeSpecificText": "Onboarding",
      "selector": "[data-clear-page-route=\"/\"]"
    }
  ],
  "routes": [
    {
      "path": "/",
      "pageId": "Onboarding_Tracker",
      "directLoad": true
    }
  ],
  "controls": [
    {
      "id": "nav_item_158_Dashboard",
      "kind": "nav-item",
      "label": "Dashboard",
      "line": 158,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_158_Dashboard\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/"
      },
      "expected": {
        "route": "/",
        "visiblePageId": "Onboarding_Tracker",
        "visibleText": "Onboarding"
      }
    },
    {
      "id": "nav_item_159_Customers",
      "kind": "nav-item",
      "label": "Customers",
      "line": 159,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_159_Customers\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/"
      },
      "expected": {
        "route": "/",
        "visiblePageId": "Onboarding_Tracker",
        "visibleText": "Onboarding"
      }
    },
    {
      "id": "nav_item_160_Steps",
      "kind": "nav-item",
      "label": "Steps",
      "line": 160,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_160_Steps\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/"
      },
      "expected": {
        "route": "/",
        "visiblePageId": "Onboarding_Tracker",
        "visibleText": "Onboarding"
      }
    },
    {
      "id": "nav_item_163_Managers",
      "kind": "nav-item",
      "label": "Managers",
      "line": 163,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"nav_item_163_Managers\"]",
      "action": {
        "type": "navigate",
        "targetRoute": "/"
      },
      "expected": {
        "route": "/",
        "visiblePageId": "Onboarding_Tracker",
        "visibleText": "Onboarding"
      }
    },
    {
      "id": "button_176_Refresh",
      "kind": "button",
      "label": "Refresh",
      "line": 176,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"button_176_Refresh\"]",
      "action": {
        "type": "api-call",
        "method": "GET",
        "path": "/api/customers/onboarding"
      }
    },
    {
      "id": "table_interaction_201_Customers",
      "kind": "table-interaction",
      "label": "Customers",
      "line": 201,
      "sourcePageRoute": "/",
      "selector": "#output_Customers_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Customers_table\"]",
        "sortSelector": "#output_Customers_table th[data-sortable]"
      }
    },
    {
      "id": "table_drilldown_201_Customers",
      "kind": "table-drilldown",
      "label": "Customers",
      "line": 201,
      "sourcePageRoute": "/",
      "selector": "#output_Customers_table button[data-row-select=\"true\"]",
      "action": {
        "type": "drilldown"
      },
      "expected": {
        "detailFor": "selected_customer",
        "detailSelector": "[data-detail-for=\"selected_customer\"]"
      }
    },
    {
      "id": "button_220_Add_Customer",
      "kind": "button",
      "label": "Add Customer",
      "line": 220,
      "sourcePageRoute": "/",
      "selector": "[data-clear-uat-id=\"button_220_Add_Customer\"]",
      "action": {
        "type": "api-call",
        "method": "POST",
        "path": "/api/customers"
      }
    },
    {
      "id": "table_interaction_227_Steps",
      "kind": "table-interaction",
      "label": "Steps",
      "line": 227,
      "sourcePageRoute": "/",
      "selector": "#output_Steps_table",
      "action": {
        "type": "table-interaction",
        "filterSelector": "[data-clear-table-filter-for=\"output_Steps_table\"]",
        "sortSelector": "#output_Steps_table th[data-sortable]"
      }
    }
  ],
  "apiCalls": [
    {
      "method": "GET",
      "path": "/api/customers",
      "line": 58,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/customers/onboarding",
      "line": 61,
      "usedByControlIds": [
        "button_176_Refresh"
      ]
    },
    {
      "method": "POST",
      "path": "/api/customers",
      "line": 64,
      "usedByControlIds": [
        "button_220_Add_Customer"
      ]
    },
    {
      "method": "PUT",
      "path": "/api/customers/:id",
      "line": 72,
      "usedByControlIds": []
    },
    {
      "method": "GET",
      "path": "/api/steps",
      "line": 77,
      "usedByControlIds": []
    },
    {
      "method": "POST",
      "path": "/api/steps",
      "line": 80,
      "usedByControlIds": []
    },
    {
      "method": "PUT",
      "path": "/api/steps/:id",
      "line": 85,
      "usedByControlIds": []
    },
    {
      "method": "POST",
      "path": "/api/seed",
      "line": 92,
      "usedByControlIds": []
    }
  ],
  "warnings": [],
  "errors": []
};
const SCREENSHOT_DIR = process.env.CLEAR_UAT_SCREENSHOT_DIR || '.clear-uat-screenshots';

let passed = 0;
let failed = 0;
const failures = [];

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

async function test(name, fn) {
  try {
    await fn();
    passed += 1;
    console.log('PASS:', name);
  } catch (err) {
    failed += 1;
    const msg = err && err.message ? err.message : String(err);
    failures.push({ name, error: msg });
    console.log('FAIL:', name, '-', msg);
  }
}

function routeUrl(route) {
  return BASE + (route || '/');
}

function pageByRoute(route) {
  return CONTRACT.pages.find(p => p.route === route);
}

function screenshotName(spec) {
  const name = (spec.route || spec.title || 'route')
    .replace(/^\/+/, 'root-')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return (name || 'root') + '.png';
}

async function captureRouteScreenshot(page, spec) {
  if (process.env.CLEAR_UAT_SCREENSHOTS === '0') return;
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  await fs.mkdir(SCREENSHOT_DIR, { recursive: true });
  const file = path.join(SCREENSHOT_DIR, screenshotName(spec));
  await page.screenshot({ path: file, fullPage: false });
  console.log('SHOT:', file);
}

async function assertVisiblePage(page, spec, label) {
  if (!spec) return;
  const selector = '[data-clear-page-route="' + spec.route + '"]';
  const el = page.locator(selector).first();
  await el.waitFor({ state: 'visible', timeout: 3000 });
  if (spec.routeSpecificText) {
    const text = await el.innerText().catch(() => '');
    assert(text.includes(spec.routeSpecificText), label + ' expected page "' + spec.route + '" to show "' + spec.routeSpecificText + '".');
  }
}

async function assertNoPageOverflow(page, spec, label) {
  const layout = await page.evaluate(() => {
    const body = document.body;
    const viewportWidth = document.documentElement.clientWidth;
    const scrollWidth = Math.max(document.documentElement.scrollWidth, body ? body.scrollWidth : 0);
    return { viewportWidth, scrollWidth, overflowX: scrollWidth - viewportWidth };
  });
  assert(layout.overflowX <= 2, label + ' has page-level horizontal overflow on ' + spec.route + ': viewport=' + layout.viewportWidth + ', scrollWidth=' + layout.scrollWidth);
}

async function assertPersistentShell(page, spec, label) {
  if (/^\/(login|signup|auth)(\/|$)/.test(spec.route || '')) return;
  const root = page.locator('[data-clear-shell-root="true"]');
  if (await root.count() === 0) return;
  await root.first().waitFor({ state: 'visible', timeout: 3000 });
  const outlet = page.locator('[data-clear-shell-outlet="true"]').first();
  if (await outlet.count() > 0) await outlet.waitFor({ state: 'visible', timeout: 3000 });
  const shellText = await root.first().innerText().catch(() => '');
  assert(shellText.length > 0, label + ' expected the app shell to stay visible.');
}

let chromium;
try {
  ({ chromium } = await import('playwright'));
} catch (err) {
  console.log('FAIL: Browser UAT setup — generated browser UAT requires the dev dependency "playwright". Run: npm install --save-dev playwright');
  process.exitCode = 1;
}

if (chromium) {
  const browser = await chromium.launch({ headless: process.env.CLEAR_UAT_HEADLESS !== '0' });
  const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
  const consoleErrors = [];
  page.on('console', msg => {
    if (msg.type() === 'error' && !String(msg.text()).includes('favicon')) consoleErrors.push(msg.text());
  });
  page.on('pageerror', err => consoleErrors.push(err.message));

  try {
    for (const spec of CONTRACT.pages) {
      await test('Direct route: ' + spec.title, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(spec.route), { waitUntil: 'networkidle' });
        await assertVisiblePage(page, spec, 'Direct route ' + spec.title);
        await assertPersistentShell(page, spec, 'Direct route ' + spec.title);
        await assertNoPageOverflow(page, spec, 'Direct route ' + spec.title);
        await captureRouteScreenshot(page, spec);
        assert(consoleErrors.length === 0, 'Browser errors on ' + spec.route + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'navigate' && c.expected)) {
      await test('Click ' + control.kind + ': ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        await page.locator('[data-clear-uat-id="' + control.id + '"]').first().click();
        await page.waitForTimeout(75);
        const expectedPage = pageByRoute(control.expected.route);
        await assertVisiblePage(page, expectedPage, 'Click ' + control.kind + ' "' + control.label + '" [clear:' + control.line + ']');
        await assertPersistentShell(page, expectedPage, 'Click ' + control.kind + ' "' + control.label + '" [clear:' + control.line + ']');
        assert(consoleErrors.length === 0, 'Browser errors after clicking ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'table-interaction')) {
      await test('Use table controls: ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        const table = page.locator(control.selector).first();
        await table.waitFor({ state: 'visible', timeout: 3000 });
        const filter = page.locator(control.action.filterSelector).first();
        if (await filter.count() === 0) return;
        await filter.waitFor({ state: 'visible', timeout: 3000 });
        const rows = table.locator('tbody tr');
        const sortHeaders = page.locator(control.action.sortSelector);
        if (await sortHeaders.count() > 0) {
          const header = sortHeaders.first();
          await header.click();
          await page.waitForTimeout(75);
          const sortedClass = await header.getAttribute('class') || '';
          const sortedDir = await header.getAttribute('data-sort-dir') || '';
          assert(sortedClass.split(/\s+/).includes('is-sorted') || sortedDir.length > 0, 'Table "' + control.label + '" sortable header should show sorted state.');
        }
        if (await rows.count() > 0) {
          const rowText = (await rows.first().innerText().catch(() => '')).trim();
          const token = (rowText.match(/[A-Za-z][A-Za-z0-9_-]{2,}/) || [])[0] || '';
          if (token) {
            await filter.fill(token);
            await page.waitForTimeout(75);
            const filteredText = (await table.innerText().catch(() => '')).toLowerCase();
            assert(filteredText.includes(token.toLowerCase()), 'Table "' + control.label + '" quick filter should show matching text.');
          }
        }
        assert(consoleErrors.length === 0, 'Browser errors after using table controls ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }

    for (const control of CONTRACT.controls.filter(c => c.action && c.action.type === 'drilldown')) {
      await test('Click ' + control.kind + ': ' + control.label, async () => {
        consoleErrors.length = 0;
        await page.goto(routeUrl(control.sourcePageRoute || CONTRACT.pages[0].route), { waitUntil: 'networkidle' });
        const clickTarget = page.locator(control.selector).first();
        if (await clickTarget.count() === 0) return;
        await clickTarget.waitFor({ state: 'visible', timeout: 3000 });
        await clickTarget.click();
        await page.waitForTimeout(100);
        const detailSelector = control.expected && control.expected.detailSelector
          ? control.expected.detailSelector
          : '[data-detail-for="' + (control.expected?.detailFor || '') + '"]';
        const detail = page.locator(detailSelector).first();
        await detail.waitFor({ state: 'visible', timeout: 3000 });
        const text = (await detail.innerText().catch(() => '')).trim();
        assert(text.length > 0, 'Click table drilldown "' + control.label + '" should show detail text.');
        assert(consoleErrors.length === 0, 'Browser errors after clicking table drilldown ' + control.label + ': ' + consoleErrors.join('; '));
      });
    }
  } finally {
    await browser.close();
  }
}

console.log('Browser UAT:', passed, 'passed,', failed, 'failed');
process.exitCode = failed > 0 ? 1 : 0;
