// Generated by Clear v1.0
const _clearLineMap = process.env.CLEAR_DEBUG ? {"326":17,"329":21,"341":30,"354":47,"355":47,"358":48,"360":48,"369":50,"370":50,"373":51,"375":51,"384":53,"385":53,"391":54,"393":55,"396":58,"397":58,"398":59,"408":61,"409":61,"414":62,"416":63,"419":63,"421":64,"431":66,"432":66,"435":67,"438":67,"447":69,"448":69,"453":70,"455":71,"456":71,"457":72,"467":74,"468":74,"473":75,"475":76,"478":76,"480":77,"491":81,"492":81,"500":82,"502":88,"503":88,"504":89,"506":95,"507":95,"508":96,"510":102,"511":102,"512":103,"514":107,"515":107,"516":108,"518":112,"519":112,"520":113,"522":117,"523":117,"524":118,"526":122,"527":122,"528":123,"530":127,"531":127,"532":128,"545":162,"547":163,"554":164,"556":165,"561":167,"563":168} : null;
// ┌─────────────────────────────────────────────┐
// │         CLEAR APP — Architecture            │
// └─────────────────────────────────────────────┘
//
// TABLES:
//   Customers: name*, company*, email, status, started_at_date, account_manager, notes (line 21)
//   OnboardingSteps: customer_id*, step_name*, completed, completed_at_date, customer (line 30)
//
// ENDPOINTS:
//   GET /api/customers (line 47)
//   GET /api/customers/onboarding (line 50)
//   POST /api/customers [auth] (line 53)
//   PUT /api/customers/:id [auth] (line 61)
//   GET /api/steps (line 66)
//   POST /api/steps [auth] (line 69)
//   PUT /api/steps/:id [auth] (line 74)
//   POST /api/seed (line 81)
//
// PAGES:
//   'Onboarding Tracker' at / (line 132)
//
// DATAFLOW: Frontend ──> API ──> Database
//

const express = require('express');
const db = require('./clear-runtime/db');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const app = express();
app.use(express.json());
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed") return res.status(400).json({ error: "Invalid JSON in request body" });
  next(err);
});
// CF-1: runtime instrumentation — fire-and-forget beacons to the Compiler Flywheel.
const _CLEAR_FLYWHEEL_URL = process.env.CLEAR_FLYWHEEL_URL;
const _CLEAR_COMPILE_ROW_ID = process.env.CLEAR_COMPILE_ROW_ID;
function _clearBeacon(event) {
  if (!_CLEAR_FLYWHEEL_URL || !_CLEAR_COMPILE_ROW_ID) return;
  try {
    fetch(_CLEAR_FLYWHEEL_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(Object.assign({ compile_row_id: _CLEAR_COMPILE_ROW_ID, ts: Date.now() }, event)),
      signal: AbortSignal.timeout(500),
    }).catch(() => {});
  } catch {}
}
app.use((req, res, next) => {
  const _t0 = Date.now();
  res.on('finish', () => {
    _clearBeacon({ event_type: 'endpoint_latency', method: req.method, path: req.route ? req.route.path : req.path, status: res.statusCode, duration_ms: Date.now() - _t0 });
  });
  next();
});
app.use((err, req, res, next) => {
  _clearBeacon({ event_type: 'endpoint_error', method: req.method, path: req.path, error_sig: (err && err.message ? String(err.message).substring(0, 200) : 'unknown') });
  next(err);
});
// Log every request
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const ms = Date.now() - start;
    console.log(`${req.method} ${req.path} ${res.statusCode} ${ms}ms`);
  });
  next();
});
// Allow cross-origin requests
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});
// Auth scaffolding from `allow signup and login` (clear:42)
//   emits: POST /auth/signup, POST /auth/login, GET /auth/me
//   plus:  requireLogin middleware, requireRole middleware, JWT secret, bcrypt + jwt requires
const _JWT_SECRET = process.env.JWT_SECRET || require('crypto').randomBytes(32).toString('hex');
const _users = [];

// JWT middleware — extracts user from token on every request
app.use((req, res, next) => {
  const authHeader = req.headers.authorization || '';
  if (authHeader.startsWith('Bearer ')) {
    try {
      req.user = jwt.verify(authHeader.slice(7), _JWT_SECRET);
    } catch(e) { req.user = null; }
  }
  next();
});

// POST /auth/signup — create new user
app.post('/auth/signup', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    if (_users.find(u => u.email === email)) return res.status(400).json({ error: 'Email already registered' });
    const password_hash = await bcrypt.hash(password, 10);
    const user = { id: _users.length + 1, email, password_hash, role: 'user', created_at: new Date().toISOString() };
    _users.push(user);
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.status(201).json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// POST /auth/login — authenticate user
app.post('/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });
    const user = _users.find(u => u.email === email);
    if (!user) return res.status(401).json({ error: 'Invalid email or password' });
    const valid = await bcrypt.compare(password, user.password_hash);
    if (!valid) return res.status(401).json({ error: 'Invalid email or password' });
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, _JWT_SECRET, { expiresIn: "7d" });
    res.json({ token, user: { id: user.id, email: user.email, role: user.role } });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// GET /auth/me — return current user
app.get('/auth/me', (req, res) => {
  if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
  const user = _users.find(u => u.id === req.user.id);
  if (!user) return res.status(404).json({ error: 'User not found' });
  res.json({ id: user.id, email: user.email, role: user.role, created_at: user.created_at });
});

// --- Live App Editing routes (Meph edit widget) ---
// Widget is served from a static file in clear-runtime/. API calls
// proxy to Studio (when STUDIO_PORT is set in the environment). In
// a standalone deploy STUDIO_PORT is unset and the API path 503s.
const _MEPH_WIDGET_PATH = require('path').join(__dirname, 'clear-runtime', 'meph-widget.js');
app.get('/__meph__/widget.js', (req, res) => {
  try {
    res.type('application/javascript').send(require('fs').readFileSync(_MEPH_WIDGET_PATH, 'utf8'));
  } catch(e) { res.status(404).send('// widget bundle not found'); }
});
app.all('/__meph__/api/:action', async (req, res) => {
  const studioPort = process.env.STUDIO_PORT;
  if (!studioPort) {
    return res.status(503).json({ error: 'Live editing is not available in this environment (STUDIO_PORT not set)' });
  }
  try {
    const upstream = 'http://localhost:' + studioPort + '/__meph__/api/' + req.params.action;
    const r = await fetch(upstream, {
      method: req.method,
      headers: { 'Content-Type': 'application/json', 'Authorization': req.headers.authorization || '' },
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined : JSON.stringify(req.body || {}),
    });
    const body = await r.text();
    res.status(r.status).type(r.headers.get('content-type') || 'application/json').send(body);
  } catch(e) {
    res.status(502).json({ error: 'Proxy to Studio failed: ' + e.message });
  }
});

// Built-in utilities
function _pick(obj, schema) { return Object.fromEntries(Object.entries(obj).filter(([k]) => k in schema).map(([k, v]) => [k, v !== null && typeof v === "object" ? JSON.stringify(v) : v])); }
function _revive(record) { if (!record) return record; const out = {}; for (const [k, v] of Object.entries(record)) { if (typeof v === "string" && (v[0] === "{" || v[0] === "[")) { try { out[k] = JSON.parse(v); } catch(_) { out[k] = v; } } else { out[k] = v; } } return out; }
function _validate(body, rules) {
  if (body == null || typeof body !== 'object') return [{ field: '_body', message: 'Request body is required' }];
  const _errs = [];
  for (const r of rules) {
    let v = body[r.field];
    if (r.required && (v == null || v === '')) { _errs.push({ field: r.field, message: r.field + ' is required' }); continue; }
    if (v == null) continue;
    if (r.type === 'number' && typeof v === 'string' && v.trim() !== '' && !isNaN(Number(v))) { body[r.field] = Number(v); v = body[r.field]; }
    if (r.type === 'number' && typeof v !== 'number') { _errs.push({ field: r.field, message: r.field + ' must be a number' }); continue; }
    if (r.type === 'boolean' && typeof v !== 'boolean') { _errs.push({ field: r.field, message: r.field + ' must be true or false' }); continue; }
    if (r.min != null && r.type === 'text' && String(v).length < r.min) _errs.push({ field: r.field, message: r.field + ' must be at least ' + r.min + (r.min === 1 ? ' character' : ' characters') });
    if (r.max != null && r.type === 'text' && String(v).length > r.max) _errs.push({ field: r.field, message: r.field + ' must be at most ' + r.max + (r.max === 1 ? ' character' : ' characters') });
    if (r.min != null && r.type !== 'text' && v < r.min) _errs.push({ field: r.field, message: r.field + ' must be at least ' + r.min });
    if (r.max != null && r.type !== 'text' && v > r.max) _errs.push({ field: r.field, message: r.field + ' must be at most ' + r.max });
    if (r.matches === 'email' && !/^[^@]+@[^@]+\.[^@]+$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid email' });
    if (r.matches === 'time' && !/^([01]\d|2[0-3]):[0-5]\d$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid time (HH:MM)' });
    if (r.matches === 'phone' && !/^[\+]?[\d\s\-\.\(\)]{7,15}$/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid phone number' });
    if (r.matches === 'url' && !/^https?:\/\/.+/.test(v)) _errs.push({ field: r.field, message: r.field + ' must be a valid URL' });
    if (r.oneOf && !r.oneOf.includes(v)) _errs.push({ field: r.field, message: r.field + ' must be one of: ' + r.oneOf.join(', ') });
  }
  return _errs.length ? _errs : null;
}
function _clearError(err, ctx) {
  const debug = typeof process !== 'undefined' && process.env.CLEAR_DEBUG;
  const status = err.status || (err.message && (err.message.includes('required') || err.message.includes('must be') || err.message.includes('must be unique') || err.message.includes('already exists')) ? 400 : 500);
  const safeMsg = status === 400 ? err.message : 'Something went wrong';
  // Always compute hints and structured info (not just in debug mode)
  // Debug mode adds verbose context; non-debug still gets hints.
  const PII_FIELDS = ['password','secret','token','key','credit_card','ssn','api_key','api_secret'];
  function redact(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    const out = Array.isArray(obj) ? [...obj] : { ...obj };
    for (const k of Object.keys(out)) {
      if (PII_FIELDS.some(p => k.toLowerCase().includes(p))) out[k] = '[REDACTED]';
      else if (typeof out[k] === 'object') out[k] = redact(out[k]);
    }
    return out;
  }
  const map = typeof _clearMap !== 'undefined' ? _clearMap : null;
  let hint = '';
  const msg = err.message || '';
  if (msg.includes('required')) {
    const field = msg.match(/^(\w+) is required/);
    let tableInfo = ctx.table || 'this table';
    if (field && map && map.tables && ctx.table && map.tables[ctx.table]) {
      const t = map.tables[ctx.table];
      tableInfo = ctx.table + " (defined at " + t.file + " line " + t.line + ")";
    }
    hint = field ? "'" + field[1] + "' is required in " + tableInfo + ". Add it to the form or remove 'required' from the table definition." : msg;
  } else if (msg.includes('must be unique') || msg.includes('already exists')) {
    hint = "A record with this value already exists. Check for duplicates before saving.";
  } else if (msg.includes('Authentication required') || msg.includes('No token')) {
    hint = "This endpoint needs login. Add 'needs login' to the endpoint definition.";
  } else if (msg.includes('Requires role') || msg.includes('requires role')) {
    const role = msg.match(/role '?(\w+)'?/);
    hint = role ? "User needs '" + role[1] + "' role." : "User does not have the required role.";
  } else if (msg.includes('must be a')) {
    hint = msg + ". Check the form or API call.";
  } else if (msg.includes('API') || msg.includes('api')) {
    const svc = ctx.service || 'external';
    hint = svc + " API call failed. Check the API key and account.";
  } else if (msg.includes('aborted') || msg.includes('timed out') || msg.includes('timeout')) {
    hint = "Request timed out. Check if the service is running.";
  } else {
    hint = msg;
  }
  let suggested_fix = null;
  if (map) {
    if (msg.includes('required')) {
      const field = msg.match(/^(\w+) is required/);
      if (field && ctx.table && map.tables && map.tables[ctx.table]) {
        const t = map.tables[ctx.table];
        suggested_fix = { file: t.file, line: t.line, action: 'info', explanation: "Ensure '" + field[1] + "' is included in the request body. The table at " + t.file + " line " + t.line + " requires it." };
      }
    } else if (msg.includes('Authentication required') || msg.includes('No token')) {
      if (ctx.line && ctx.file) {
        suggested_fix = { file: ctx.file, line: ctx.line, action: 'add_line_after', content: "  needs login", explanation: "Add 'needs login' to the endpoint definition." };
      }
    }
  }
  // Translate JS stack trace to a Clear line number using the embedded source map.
  // _clearLineMap is { jsLine: clearLine } injected at compile time.
  let clearLineFromStack = null;
  const lineMapRef = typeof _clearLineMap !== 'undefined' ? _clearLineMap : null;
  if (err.stack && lineMapRef) {
    const stackLines = err.stack.split('\n');
    for (const sl of stackLines) {
      const m = sl.match(/\bserver\.js:(\d+)/);
      if (m) {
        const jsLine = parseInt(m[1]);
        const mapKeys = Object.keys(lineMapRef).map(Number).sort((a, b) => a - b);
        for (let i = mapKeys.length - 1; i >= 0; i--) {
          if (mapKeys[i] <= jsLine) { clearLineFromStack = lineMapRef[mapKeys[i]]; break; }
        }
        break;
      }
    }
  }
  // Most specific Clear line wins: stack-traced statement > endpoint ctx > null
  const resolvedClearLine = clearLineFromStack || ctx.line || null;
  const result = {
    status,
    response: {
      error: safeMsg,
      clear_line: resolvedClearLine,
      clear_file: ctx.file || null,
      hint: hint,
      ...(debug ? { technical: msg, clear_source: ctx.source || null } : {})
    }
  };
  if (clearLineFromStack && clearLineFromStack !== ctx.line) {
    result.response.clear_line_endpoint = ctx.line || null;
  }
  if (suggested_fix) result.response.suggested_fix = suggested_fix;
  if (debug === 'verbose' && ctx) {
    const tableSchema = (map && map.tables && ctx.table) ? map.tables[ctx.table] : null;
    result.response.context = redact({
      endpoint: ctx.endpoint || null,
      input: ctx.input || null,
      schema: tableSchema ? tableSchema.fields : (ctx.schema || null),
      table: ctx.table || null
    });
  }
  return result;
}
async function _clearTry(fn, ctx) {
  try { return await fn(); } catch (err) {
    err._clearCtx = ctx;
    throw err;
  }
}

// Source map for error translator (only active with CLEAR_DEBUG)
const _clearMap = process.env.CLEAR_DEBUG ? {
  tables: {
    customers: { line: 21, file: "main.clear", fields: { name: { required: true, type: "text" }, company: { required: true, type: "text" }, email: { type: "text" }, status: { type: "text" }, started_at_date: { type: "timestamp" }, account_manager: { type: "text" }, notes: { type: "text" } } },
    onboardingsteps: { line: 30, file: "main.clear", fields: { customer_id: { required: true, type: "fk" }, step_name: { required: true, type: "text" }, completed: { type: "boolean" }, completed_at_date: { type: "text" }, customer: { type: "fk" } } },
  },
  endpoints: {
    "GET /api/customers": { line: 47, file: "main.clear", auth: false },
    "GET /api/customers/onboarding": { line: 50, file: "main.clear", auth: false },
    "POST /api/customers": { line: 53, file: "main.clear", auth: true },
    "PUT /api/customers/:id": { line: 61, file: "main.clear", auth: true },
    "GET /api/steps": { line: 66, file: "main.clear", auth: false },
    "POST /api/steps": { line: 69, file: "main.clear", auth: true },
    "PUT /api/steps/:id": { line: 74, file: "main.clear", auth: true },
    "POST /api/seed": { line: 81, file: "main.clear", auth: false },
  }
} : null;

// Onboarding Tracker — multi-step progress for each new customer
// 
//   ┌──────────┐            ┌──────────┐  has many   ┌──────────┐
//   │  Ops     │ ─► CRUD ─► │Customers │ ──────────► │  Steps   │
//   └──────────┘            └──────────┘             └──────────┘
//        │                       │
//        │                       │ progress % computed from
//        │                       │ completed_steps / total_steps
//        │                       │
//        └── view ────────────►  │
//                                │
//                       Status: onboarding / active / churned
// clear:17
// Database: local memory (JSON file backup)
// Database
// clear:21
// Data shape: Customers
const CustomersSchema = {
  name: { type: "text", required: true },
  company: { type: "text", required: true },
  email: { type: "text" },
  status: { type: "text", default: "onboarding" },
  started_at_date: { type: "timestamp", auto: true },
  account_manager: { type: "text" },
  notes: { type: "text" }
};
db.createTable('customers', CustomersSchema);
// clear:30
// Data shape: OnboardingSteps
const OnboardingStepsSchema = {
  customer_id: { type: "fk", required: true },
  step_name: { type: "text", required: true },
  completed: { type: "boolean", default: false },
  completed_at_date: { type: "text" },
  customer: { type: "fk", ref: "Customers" }
};
db.createTable('onboardingsteps', OnboardingStepsSchema);
// Backend
// # Middleware
// # Endpoints
// clear:47
// clear:47 — GET /api/customers
app.get('/api/customers', async (req, res) => {
  try {
    // clear:48
    const _resp_48 = (await db.findAll('customers', {}, { limit: 50 })).map(_revive);
    // clear:48
    return res.json(_resp_48);
  } catch (err) {
    console.error('[GET /api/customers] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/customers', line: 47, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:50
// clear:50 — GET /api/customers/onboarding
app.get('/api/customers/onboarding', async (req, res) => {
  try {
    // clear:51
    const _resp_51 = (await db.findAll('customers', { status: "onboarding" }, { limit: 50 })).map(_revive);
    // clear:51
    return res.json(_resp_51);
  } catch (err) {
    console.error('[GET /api/customers/onboarding] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/customers/onboarding', line: 50, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:53
// clear:53 — POST /api/customers
app.post('/api/customers', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const customer = req.body;
    const incoming = req.params;
    // clear:54
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:55
    const _vErrs = _validate(req.body, [{"field":"name","type":"text","required":true}, {"field":"company","type":"text","required":true}]);
    if (_vErrs) return res.status(400).json({ errors: _vErrs });
    // clear:58
    const new_customer = await _clearTry(() => db.insert('customers', _pick(customer, CustomersSchema)), { op: 'insert', table: 'customers', line: 58, file: 'main.clear', source: "" }); // clear:58
    // clear:59
    return res.status(201).json({ ...new_customer, message: "success" });
  } catch (err) {
    console.error('[POST /api/customers] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/customers', line: 53, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:61
// clear:61 — PUT /api/customers/:id
app.put('/api/customers/:id', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const customer = req.body;
    // clear:62
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:63
    const _picked_customer = _pick(customer, CustomersSchema);
    _picked_customer.id = req.params.id;
    await _clearTry(() => db.update('customers', _picked_customer), { op: 'update', table: 'customers', line: 63, file: 'main.clear', source: "" }); // clear:63
    Object.assign(customer, await db.findOne('customers', { id: _picked_customer.id }) || {});
    // clear:64
    return res.status(200).json({ message: "updated" });
  } catch (err) {
    console.error('[PUT /api/customers/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'PUT /api/customers/:id', line: 61, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:66
// clear:66 — GET /api/steps
app.get('/api/steps', async (req, res) => {
  try {
    // clear:67
    const _resp_67 = (await db.findAll('onboardingsteps', {}, { limit: 50 })).map(_revive);
    for (const _item of _resp_67) { if (_item.customer) _item.customer = await db.findOne('customers', { id: _item.customer }); }
    // clear:67
    return res.json(_resp_67);
  } catch (err) {
    console.error('[GET /api/steps] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'GET /api/steps', line: 66, file: 'main.clear' }, err._clearCtx || {});
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:69
// clear:69 — POST /api/steps
app.post('/api/steps', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const step = req.body;
    // clear:70
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:71
    const new_step = await _clearTry(() => db.insert('onboardingsteps', _pick(step, OnboardingStepsSchema)), { op: 'insert', table: 'onboardingsteps', line: 71, file: 'main.clear', source: "" }); // clear:71
    // clear:72
    return res.status(201).json({ ...new_step, message: "success" });
  } catch (err) {
    console.error('[POST /api/steps] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/steps', line: 69, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// clear:74
// clear:74 — PUT /api/steps/:id
app.put('/api/steps/:id', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const step = req.body;
    // clear:75
    if (!req.user) { return res.status(401).json({ error: "Authentication required" }); }
    // clear:76
    const _picked_step = _pick(step, OnboardingStepsSchema);
    _picked_step.id = req.params.id;
    await _clearTry(() => db.update('onboardingsteps', _picked_step), { op: 'update', table: 'onboardingsteps', line: 76, file: 'main.clear', source: "" }); // clear:76
    Object.assign(step, await db.findOne('onboardingsteps', { id: _picked_step.id }) || {});
    // clear:77
    return res.status(200).json({ message: "updated" });
  } catch (err) {
    console.error('[PUT /api/steps/:id] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'PUT /api/steps/:id', line: 74, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// # Seed Data
// clear:81
// clear:81 — POST /api/seed
app.post('/api/seed', async (req, res) => {
  try {
    if (process.env.NODE_ENV === 'production') return res.status(403).json({ error: 'Seed endpoint is disabled in production' });
    const _existing = await db.findAll('customers');
    if (_existing.length > 0) return res.json({ message: 'already seeded' });
    if (!req.body || typeof req.body !== 'object') return res.status(400).json({ error: 'Request body is required (send JSON with Content-Type: application/json)' });
    const seed = req.body;
    // clear:82
    let c1 = { name: "Priya Shah", company: "Acme Corp", email: "priya@acmecorp.com", status: "onboarding", account_manager: "sarah.j" };
    // clear:88
    await _clearTry(() => db.insert('customers', _pick(c1, CustomersSchema)), { op: 'insert', table: 'customers', line: 88, file: 'main.clear', source: "" }); // clear:88
    // clear:89
    let c2 = { name: "Marcus Jones", company: "Shopify Shops", email: "mj@shopify-shops.com", status: "onboarding", account_manager: "mike.l" };
    // clear:95
    await _clearTry(() => db.insert('customers', _pick(c2, CustomersSchema)), { op: 'insert', table: 'customers', line: 95, file: 'main.clear', source: "" }); // clear:95
    // clear:96
    let c3 = { name: "Jenna Liu", company: "Tiny Studio", email: "jenna@tinystudio.co", status: "active", account_manager: "sarah.j" };
    // clear:102
    await _clearTry(() => db.insert('customers', _pick(c3, CustomersSchema)), { op: 'insert', table: 'customers', line: 102, file: 'main.clear', source: "" }); // clear:102
    // clear:103
    let s1 = { customer_id: c1?.id, step_name: "Kickoff call", completed: true };
    // clear:107
    await _clearTry(() => db.insert('onboardingsteps', _pick(s1, OnboardingStepsSchema)), { op: 'insert', table: 'onboardingsteps', line: 107, file: 'main.clear', source: "" }); // clear:107
    // clear:108
    let s2 = { customer_id: c1?.id, step_name: "Technical setup", completed: true };
    // clear:112
    await _clearTry(() => db.insert('onboardingsteps', _pick(s2, OnboardingStepsSchema)), { op: 'insert', table: 'onboardingsteps', line: 112, file: 'main.clear', source: "" }); // clear:112
    // clear:113
    let s3 = { customer_id: c1?.id, step_name: "First campaign launched", completed: false };
    // clear:117
    await _clearTry(() => db.insert('onboardingsteps', _pick(s3, OnboardingStepsSchema)), { op: 'insert', table: 'onboardingsteps', line: 117, file: 'main.clear', source: "" }); // clear:117
    // clear:118
    let s4 = { customer_id: c2?.id, step_name: "Kickoff call", completed: true };
    // clear:122
    await _clearTry(() => db.insert('onboardingsteps', _pick(s4, OnboardingStepsSchema)), { op: 'insert', table: 'onboardingsteps', line: 122, file: 'main.clear', source: "" }); // clear:122
    // clear:123
    let s5 = { customer_id: c2?.id, step_name: "Technical setup", completed: false };
    // clear:127
    await _clearTry(() => db.insert('onboardingsteps', _pick(s5, OnboardingStepsSchema)), { op: 'insert', table: 'onboardingsteps', line: 127, file: 'main.clear', source: "" }); // clear:127
    // clear:128
    return res.status(201).json({ message: "seeded" });
  } catch (err) {
    console.error('[POST /api/seed] Error:', err.message);
    const _ctx = Object.assign({ endpoint: 'POST /api/seed', line: 81, file: 'main.clear' }, err._clearCtx || {});
    if (typeof process !== 'undefined' && process.env.CLEAR_DEBUG === 'verbose') _ctx.input = req.body;
    const _info = _clearError(err, _ctx);
    res.status(_info.status).json(_info.response);
  }
});
// Frontend
// Tests
if (typeof test === 'function') {
// clear:162
test("can user create a customer with name is 'Test' , company is 'TestCo'", async () => {
  // clear:163
  _response = await fetch(_baseUrl + "/api/customers", {
    method: "POST", headers: AUTH_HEADERS,
    body: JSON.stringify({ "name": "Test", "company": "TestCo" })
  });
  _responseBody = await _response.json().catch(() => null);
  assert(_response.status >= 200 && _response.status < 300, "Create should succeed, got " + _response.status);
  // clear:164
  _expectSuccess(_response);
  // clear:165
  _expectBodyHas(_responseBody, "id");
});
}
if (typeof test === 'function') {
// clear:167
test("creating a customer should require login", async () => {
  // clear:168
  _response = await fetch(_baseUrl + "/api/customers", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ test: true })
  });
  assert(_response.status === 401, "Should require login, got " + _response.status);
});
}

const path = require('path');
app.use(express.static(__dirname));
app.get("/", (req, res) => res.sendFile('index.html', { root: __dirname }));

const PORT = process.env.PORT || 3000;
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});
process.on('SIGINT', () => {
  console.log('Shutting down...');
  server.close(() => process.exit(0));
});